// Code generated by pigeon; DO NOT EDIT.

package leftrecursionlabeledfailures

import (
	"errors"
	"io"
	"sync"
	"unicode"
)

func ids(list, id any) (any, error) { _ = "STUB: not implemented"; return *new(any), nil }

func toStringSlice(v any) []string { _ = "STUB: not implemented"; return nil }

var g = &grammar{
	rules: []*rule{
		{
			name: "S",
			pos:  position{line: 18, col: 1, offset: 244},
			expr: &recoveryExpr{
				pos: position{line: 18, col: 5, offset: 250},
				expr: &recoveryExpr{
					pos: position{line: 18, col: 5, offset: 250},
					expr: &actionExpr{
						pos: position{line: 18, col: 5, offset: 250},
						run: (*parser).callonS3,
						expr: &labeledExpr{
							pos:   position{line: 18, col: 5, offset: 250},
							label: "list",
							expr: &ruleRefExpr{
								pos:  position{line: 18, col: 10, offset: 255},
								name: "List",
							},
						},
					},
					recoverExpr: &ruleRefExpr{
						pos:  position{line: 20, col: 16, offset: 309},
						name: "ErrComma",
					},
					failureLabel: []string{
						"errComma",
					},
				},
				recoverExpr: &ruleRefExpr{
					pos:  position{line: 20, col: 35, offset: 328},
					name: "ErrID",
				},
				failureLabel: []string{
					"errId",
				},
			},
			leader:        false,
			leftRecursive: false,
		},
		{
			name: "List",
			pos:  position{line: 22, col: 1, offset: 335},
			expr: &choiceExpr{
				pos: position{line: 22, col: 8, offset: 344},
				alternatives: []any{
					&actionExpr{
						pos: position{line: 22, col: 8, offset: 344},
						run: (*parser).callonList2,
						expr: &seqExpr{
							pos: position{line: 22, col: 9, offset: 345},
							exprs: []any{
								&labeledExpr{
									pos:   position{line: 22, col: 9, offset: 345},
									label: "list",
									expr: &ruleRefExpr{
										pos:  position{line: 22, col: 14, offset: 350},
										name: "List",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 22, col: 19, offset: 355},
									name: "Comma",
								},
								&labeledExpr{
									pos:   position{line: 22, col: 25, offset: 361},
									label: "id",
									expr: &ruleRefExpr{
										pos:  position{line: 22, col: 28, offset: 364},
										name: "ID",
									},
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 24, col: 5, offset: 399},
						run: (*parser).callonList9,
						expr: &labeledExpr{
							pos:   position{line: 24, col: 5, offset: 399},
							label: "id",
							expr: &ruleRefExpr{
								pos:  position{line: 24, col: 8, offset: 402},
								name: "ID",
							},
						},
					},
				},
			},
			leader:        true,
			leftRecursive: true,
		},
		{
			name: "ID",
			pos:  position{line: 28, col: 1, offset: 448},
			expr: &choiceExpr{
				pos: position{line: 28, col: 6, offset: 455},
				alternatives: []any{
					&actionExpr{
						pos: position{line: 28, col: 6, offset: 455},
						run: (*parser).callonID2,
						expr: &seqExpr{
							pos: position{line: 28, col: 6, offset: 455},
							exprs: []any{
								&ruleRefExpr{
									pos:  position{line: 28, col: 6, offset: 455},
									name: "Sp",
								},
								&oneOrMoreExpr{
									pos: position{line: 28, col: 9, offset: 458},
									expr: &charClassMatcher{
										pos:        position{line: 28, col: 9, offset: 458},
										val:        "[a-z]",
										ranges:     []rune{'a', 'z'},
										ignoreCase: false,
										inverted:   false,
									},
								},
							},
						},
					},
					&throwExpr{
						pos:   position{line: 30, col: 5, offset: 531},
						label: "errId",
					},
				},
			},
			leader:        false,
			leftRecursive: false,
		},
		{
			name: "Comma",
			pos:  position{line: 32, col: 1, offset: 541},
			expr: &choiceExpr{
				pos: position{line: 32, col: 9, offset: 551},
				alternatives: []any{
					&seqExpr{
						pos: position{line: 32, col: 9, offset: 551},
						exprs: []any{
							&ruleRefExpr{
								pos:  position{line: 32, col: 9, offset: 551},
								name: "Sp",
							},
							&litMatcher{
								pos:        position{line: 32, col: 12, offset: 554},
								val:        ",",
								ignoreCase: false,
								want:       "\",\"",
							},
						},
					},
					&throwExpr{
						pos:   position{line: 32, col: 18, offset: 560},
						label: "errComma",
					},
				},
			},
			leader:        false,
			leftRecursive: false,
		},
		{
			name: "Sp",
			pos:  position{line: 33, col: 1, offset: 572},
			expr: &zeroOrMoreExpr{
				pos: position{line: 33, col: 6, offset: 579},
				expr: &charClassMatcher{
					pos:        position{line: 33, col: 6, offset: 579},
					val:        "[ \\t\\r\\n]",
					chars:      []rune{' ', '\t', '\r', '\n'},
					ignoreCase: false,
					inverted:   false,
				},
			},
			leader:        false,
			leftRecursive: false,
		},
		{
			name: "ErrComma",
			pos:  position{line: 35, col: 1, offset: 591},
			expr: &seqExpr{
				pos: position{line: 35, col: 12, offset: 604},
				exprs: []any{
					&stateCodeExpr{
						pos: position{line: 35, col: 12, offset: 604},
						run: (*parser).callonErrComma2,
					},
					&zeroOrMoreExpr{
						pos: position{line: 37, col: 7, offset: 656},
						expr: &seqExpr{
							pos: position{line: 37, col: 9, offset: 658},
							exprs: []any{
								&notExpr{
									pos: position{line: 37, col: 9, offset: 658},
									expr: &oneOrMoreExpr{
										pos: position{line: 37, col: 11, offset: 660},
										expr: &charClassMatcher{
											pos:        position{line: 37, col: 11, offset: 660},
											val:        "[a-z]",
											ranges:     []rune{'a', 'z'},
											ignoreCase: false,
											inverted:   false,
										},
									},
								},
								&anyMatcher{
									line: 37, col: 19, offset: 668,
								},
							},
						},
					},
				},
			},
			leader:        false,
			leftRecursive: false,
		},
		{
			name: "ErrID",
			pos:  position{line: 38, col: 1, offset: 672},
			expr: &actionExpr{
				pos: position{line: 38, col: 9, offset: 682},
				run: (*parser).callonErrID1,
				expr: &seqExpr{
					pos: position{line: 38, col: 9, offset: 682},
					exprs: []any{
						&stateCodeExpr{
							pos: position{line: 38, col: 9, offset: 682},
							run: (*parser).callonErrID3,
						},
						&zeroOrMoreExpr{
							pos: position{line: 40, col: 7, offset: 744},
							expr: &seqExpr{
								pos: position{line: 40, col: 9, offset: 746},
								exprs: []any{
									&notExpr{
										pos: position{line: 40, col: 9, offset: 746},
										expr: &litMatcher{
											pos:        position{line: 40, col: 11, offset: 748},
											val:        ",",
											ignoreCase: false,
											want:       "\",\"",
										},
									},
									&anyMatcher{
										line: 40, col: 16, offset: 753,
									},
								},
							},
						},
					},
				},
			},
			leader:        false,
			leftRecursive: false,
		},
	},
}

func (c *current) onS3(list any) (any, error) { _ = "STUB: not implemented"; return *new(any), nil }

func (p *parser) callonS3() (any, error) { _ = "STUB: not implemented"; return *new(any), nil }

func (c *current) onList2(list, id any) (any, error) {
	_ = "STUB: not implemented"
	return *new(any), nil
}

func (p *parser) callonList2() (any, error) { _ = "STUB: not implemented"; return *new(any), nil }

func (c *current) onList9(id any) (any, error) { _ = "STUB: not implemented"; return *new(any), nil }

func (p *parser) callonList9() (any, error) { _ = "STUB: not implemented"; return *new(any), nil }

func (c *current) onID2() (any, error) { _ = "STUB: not implemented"; return *new(any), nil }

func (p *parser) callonID2() (any, error) { _ = "STUB: not implemented"; return *new(any), nil }

func (c *current) onErrComma2() error { _ = "STUB: not implemented"; return nil }

func (p *parser) callonErrComma2() error { _ = "STUB: not implemented"; return nil }

func (c *current) onErrID3() error { _ = "STUB: not implemented"; return nil }

func (p *parser) callonErrID3() error { _ = "STUB: not implemented"; return nil }

func (c *current) onErrID1() (any, error) { _ = "STUB: not implemented"; return *new(any), nil }

func (p *parser) callonErrID1() (any, error) { _ = "STUB: not implemented"; return *new(any), nil }

var (
	// errNoRule is returned when the grammar to parse has no rule.
	errNoRule = errors.New("grammar has no rule")

	// errInvalidEntrypoint is returned when the specified entrypoint rule
	// does not exit.
	errInvalidEntrypoint = errors.New("invalid entrypoint")

	// errInvalidEncoding is returned when the source is not properly
	// utf8-encoded.
	errInvalidEncoding = errors.New("invalid encoding")

	// errMaxExprCnt is used to signal that the maximum number of
	// expressions have been parsed.
	errMaxExprCnt = errors.New("max number of expressions parsed")
)

// Option is a function that can set an option on the parser. It returns
// the previous setting as an Option.
type Option func(*parser) Option

// MaxExpressions creates an Option to stop parsing after the provided
// number of expressions have been parsed, if the value is 0 then the parser will
// parse for as many steps as needed (possibly an infinite number).
//
// The default for maxExprCnt is 0.
func MaxExpressions(maxExprCnt uint64) Option { _ = "STUB: not implemented"; return *new(Option) }

// Entrypoint creates an Option to set the rule name to use as entrypoint.
// The rule name must have been specified in the -alternate-entrypoints
// if generating the parser with the -optimize-grammar flag, otherwise
// it may have been optimized out. Passing an empty string sets the
// entrypoint to the first rule in the grammar.
//
// The default is to start parsing at the first rule in the grammar.
func Entrypoint(ruleName string) Option { _ = "STUB: not implemented"; return *new(Option) }

// Statistics adds a user provided Stats struct to the parser to allow
// the user to process the results after the parsing has finished.
// Also the key for the "no match" counter is set.
//
// Example usage:
//
//	input := "input"
//	stats := Stats{}
//	_, err := Parse("input-file", []byte(input), Statistics(&stats, "no match"))
//	if err != nil {
//	    log.Panicln(err)
//	}
//	b, err := json.MarshalIndent(stats.ChoiceAltCnt, "", "  ")
//	if err != nil {
//	    log.Panicln(err)
//	}
//	fmt.Println(string(b))
func Statistics(stats *Stats, choiceNoMatch string) Option {
	_ = "STUB: not implemented"
	return *new(Option)
}

// Debug creates an Option to set the debug flag to b. When set to true,
// debugging information is printed to stdout while parsing.
//
// The default is false.
func Debug(b bool) Option { _ = "STUB: not implemented"; return *new(Option) }

// Memoize creates an Option to set the memoize flag to b. When set to true,
// the parser will cache all results so each expression is evaluated only
// once. This guarantees linear parsing time even for pathological cases,
// at the expense of more memory and slower times for typical cases.
//
// The default is false.
func Memoize(b bool) Option { _ = "STUB: not implemented"; return *new(Option) }

// AllowInvalidUTF8 creates an Option to allow invalid UTF-8 bytes.
// Every invalid UTF-8 byte is treated as a utf8.RuneError (U+FFFD)
// by character class matchers and is matched by the any matcher.
// The returned matched value, c.text and c.offset are NOT affected.
//
// The default is false.
func AllowInvalidUTF8(b bool) Option { _ = "STUB: not implemented"; return *new(Option) }

// Recover creates an Option to set the recover flag to b. When set to
// true, this causes the parser to recover from panics and convert it
// to an error. Setting it to false can be useful while debugging to
// access the full stack trace.
//
// The default is true.
func Recover(b bool) Option { _ = "STUB: not implemented"; return *new(Option) }

// GlobalStore creates an Option to set a key to a certain value in
// the globalStore.
func GlobalStore(key string, value any) Option { _ = "STUB: not implemented"; return *new(Option) }

// InitState creates an Option to set a key to a certain value in
// the global "state" store.
func InitState(key string, value any) Option { _ = "STUB: not implemented"; return *new(Option) }

// ParseFile parses the file identified by filename.
func ParseFile(filename string, opts ...Option) (i any, err error) {
	_ = "STUB: not implemented" // nolint: deadcode
	return *new(any), nil
}

// ParseReader parses the data from r using filename as information in the
// error messages.
func ParseReader(filename string, r io.Reader, opts ...Option) (any, error) {
	_ = "STUB: not implemented" // nolint: deadcode
	return *new(any), nil
}

// Parse parses the data from b using filename as information in the
// error messages.
func Parse(filename string, b []byte, opts ...Option) (any, error) {
	_ = "STUB: not implemented"
	return *new(any), nil
}

// position records a position in the text.
type position struct {
	line, col, offset int
}

func (p position) String() string { _ = "STUB: not implemented"; return "" }

// savepoint stores all state required to go back to this point in the
// parser.
type savepoint struct {
	position
	rn rune
	w  int
}

type current struct {
	pos  position // start position of the match
	text []byte   // raw text of the match

	// state is a store for arbitrary key,value pairs that the user wants to be
	// tied to the backtracking of the parser.
	// This is always rolled back if a parsing rule fails.
	state storeDict

	// globalStore is a general store for the user to store arbitrary key-value
	// pairs that they need to manage and that they do not want tied to the
	// backtracking of the parser. This is only modified by the user and never
	// rolled back by the parser. It is always up to the user to keep this in a
	// consistent state.
	globalStore storeDict
}

type storeDict map[string]any

// the AST types...

// nolint: structcheck
type grammar struct {
	pos   position
	rules []*rule
}

// nolint: structcheck
type rule struct {
	pos         position
	name        string
	displayName string
	expr        any

	leader        bool
	leftRecursive bool
}

// nolint: structcheck
type choiceExpr struct {
	pos          position
	alternatives []any
}

// nolint: structcheck
type actionExpr struct {
	pos  position
	expr any
	run  func(*parser) (any, error)
}

// nolint: structcheck
type recoveryExpr struct {
	pos          position
	expr         any
	recoverExpr  any
	failureLabel []string
}

// nolint: structcheck
type seqExpr struct {
	pos   position
	exprs []any
}

// nolint: structcheck
type throwExpr struct {
	pos   position
	label string
}

// nolint: structcheck
type labeledExpr struct {
	pos   position
	label string
	expr  any
}

// nolint: structcheck
type expr struct {
	pos  position
	expr any
}

type (
	andExpr        expr // nolint: structcheck
	notExpr        expr // nolint: structcheck
	zeroOrOneExpr  expr // nolint: structcheck
	zeroOrMoreExpr expr // nolint: structcheck
	oneOrMoreExpr  expr // nolint: structcheck
)

// nolint: structcheck
type ruleRefExpr struct {
	pos  position
	name string
}

// nolint: structcheck
type stateCodeExpr struct {
	pos position
	run func(*parser) error
}

// nolint: structcheck
type andCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

// nolint: structcheck
type notCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

// nolint: structcheck
type litMatcher struct {
	pos        position
	val        string
	ignoreCase bool
	want       string
}

// nolint: structcheck
type charClassMatcher struct {
	pos             position
	val             string
	basicLatinChars [128]bool
	chars           []rune
	ranges          []rune
	classes         []*unicode.RangeTable
	ignoreCase      bool
	inverted        bool
}

type anyMatcher position // nolint: structcheck

// errList cumulates the errors found by the parser.
type errList []error

func (e *errList) add(err error) { _ = "STUB: not implemented"; return }

func (e errList) err() error { _ = "STUB: not implemented"; return nil }

func (e *errList) dedupe() { _ = "STUB: not implemented"; return }

func (e errList) Error() string { _ = "STUB: not implemented"; return "" }

// parserError wraps an error with a prefix indicating the rule in which
// the error occurred. The original error is stored in the Inner field.
type parserError struct {
	Inner    error
	pos      position
	prefix   string
	expected []string
}

// Error returns the error message.
func (p *parserError) Error() string { _ = "STUB: not implemented"; return "" }

// newParser creates a parser with the specified input source and options.
func newParser(filename string, b []byte, opts ...Option) *parser {
	_ = "STUB: not implemented"
	return nil
}

// start rule is rule [0] unless an alternate entrypoint is specified

// setOptions applies the options to the parser.
func (p *parser) setOptions(opts []Option) { _ = "STUB: not implemented"; return }

// nolint: structcheck,deadcode
type resultTuple struct {
	v   any
	b   bool
	end savepoint
}

// nolint: varcheck
const choiceNoMatch = -1

// Stats stores some statistics, gathered during parsing
type Stats struct {
	// ExprCnt counts the number of expressions processed during parsing
	// This value is compared to the maximum number of expressions allowed
	// (set by the MaxExpressions option).
	ExprCnt uint64

	// ChoiceAltCnt is used to count for each ordered choice expression,
	// which alternative is used how may times.
	// These numbers allow to optimize the order of the ordered choice expression
	// to increase the performance of the parser
	//
	// The outer key of ChoiceAltCnt is composed of the name of the rule as well
	// as the line and the column of the ordered choice.
	// The inner key of ChoiceAltCnt is the number (one-based) of the matching alternative.
	// For each alternative the number of matches are counted. If an ordered choice does not
	// match, a special counter is incremented. The name of this counter is set with
	// the parser option Statistics.
	// For an alternative to be included in ChoiceAltCnt, it has to match at least once.
	ChoiceAltCnt map[string]map[string]int
}

type ruleWithExpsStack struct {
	rule   *rule
	estack []any
}

// nolint: structcheck,maligned
type parser struct {
	filename string
	pt       savepoint
	cur      current

	data []byte
	errs *errList

	depth   int
	recover bool
	debug   bool

	memoize bool
	// memoization table for the packrat algorithm:
	// map[offset in source] map[expression or rule] {value, match}
	memo map[int]map[any]resultTuple

	// rules table, maps the rule identifier to the rule node
	rules map[string]*rule
	// variables stack, map of label to value
	vstack []map[string]any
	// rule stack, allows identification of the current rule in errors
	rstack []*rule

	// parse fail
	maxFailPos            position
	maxFailExpected       []string
	maxFailInvertExpected bool

	// max number of expressions to be parsed
	maxExprCnt uint64
	// entrypoint for the parser
	entrypoint string

	allowInvalidUTF8 bool

	*Stats

	choiceNoMatch string
	// recovery expression stack, keeps track of the currently available recovery expression, these are traversed in reverse
	recoveryStack []map[string]any
}

// push a variable set on the vstack.
func (p *parser) pushV() { _ = "STUB: not implemented"; return }

// create new empty slot in the stack

// slice to 1 more

// get the last args set

// empty map, all good

// pop a variable set from the vstack.
func (p *parser) popV() {
	_ = "STUB: not implemented"
	// if the map is not empty, clear it
	return
}

// GC that map

// push a recovery expression with its labels to the recoveryStack
func (p *parser) pushRecovery(labels []string, expr any) { _ = "STUB: not implemented"; return }

// create new empty slot in the stack

// slice to 1 more

// pop a recovery expression from the recoveryStack
func (p *parser) popRecovery() {
	_ = "STUB: not implemented"
	// GC that map
	return
}

func (p *parser) print(prefix, s string) string { _ = "STUB: not implemented"; return "" }

func (p *parser) printIndent(mark string, s string) string { _ = "STUB: not implemented"; return "" }

func (p *parser) in(s string) string { _ = "STUB: not implemented"; return "" }

func (p *parser) out(s string) string { _ = "STUB: not implemented"; return "" }

func (p *parser) addErr(err error) { _ = "STUB: not implemented"; return }

func (p *parser) addErrAt(err error, pos position, expected []string) {
	_ = "STUB: not implemented"
	return
}

func (p *parser) failAt(fail bool, pos position, want string) {
	_ = "STUB: not implemented"
	// process fail if parsing fails and not inverted or parsing succeeds and invert is set
	return
}

// read advances the parser to the next rune.
func (p *parser) read() { _ = "STUB: not implemented"; return }

// see utf8.DecodeRune

// restore parser position to the savepoint pt.
func (p *parser) restore(pt savepoint) { _ = "STUB: not implemented"; return }

// Cloner is implemented by any value that has a Clone method, which returns a
// copy of the value. This is mainly used for types which are not passed by
// value (e.g map, slice, chan) or structs that contain such types.
//
// This is used in conjunction with the global state feature to create proper
// copies of the state to allow the parser to properly restore the state in
// the case of backtracking.
type Cloner interface {
	Clone() any
}

var statePool = &sync.Pool{
	New: func() any { return make(storeDict) },
}

func (sd storeDict) Discard() { _ = "STUB: not implemented"; return }

// clone and return parser current state.
func (p *parser) cloneState() storeDict { _ = "STUB: not implemented"; return *new(storeDict) }

// restore parser current state to the state storeDict.
// every restoreState should applied only one time for every cloned state
func (p *parser) restoreState(state storeDict) { _ = "STUB: not implemented"; return }

// get the slice of bytes from the savepoint start to the current position.
func (p *parser) sliceFrom(start savepoint) []byte { _ = "STUB: not implemented"; return nil }

func (p *parser) getMemoized(node any) (resultTuple, bool) {
	_ = "STUB: not implemented"
	return *new(resultTuple), false
}

func (p *parser) setMemoized(pt savepoint, node any, tuple resultTuple) {
	_ = "STUB: not implemented"
	return
}

func (p *parser) buildRulesTable(g *grammar) { _ = "STUB: not implemented"; return }

// nolint: gocyclo
func (p *parser) parse(g *grammar) (val any, err error) {
	_ = "STUB: not implemented"
	return *new(any), nil
}

// TODO : not super critical but this could be generated

// panic can be used in action code to stop parsing immediately
// and return the panic as an error.

// advance to first rune

// If parsing fails, but no errors have been recorded, the expected values
// for the farthest parser position are returned as error.

func listJoin(list []string, sep string, lastSep string) string {
	_ = "STUB: not implemented"
	return ""
}

func (p *parser) parseRuleRecursiveLeader(rule *rule) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (p *parser) parseRuleRecursiveNoLeader(rule *rule) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (p *parser) parseRuleMemoize(rule *rule) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (p *parser) parseRuleWrap(rule *rule) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (p *parser) parseRule(rule *rule) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (p *parser) parseExprWrap(expr any) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

// nolint: gocyclo
func (p *parser) parseExpr(expr any) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (p *parser) parseActionExpr(act *actionExpr) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (p *parser) parseAndCodeExpr(and *andCodeExpr) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (p *parser) parseAndExpr(and *andExpr) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (p *parser) parseAnyMatcher(any *anyMatcher) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

// EOF - see utf8.DecodeRune

// nolint: gocyclo
func (p *parser) parseCharClassMatcher(chr *charClassMatcher) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

// can't match EOF
// see utf8.DecodeRune

// try to match in the list of available chars

// try to match in the list of ranges

// try to match in the list of Unicode classes

func (p *parser) incChoiceAltCnt(ch *choiceExpr, altI int) { _ = "STUB: not implemented"; return }

// We increment altI by 1, so the keys do not start at 0

func (p *parser) parseChoiceExpr(ch *choiceExpr) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

// dummy assignment to prevent compile error if optimized

func (p *parser) parseLabeledExpr(lab *labeledExpr) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (p *parser) parseLitMatcher(lit *litMatcher) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (p *parser) parseNotCodeExpr(not *notCodeExpr) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (p *parser) parseNotExpr(not *notExpr) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (p *parser) parseOneOrMoreExpr(expr *oneOrMoreExpr) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

// did not match once, no match

func (p *parser) parseRecoveryExpr(recover *recoveryExpr) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (p *parser) parseRuleRefExpr(ref *ruleRefExpr) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (p *parser) parseSeqExpr(seq *seqExpr) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (p *parser) parseStateCodeExpr(state *stateCodeExpr) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (p *parser) parseThrowExpr(expr *throwExpr) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (p *parser) parseZeroOrMoreExpr(expr *zeroOrMoreExpr) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (p *parser) parseZeroOrOneExpr(expr *zeroOrOneExpr) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

// whether it matched or not, consider it a match
