// Code generated by pigeon; DO NOT EDIT.

package thrownrecover

import (
	"errors"
	"io"
	"sync"
	"unicode"
)

var g = &grammar{
	rules: []*rule{
		{
			name: "Start",
			pos:  position{line: 6, col: 1, offset: 28},
			expr: &choiceExpr{
				pos: position{line: 6, col: 9, offset: 36},
				alternatives: []any{
					&ruleRefExpr{
						pos:  position{line: 6, col: 9, offset: 36},
						name: "case01",
					},
					&ruleRefExpr{
						pos:  position{line: 6, col: 18, offset: 45},
						name: "case02",
					},
					&ruleRefExpr{
						pos:  position{line: 6, col: 27, offset: 54},
						name: "case03",
					},
					&ruleRefExpr{
						pos:  position{line: 6, col: 36, offset: 63},
						name: "case04",
					},
				},
			},
		},
		{
			name: "case01",
			pos:  position{line: 11, col: 1, offset: 108},
			expr: &actionExpr{
				pos: position{line: 11, col: 10, offset: 117},
				run: (*parser).calloncase011,
				expr: &seqExpr{
					pos: position{line: 11, col: 10, offset: 117},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 11, col: 10, offset: 117},
							val:        "case01:",
							ignoreCase: false,
							want:       "\"case01:\"",
						},
						&labeledExpr{
							pos:   position{line: 11, col: 20, offset: 127},
							label: "case01",
							expr: &ruleRefExpr{
								pos:  position{line: 11, col: 27, offset: 134},
								name: "MultiLabelRecover",
							},
						},
					},
				},
			},
		},
		{
			name: "MultiLabelRecover",
			pos:  position{line: 13, col: 1, offset: 176},
			expr: &recoveryExpr{
				pos: position{line: 13, col: 21, offset: 196},
				expr: &ruleRefExpr{
					pos:  position{line: 13, col: 21, offset: 196},
					name: "number",
				},
				recoverExpr: &ruleRefExpr{
					pos:  position{line: 13, col: 51, offset: 226},
					name: "ErrNonNumber",
				},
				failureLabel: []string{
					"errAlpha",
					"errOther",
				},
			},
		},
		{
			name: "number",
			pos:  position{line: 15, col: 1, offset: 240},
			expr: &choiceExpr{
				pos: position{line: 15, col: 10, offset: 249},
				alternatives: []any{
					&notExpr{
						pos: position{line: 15, col: 10, offset: 249},
						expr: &anyMatcher{
							line: 15, col: 11, offset: 250,
						},
					},
					&actionExpr{
						pos: position{line: 15, col: 15, offset: 254},
						run: (*parser).callonnumber4,
						expr: &seqExpr{
							pos: position{line: 15, col: 15, offset: 254},
							exprs: []any{
								&labeledExpr{
									pos:   position{line: 15, col: 15, offset: 254},
									label: "d",
									expr: &ruleRefExpr{
										pos:  position{line: 15, col: 17, offset: 256},
										name: "digit",
									},
								},
								&labeledExpr{
									pos:   position{line: 15, col: 23, offset: 262},
									label: "n",
									expr: &ruleRefExpr{
										pos:  position{line: 15, col: 25, offset: 264},
										name: "number",
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "digit",
			pos:  position{line: 22, col: 1, offset: 371},
			expr: &choiceExpr{
				pos: position{line: 22, col: 9, offset: 379},
				alternatives: []any{
					&actionExpr{
						pos: position{line: 22, col: 9, offset: 379},
						run: (*parser).callondigit2,
						expr: &charClassMatcher{
							pos:        position{line: 22, col: 9, offset: 379},
							val:        "[0-9]",
							ranges:     []rune{'0', '9'},
							ignoreCase: false,
							inverted:   false,
						},
					},
					&actionExpr{
						pos: position{line: 22, col: 48, offset: 418},
						run: (*parser).callondigit4,
						expr: &labeledExpr{
							pos:   position{line: 22, col: 48, offset: 418},
							label: "x",
							expr: &seqExpr{
								pos: position{line: 22, col: 52, offset: 422},
								exprs: []any{
									&andExpr{
										pos: position{line: 22, col: 52, offset: 422},
										expr: &charClassMatcher{
											pos:        position{line: 22, col: 53, offset: 423},
											val:        "[a-z]",
											ranges:     []rune{'a', 'z'},
											ignoreCase: false,
											inverted:   false,
										},
									},
									&throwExpr{
										pos:   position{line: 22, col: 59, offset: 429},
										label: "errAlpha",
									},
								},
							},
						},
					},
					&throwExpr{
						pos:   position{line: 22, col: 104, offset: 474},
						label: "errOther",
					},
				},
			},
		},
		{
			name: "ErrNonNumber",
			pos:  position{line: 24, col: 1, offset: 487},
			expr: &actionExpr{
				pos: position{line: 24, col: 16, offset: 502},
				run: (*parser).callonErrNonNumber1,
				expr: &seqExpr{
					pos: position{line: 24, col: 16, offset: 502},
					exprs: []any{
						&andCodeExpr{
							pos: position{line: 24, col: 16, offset: 502},
							run: (*parser).callonErrNonNumber3,
						},
						&zeroOrMoreExpr{
							pos: position{line: 26, col: 3, offset: 557},
							expr: &seqExpr{
								pos: position{line: 26, col: 5, offset: 559},
								exprs: []any{
									&notExpr{
										pos: position{line: 26, col: 5, offset: 559},
										expr: &charClassMatcher{
											pos:        position{line: 26, col: 6, offset: 560},
											val:        "[0-9]",
											ranges:     []rune{'0', '9'},
											ignoreCase: false,
											inverted:   false,
										},
									},
									&anyMatcher{
										line: 26, col: 12, offset: 566,
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "case02",
			pos:  position{line: 31, col: 1, offset: 628},
			expr: &seqExpr{
				pos: position{line: 31, col: 10, offset: 637},
				exprs: []any{
					&litMatcher{
						pos:        position{line: 31, col: 10, offset: 637},
						val:        "case02:",
						ignoreCase: false,
						want:       "\"case02:\"",
					},
					&choiceExpr{
						pos: position{line: 31, col: 21, offset: 648},
						alternatives: []any{
							&ruleRefExpr{
								pos:  position{line: 31, col: 21, offset: 648},
								name: "ThrowUndefLabel",
							},
							&andCodeExpr{
								pos: position{line: 31, col: 39, offset: 666},
								run: (*parser).calloncase025,
							},
						},
					},
				},
			},
		},
		{
			name: "ThrowUndefLabel",
			pos:  position{line: 33, col: 1, offset: 723},
			expr: &throwExpr{
				pos:   position{line: 33, col: 19, offset: 741},
				label: "undeflabel",
			},
		},
		{
			name: "case03",
			pos:  position{line: 38, col: 1, offset: 785},
			expr: &actionExpr{
				pos: position{line: 38, col: 10, offset: 794},
				run: (*parser).calloncase031,
				expr: &seqExpr{
					pos: position{line: 38, col: 10, offset: 794},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 38, col: 10, offset: 794},
							val:        "case03:",
							ignoreCase: false,
							want:       "\"case03:\"",
						},
						&labeledExpr{
							pos:   position{line: 38, col: 20, offset: 804},
							label: "case03",
							expr: &ruleRefExpr{
								pos:  position{line: 38, col: 27, offset: 811},
								name: "OuterRecover03",
							},
						},
					},
				},
			},
		},
		{
			name: "OuterRecover03",
			pos:  position{line: 40, col: 1, offset: 850},
			expr: &recoveryExpr{
				pos: position{line: 40, col: 18, offset: 867},
				expr: &recoveryExpr{
					pos: position{line: 40, col: 18, offset: 867},
					expr: &ruleRefExpr{
						pos:  position{line: 40, col: 18, offset: 867},
						name: "InnerRecover03",
					},
					recoverExpr: &ruleRefExpr{
						pos:  position{line: 40, col: 66, offset: 915},
						name: "ErrAlphaOuter03",
					},
					failureLabel: []string{
						"errAlphaLower",
						"errAlphaUpper",
					},
				},
				recoverExpr: &ruleRefExpr{
					pos:  position{line: 40, col: 95, offset: 944},
					name: "ErrOtherOuter03",
				},
				failureLabel: []string{
					"errOther",
				},
			},
		},
		{
			name: "InnerRecover03",
			pos:  position{line: 42, col: 1, offset: 961},
			expr: &recoveryExpr{
				pos: position{line: 42, col: 18, offset: 978},
				expr: &ruleRefExpr{
					pos:  position{line: 42, col: 18, offset: 978},
					name: "number03",
				},
				recoverExpr: &ruleRefExpr{
					pos:  position{line: 42, col: 45, offset: 1005},
					name: "ErrAlphaInner03",
				},
				failureLabel: []string{
					"errAlphaLower",
				},
			},
		},
		{
			name: "number03",
			pos:  position{line: 44, col: 1, offset: 1022},
			expr: &choiceExpr{
				pos: position{line: 44, col: 12, offset: 1033},
				alternatives: []any{
					&notExpr{
						pos: position{line: 44, col: 12, offset: 1033},
						expr: &anyMatcher{
							line: 44, col: 13, offset: 1034,
						},
					},
					&actionExpr{
						pos: position{line: 44, col: 17, offset: 1038},
						run: (*parser).callonnumber034,
						expr: &seqExpr{
							pos: position{line: 44, col: 17, offset: 1038},
							exprs: []any{
								&labeledExpr{
									pos:   position{line: 44, col: 17, offset: 1038},
									label: "d",
									expr: &ruleRefExpr{
										pos:  position{line: 44, col: 19, offset: 1040},
										name: "digit03",
									},
								},
								&labeledExpr{
									pos:   position{line: 44, col: 27, offset: 1048},
									label: "n",
									expr: &ruleRefExpr{
										pos:  position{line: 44, col: 29, offset: 1050},
										name: "number03",
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "digit03",
			pos:  position{line: 51, col: 1, offset: 1159},
			expr: &choiceExpr{
				pos: position{line: 51, col: 11, offset: 1169},
				alternatives: []any{
					&actionExpr{
						pos: position{line: 51, col: 11, offset: 1169},
						run: (*parser).callondigit032,
						expr: &charClassMatcher{
							pos:        position{line: 51, col: 11, offset: 1169},
							val:        "[0-9]",
							ranges:     []rune{'0', '9'},
							ignoreCase: false,
							inverted:   false,
						},
					},
					&actionExpr{
						pos: position{line: 51, col: 50, offset: 1208},
						run: (*parser).callondigit034,
						expr: &labeledExpr{
							pos:   position{line: 51, col: 50, offset: 1208},
							label: "x",
							expr: &seqExpr{
								pos: position{line: 51, col: 54, offset: 1212},
								exprs: []any{
									&andExpr{
										pos: position{line: 51, col: 54, offset: 1212},
										expr: &charClassMatcher{
											pos:        position{line: 51, col: 55, offset: 1213},
											val:        "[a-z]",
											ranges:     []rune{'a', 'z'},
											ignoreCase: false,
											inverted:   false,
										},
									},
									&throwExpr{
										pos:   position{line: 51, col: 61, offset: 1219},
										label: "errAlphaLower",
									},
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 51, col: 111, offset: 1269},
						run: (*parser).callondigit0310,
						expr: &labeledExpr{
							pos:   position{line: 51, col: 111, offset: 1269},
							label: "x",
							expr: &seqExpr{
								pos: position{line: 51, col: 115, offset: 1273},
								exprs: []any{
									&andExpr{
										pos: position{line: 51, col: 115, offset: 1273},
										expr: &charClassMatcher{
											pos:        position{line: 51, col: 116, offset: 1274},
											val:        "[A-Z]",
											ranges:     []rune{'A', 'Z'},
											ignoreCase: false,
											inverted:   false,
										},
									},
									&throwExpr{
										pos:   position{line: 51, col: 122, offset: 1280},
										label: "errAlphaUpper",
									},
								},
							},
						},
					},
					&throwExpr{
						pos:   position{line: 51, col: 172, offset: 1330},
						label: "errOther",
					},
				},
			},
		},
		{
			name: "ErrAlphaInner03",
			pos:  position{line: 53, col: 1, offset: 1343},
			expr: &actionExpr{
				pos: position{line: 53, col: 19, offset: 1361},
				run: (*parser).callonErrAlphaInner031,
				expr: &seqExpr{
					pos: position{line: 53, col: 19, offset: 1361},
					exprs: []any{
						&andCodeExpr{
							pos: position{line: 53, col: 19, offset: 1361},
							run: (*parser).callonErrAlphaInner033,
						},
						&zeroOrMoreExpr{
							pos: position{line: 55, col: 3, offset: 1437},
							expr: &seqExpr{
								pos: position{line: 55, col: 5, offset: 1439},
								exprs: []any{
									&notExpr{
										pos: position{line: 55, col: 5, offset: 1439},
										expr: &charClassMatcher{
											pos:        position{line: 55, col: 6, offset: 1440},
											val:        "[0-9]",
											ranges:     []rune{'0', '9'},
											ignoreCase: false,
											inverted:   false,
										},
									},
									&anyMatcher{
										line: 55, col: 12, offset: 1446,
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "ErrAlphaOuter03",
			pos:  position{line: 57, col: 1, offset: 1472},
			expr: &actionExpr{
				pos: position{line: 57, col: 19, offset: 1490},
				run: (*parser).callonErrAlphaOuter031,
				expr: &seqExpr{
					pos: position{line: 57, col: 19, offset: 1490},
					exprs: []any{
						&andCodeExpr{
							pos: position{line: 57, col: 19, offset: 1490},
							run: (*parser).callonErrAlphaOuter033,
						},
						&zeroOrMoreExpr{
							pos: position{line: 59, col: 3, offset: 1566},
							expr: &seqExpr{
								pos: position{line: 59, col: 5, offset: 1568},
								exprs: []any{
									&notExpr{
										pos: position{line: 59, col: 5, offset: 1568},
										expr: &charClassMatcher{
											pos:        position{line: 59, col: 6, offset: 1569},
											val:        "[0-9]",
											ranges:     []rune{'0', '9'},
											ignoreCase: false,
											inverted:   false,
										},
									},
									&anyMatcher{
										line: 59, col: 12, offset: 1575,
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "ErrOtherOuter03",
			pos:  position{line: 61, col: 1, offset: 1601},
			expr: &actionExpr{
				pos: position{line: 61, col: 19, offset: 1619},
				run: (*parser).callonErrOtherOuter031,
				expr: &seqExpr{
					pos: position{line: 61, col: 19, offset: 1619},
					exprs: []any{
						&andCodeExpr{
							pos: position{line: 61, col: 19, offset: 1619},
							run: (*parser).callonErrOtherOuter033,
						},
						&zeroOrMoreExpr{
							pos: position{line: 63, col: 3, offset: 1690},
							expr: &seqExpr{
								pos: position{line: 63, col: 5, offset: 1692},
								exprs: []any{
									&notExpr{
										pos: position{line: 63, col: 5, offset: 1692},
										expr: &charClassMatcher{
											pos:        position{line: 63, col: 6, offset: 1693},
											val:        "[0-9]",
											ranges:     []rune{'0', '9'},
											ignoreCase: false,
											inverted:   false,
										},
									},
									&anyMatcher{
										line: 63, col: 12, offset: 1699,
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "case04",
			pos:  position{line: 68, col: 1, offset: 1784},
			expr: &actionExpr{
				pos: position{line: 68, col: 10, offset: 1793},
				run: (*parser).calloncase041,
				expr: &seqExpr{
					pos: position{line: 68, col: 10, offset: 1793},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 68, col: 10, offset: 1793},
							val:        "case04:",
							ignoreCase: false,
							want:       "\"case04:\"",
						},
						&labeledExpr{
							pos:   position{line: 68, col: 20, offset: 1803},
							label: "case04",
							expr: &ruleRefExpr{
								pos:  position{line: 68, col: 27, offset: 1810},
								name: "OuterRecover04",
							},
						},
					},
				},
			},
		},
		{
			name: "OuterRecover04",
			pos:  position{line: 70, col: 1, offset: 1849},
			expr: &recoveryExpr{
				pos: position{line: 70, col: 18, offset: 1866},
				expr: &recoveryExpr{
					pos: position{line: 70, col: 18, offset: 1866},
					expr: &ruleRefExpr{
						pos:  position{line: 70, col: 18, offset: 1866},
						name: "InnerRecover04",
					},
					recoverExpr: &ruleRefExpr{
						pos:  position{line: 70, col: 66, offset: 1914},
						name: "ErrAlphaOuter04",
					},
					failureLabel: []string{
						"errAlphaLower",
						"errAlphaUpper",
					},
				},
				recoverExpr: &ruleRefExpr{
					pos:  position{line: 70, col: 95, offset: 1943},
					name: "ErrOtherOuter04",
				},
				failureLabel: []string{
					"errOther",
				},
			},
		},
		{
			name: "InnerRecover04",
			pos:  position{line: 72, col: 1, offset: 1960},
			expr: &recoveryExpr{
				pos: position{line: 72, col: 18, offset: 1977},
				expr: &ruleRefExpr{
					pos:  position{line: 72, col: 18, offset: 1977},
					name: "number04",
				},
				recoverExpr: &ruleRefExpr{
					pos:  position{line: 72, col: 45, offset: 2004},
					name: "ErrAlphaInner04",
				},
				failureLabel: []string{
					"errAlphaLower",
				},
			},
		},
		{
			name: "number04",
			pos:  position{line: 74, col: 1, offset: 2021},
			expr: &choiceExpr{
				pos: position{line: 74, col: 12, offset: 2032},
				alternatives: []any{
					&notExpr{
						pos: position{line: 74, col: 12, offset: 2032},
						expr: &anyMatcher{
							line: 74, col: 13, offset: 2033,
						},
					},
					&actionExpr{
						pos: position{line: 74, col: 17, offset: 2037},
						run: (*parser).callonnumber044,
						expr: &seqExpr{
							pos: position{line: 74, col: 17, offset: 2037},
							exprs: []any{
								&labeledExpr{
									pos:   position{line: 74, col: 17, offset: 2037},
									label: "d",
									expr: &ruleRefExpr{
										pos:  position{line: 74, col: 19, offset: 2039},
										name: "digit04",
									},
								},
								&labeledExpr{
									pos:   position{line: 74, col: 27, offset: 2047},
									label: "n",
									expr: &ruleRefExpr{
										pos:  position{line: 74, col: 29, offset: 2049},
										name: "number04",
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "digit04",
			pos:  position{line: 81, col: 1, offset: 2158},
			expr: &choiceExpr{
				pos: position{line: 81, col: 11, offset: 2168},
				alternatives: []any{
					&actionExpr{
						pos: position{line: 81, col: 11, offset: 2168},
						run: (*parser).callondigit042,
						expr: &charClassMatcher{
							pos:        position{line: 81, col: 11, offset: 2168},
							val:        "[0-9]",
							ranges:     []rune{'0', '9'},
							ignoreCase: false,
							inverted:   false,
						},
					},
					&actionExpr{
						pos: position{line: 81, col: 50, offset: 2207},
						run: (*parser).callondigit044,
						expr: &labeledExpr{
							pos:   position{line: 81, col: 50, offset: 2207},
							label: "x",
							expr: &seqExpr{
								pos: position{line: 81, col: 54, offset: 2211},
								exprs: []any{
									&andExpr{
										pos: position{line: 81, col: 54, offset: 2211},
										expr: &charClassMatcher{
											pos:        position{line: 81, col: 55, offset: 2212},
											val:        "[a-z]",
											ranges:     []rune{'a', 'z'},
											ignoreCase: false,
											inverted:   false,
										},
									},
									&throwExpr{
										pos:   position{line: 81, col: 61, offset: 2218},
										label: "errAlphaLower",
									},
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 81, col: 111, offset: 2268},
						run: (*parser).callondigit0410,
						expr: &labeledExpr{
							pos:   position{line: 81, col: 111, offset: 2268},
							label: "x",
							expr: &seqExpr{
								pos: position{line: 81, col: 115, offset: 2272},
								exprs: []any{
									&andExpr{
										pos: position{line: 81, col: 115, offset: 2272},
										expr: &charClassMatcher{
											pos:        position{line: 81, col: 116, offset: 2273},
											val:        "[A-Z]",
											ranges:     []rune{'A', 'Z'},
											ignoreCase: false,
											inverted:   false,
										},
									},
									&throwExpr{
										pos:   position{line: 81, col: 122, offset: 2279},
										label: "errAlphaUpper",
									},
								},
							},
						},
					},
					&throwExpr{
						pos:   position{line: 81, col: 172, offset: 2329},
						label: "errOther",
					},
				},
			},
		},
		{
			name: "ErrAlphaInner04",
			pos:  position{line: 83, col: 1, offset: 2342},
			expr: &andCodeExpr{
				pos: position{line: 83, col: 19, offset: 2360},
				run: (*parser).callonErrAlphaInner041,
			},
		},
		{
			name: "ErrAlphaOuter04",
			pos:  position{line: 87, col: 1, offset: 2388},
			expr: &actionExpr{
				pos: position{line: 87, col: 19, offset: 2406},
				run: (*parser).callonErrAlphaOuter041,
				expr: &seqExpr{
					pos: position{line: 87, col: 19, offset: 2406},
					exprs: []any{
						&andCodeExpr{
							pos: position{line: 87, col: 19, offset: 2406},
							run: (*parser).callonErrAlphaOuter043,
						},
						&zeroOrMoreExpr{
							pos: position{line: 89, col: 3, offset: 2473},
							expr: &seqExpr{
								pos: position{line: 89, col: 5, offset: 2475},
								exprs: []any{
									&notExpr{
										pos: position{line: 89, col: 5, offset: 2475},
										expr: &charClassMatcher{
											pos:        position{line: 89, col: 6, offset: 2476},
											val:        "[0-9]",
											ranges:     []rune{'0', '9'},
											ignoreCase: false,
											inverted:   false,
										},
									},
									&anyMatcher{
										line: 89, col: 12, offset: 2482,
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "ErrOtherOuter04",
			pos:  position{line: 91, col: 1, offset: 2508},
			expr: &actionExpr{
				pos: position{line: 91, col: 19, offset: 2526},
				run: (*parser).callonErrOtherOuter041,
				expr: &seqExpr{
					pos: position{line: 91, col: 19, offset: 2526},
					exprs: []any{
						&andCodeExpr{
							pos: position{line: 91, col: 19, offset: 2526},
							run: (*parser).callonErrOtherOuter043,
						},
						&zeroOrMoreExpr{
							pos: position{line: 93, col: 3, offset: 2597},
							expr: &seqExpr{
								pos: position{line: 93, col: 5, offset: 2599},
								exprs: []any{
									&notExpr{
										pos: position{line: 93, col: 5, offset: 2599},
										expr: &charClassMatcher{
											pos:        position{line: 93, col: 6, offset: 2600},
											val:        "[0-9]",
											ranges:     []rune{'0', '9'},
											ignoreCase: false,
											inverted:   false,
										},
									},
									&anyMatcher{
										line: 93, col: 12, offset: 2606,
									},
								},
							},
						},
					},
				},
			},
		},
	},
}

func (c *current) oncase011(case01 any) (any, error) {
	_ = "STUB: not implemented"
	return *new(any), nil
}

func (p *parser) calloncase011() (any, error) { _ = "STUB: not implemented"; return *new(any), nil }

func (c *current) onnumber4(d, n any) (any, error) {
	_ = "STUB: not implemented"
	return *new(any), nil
}

func (p *parser) callonnumber4() (any, error) { _ = "STUB: not implemented"; return *new(any), nil }

func (c *current) ondigit2() (any, error) { _ = "STUB: not implemented"; return *new(any), nil }

func (p *parser) callondigit2() (any, error) { _ = "STUB: not implemented"; return *new(any), nil }

func (c *current) ondigit4(x any) (any, error) { _ = "STUB: not implemented"; return *new(any), nil }

func (p *parser) callondigit4() (any, error) { _ = "STUB: not implemented"; return *new(any), nil }

func (c *current) onErrNonNumber3() (bool, error) { _ = "STUB: not implemented"; return false, nil }

func (p *parser) callonErrNonNumber3() (bool, error) { _ = "STUB: not implemented"; return false, nil }

func (c *current) onErrNonNumber1() (any, error) { _ = "STUB: not implemented"; return *new(any), nil }

func (p *parser) callonErrNonNumber1() (any, error) {
	_ = "STUB: not implemented"
	return *new(any), nil
}

func (c *current) oncase025() (bool, error) { _ = "STUB: not implemented"; return false, nil }

func (p *parser) calloncase025() (bool, error) { _ = "STUB: not implemented"; return false, nil }

func (c *current) oncase031(case03 any) (any, error) {
	_ = "STUB: not implemented"
	return *new(any), nil
}

func (p *parser) calloncase031() (any, error) { _ = "STUB: not implemented"; return *new(any), nil }

func (c *current) onnumber034(d, n any) (any, error) {
	_ = "STUB: not implemented"
	return *new(any), nil
}

func (p *parser) callonnumber034() (any, error) { _ = "STUB: not implemented"; return *new(any), nil }

func (c *current) ondigit032() (any, error) { _ = "STUB: not implemented"; return *new(any), nil }

func (p *parser) callondigit032() (any, error) { _ = "STUB: not implemented"; return *new(any), nil }

func (c *current) ondigit034(x any) (any, error) { _ = "STUB: not implemented"; return *new(any), nil }

func (p *parser) callondigit034() (any, error) { _ = "STUB: not implemented"; return *new(any), nil }

func (c *current) ondigit0310(x any) (any, error) { _ = "STUB: not implemented"; return *new(any), nil }

func (p *parser) callondigit0310() (any, error) { _ = "STUB: not implemented"; return *new(any), nil }

func (c *current) onErrAlphaInner033() (bool, error) { _ = "STUB: not implemented"; return false, nil }

func (p *parser) callonErrAlphaInner033() (bool, error) {
	_ = "STUB: not implemented"
	return false, nil
}

func (c *current) onErrAlphaInner031() (any, error) {
	_ = "STUB: not implemented"
	return *new(any), nil
}

func (p *parser) callonErrAlphaInner031() (any, error) {
	_ = "STUB: not implemented"
	return *new(any), nil
}

func (c *current) onErrAlphaOuter033() (bool, error) { _ = "STUB: not implemented"; return false, nil }

func (p *parser) callonErrAlphaOuter033() (bool, error) {
	_ = "STUB: not implemented"
	return false, nil
}

func (c *current) onErrAlphaOuter031() (any, error) {
	_ = "STUB: not implemented"
	return *new(any), nil
}

func (p *parser) callonErrAlphaOuter031() (any, error) {
	_ = "STUB: not implemented"
	return *new(any), nil
}

func (c *current) onErrOtherOuter033() (bool, error) { _ = "STUB: not implemented"; return false, nil }

func (p *parser) callonErrOtherOuter033() (bool, error) {
	_ = "STUB: not implemented"
	return false, nil
}

func (c *current) onErrOtherOuter031() (any, error) {
	_ = "STUB: not implemented"
	return *new(any), nil
}

func (p *parser) callonErrOtherOuter031() (any, error) {
	_ = "STUB: not implemented"
	return *new(any), nil
}

func (c *current) oncase041(case04 any) (any, error) {
	_ = "STUB: not implemented"
	return *new(any), nil
}

func (p *parser) calloncase041() (any, error) { _ = "STUB: not implemented"; return *new(any), nil }

func (c *current) onnumber044(d, n any) (any, error) {
	_ = "STUB: not implemented"
	return *new(any), nil
}

func (p *parser) callonnumber044() (any, error) { _ = "STUB: not implemented"; return *new(any), nil }

func (c *current) ondigit042() (any, error) { _ = "STUB: not implemented"; return *new(any), nil }

func (p *parser) callondigit042() (any, error) { _ = "STUB: not implemented"; return *new(any), nil }

func (c *current) ondigit044(x any) (any, error) { _ = "STUB: not implemented"; return *new(any), nil }

func (p *parser) callondigit044() (any, error) { _ = "STUB: not implemented"; return *new(any), nil }

func (c *current) ondigit0410(x any) (any, error) { _ = "STUB: not implemented"; return *new(any), nil }

func (p *parser) callondigit0410() (any, error) { _ = "STUB: not implemented"; return *new(any), nil }

func (c *current) onErrAlphaInner041() (bool, error) { _ = "STUB: not implemented"; return false, nil }

func (p *parser) callonErrAlphaInner041() (bool, error) {
	_ = "STUB: not implemented"
	return false, nil
}

func (c *current) onErrAlphaOuter043() (bool, error) { _ = "STUB: not implemented"; return false, nil }

func (p *parser) callonErrAlphaOuter043() (bool, error) {
	_ = "STUB: not implemented"
	return false, nil
}

func (c *current) onErrAlphaOuter041() (any, error) {
	_ = "STUB: not implemented"
	return *new(any), nil
}

func (p *parser) callonErrAlphaOuter041() (any, error) {
	_ = "STUB: not implemented"
	return *new(any), nil
}

func (c *current) onErrOtherOuter043() (bool, error) { _ = "STUB: not implemented"; return false, nil }

func (p *parser) callonErrOtherOuter043() (bool, error) {
	_ = "STUB: not implemented"
	return false, nil
}

func (c *current) onErrOtherOuter041() (any, error) {
	_ = "STUB: not implemented"
	return *new(any), nil
}

func (p *parser) callonErrOtherOuter041() (any, error) {
	_ = "STUB: not implemented"
	return *new(any), nil
}

var (
	// errNoRule is returned when the grammar to parse has no rule.
	errNoRule = errors.New("grammar has no rule")

	// errInvalidEntrypoint is returned when the specified entrypoint rule
	// does not exit.
	errInvalidEntrypoint = errors.New("invalid entrypoint")

	// errInvalidEncoding is returned when the source is not properly
	// utf8-encoded.
	errInvalidEncoding = errors.New("invalid encoding")

	// errMaxExprCnt is used to signal that the maximum number of
	// expressions have been parsed.
	errMaxExprCnt = errors.New("max number of expressions parsed")
)

// Option is a function that can set an option on the parser. It returns
// the previous setting as an Option.
type Option func(*parser) Option

// MaxExpressions creates an Option to stop parsing after the provided
// number of expressions have been parsed, if the value is 0 then the parser will
// parse for as many steps as needed (possibly an infinite number).
//
// The default for maxExprCnt is 0.
func MaxExpressions(maxExprCnt uint64) Option { _ = "STUB: not implemented"; return *new(Option) }

// Entrypoint creates an Option to set the rule name to use as entrypoint.
// The rule name must have been specified in the -alternate-entrypoints
// if generating the parser with the -optimize-grammar flag, otherwise
// it may have been optimized out. Passing an empty string sets the
// entrypoint to the first rule in the grammar.
//
// The default is to start parsing at the first rule in the grammar.
func Entrypoint(ruleName string) Option { _ = "STUB: not implemented"; return *new(Option) }

// Statistics adds a user provided Stats struct to the parser to allow
// the user to process the results after the parsing has finished.
// Also the key for the "no match" counter is set.
//
// Example usage:
//
//	input := "input"
//	stats := Stats{}
//	_, err := Parse("input-file", []byte(input), Statistics(&stats, "no match"))
//	if err != nil {
//	    log.Panicln(err)
//	}
//	b, err := json.MarshalIndent(stats.ChoiceAltCnt, "", "  ")
//	if err != nil {
//	    log.Panicln(err)
//	}
//	fmt.Println(string(b))
func Statistics(stats *Stats, choiceNoMatch string) Option {
	_ = "STUB: not implemented"
	return *new(Option)
}

// Debug creates an Option to set the debug flag to b. When set to true,
// debugging information is printed to stdout while parsing.
//
// The default is false.
func Debug(b bool) Option { _ = "STUB: not implemented"; return *new(Option) }

// Memoize creates an Option to set the memoize flag to b. When set to true,
// the parser will cache all results so each expression is evaluated only
// once. This guarantees linear parsing time even for pathological cases,
// at the expense of more memory and slower times for typical cases.
//
// The default is false.
func Memoize(b bool) Option { _ = "STUB: not implemented"; return *new(Option) }

// AllowInvalidUTF8 creates an Option to allow invalid UTF-8 bytes.
// Every invalid UTF-8 byte is treated as a utf8.RuneError (U+FFFD)
// by character class matchers and is matched by the any matcher.
// The returned matched value, c.text and c.offset are NOT affected.
//
// The default is false.
func AllowInvalidUTF8(b bool) Option { _ = "STUB: not implemented"; return *new(Option) }

// Recover creates an Option to set the recover flag to b. When set to
// true, this causes the parser to recover from panics and convert it
// to an error. Setting it to false can be useful while debugging to
// access the full stack trace.
//
// The default is true.
func Recover(b bool) Option { _ = "STUB: not implemented"; return *new(Option) }

// GlobalStore creates an Option to set a key to a certain value in
// the globalStore.
func GlobalStore(key string, value any) Option { _ = "STUB: not implemented"; return *new(Option) }

// InitState creates an Option to set a key to a certain value in
// the global "state" store.
func InitState(key string, value any) Option { _ = "STUB: not implemented"; return *new(Option) }

// ParseFile parses the file identified by filename.
func ParseFile(filename string, opts ...Option) (i any, err error) {
	_ = "STUB: not implemented" // nolint: deadcode
	return *new(any), nil
}

// ParseReader parses the data from r using filename as information in the
// error messages.
func ParseReader(filename string, r io.Reader, opts ...Option) (any, error) {
	_ = "STUB: not implemented" // nolint: deadcode
	return *new(any), nil
}

// Parse parses the data from b using filename as information in the
// error messages.
func Parse(filename string, b []byte, opts ...Option) (any, error) {
	_ = "STUB: not implemented"
	return *new(any), nil
}

// position records a position in the text.
type position struct {
	line, col, offset int
}

func (p position) String() string { _ = "STUB: not implemented"; return "" }

// savepoint stores all state required to go back to this point in the
// parser.
type savepoint struct {
	position
	rn rune
	w  int
}

type current struct {
	pos  position // start position of the match
	text []byte   // raw text of the match

	// state is a store for arbitrary key,value pairs that the user wants to be
	// tied to the backtracking of the parser.
	// This is always rolled back if a parsing rule fails.
	state storeDict

	// globalStore is a general store for the user to store arbitrary key-value
	// pairs that they need to manage and that they do not want tied to the
	// backtracking of the parser. This is only modified by the user and never
	// rolled back by the parser. It is always up to the user to keep this in a
	// consistent state.
	globalStore storeDict
}

type storeDict map[string]any

// the AST types...

// nolint: structcheck
type grammar struct {
	pos   position
	rules []*rule
}

// nolint: structcheck
type rule struct {
	pos         position
	name        string
	displayName string
	expr        any
}

// nolint: structcheck
type choiceExpr struct {
	pos          position
	alternatives []any
}

// nolint: structcheck
type actionExpr struct {
	pos  position
	expr any
	run  func(*parser) (any, error)
}

// nolint: structcheck
type recoveryExpr struct {
	pos          position
	expr         any
	recoverExpr  any
	failureLabel []string
}

// nolint: structcheck
type seqExpr struct {
	pos   position
	exprs []any
}

// nolint: structcheck
type throwExpr struct {
	pos   position
	label string
}

// nolint: structcheck
type labeledExpr struct {
	pos   position
	label string
	expr  any
}

// nolint: structcheck
type expr struct {
	pos  position
	expr any
}

type (
	andExpr        expr // nolint: structcheck
	notExpr        expr // nolint: structcheck
	zeroOrOneExpr  expr // nolint: structcheck
	zeroOrMoreExpr expr // nolint: structcheck
	oneOrMoreExpr  expr // nolint: structcheck
)

// nolint: structcheck
type ruleRefExpr struct {
	pos  position
	name string
}

// nolint: structcheck
type stateCodeExpr struct {
	pos position
	run func(*parser) error
}

// nolint: structcheck
type andCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

// nolint: structcheck
type notCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

// nolint: structcheck
type litMatcher struct {
	pos        position
	val        string
	ignoreCase bool
	want       string
}

// nolint: structcheck
type charClassMatcher struct {
	pos             position
	val             string
	basicLatinChars [128]bool
	chars           []rune
	ranges          []rune
	classes         []*unicode.RangeTable
	ignoreCase      bool
	inverted        bool
}

type anyMatcher position // nolint: structcheck

// errList cumulates the errors found by the parser.
type errList []error

func (e *errList) add(err error) { _ = "STUB: not implemented"; return }

func (e errList) err() error { _ = "STUB: not implemented"; return nil }

func (e *errList) dedupe() { _ = "STUB: not implemented"; return }

func (e errList) Error() string { _ = "STUB: not implemented"; return "" }

// parserError wraps an error with a prefix indicating the rule in which
// the error occurred. The original error is stored in the Inner field.
type parserError struct {
	Inner    error
	pos      position
	prefix   string
	expected []string
}

// Error returns the error message.
func (p *parserError) Error() string { _ = "STUB: not implemented"; return "" }

// newParser creates a parser with the specified input source and options.
func newParser(filename string, b []byte, opts ...Option) *parser {
	_ = "STUB: not implemented"
	return nil
}

// start rule is rule [0] unless an alternate entrypoint is specified

// setOptions applies the options to the parser.
func (p *parser) setOptions(opts []Option) { _ = "STUB: not implemented"; return }

// nolint: structcheck,deadcode
type resultTuple struct {
	v   any
	b   bool
	end savepoint
}

// nolint: varcheck
const choiceNoMatch = -1

// Stats stores some statistics, gathered during parsing
type Stats struct {
	// ExprCnt counts the number of expressions processed during parsing
	// This value is compared to the maximum number of expressions allowed
	// (set by the MaxExpressions option).
	ExprCnt uint64

	// ChoiceAltCnt is used to count for each ordered choice expression,
	// which alternative is used how may times.
	// These numbers allow to optimize the order of the ordered choice expression
	// to increase the performance of the parser
	//
	// The outer key of ChoiceAltCnt is composed of the name of the rule as well
	// as the line and the column of the ordered choice.
	// The inner key of ChoiceAltCnt is the number (one-based) of the matching alternative.
	// For each alternative the number of matches are counted. If an ordered choice does not
	// match, a special counter is incremented. The name of this counter is set with
	// the parser option Statistics.
	// For an alternative to be included in ChoiceAltCnt, it has to match at least once.
	ChoiceAltCnt map[string]map[string]int
}

// nolint: structcheck,maligned
type parser struct {
	filename string
	pt       savepoint
	cur      current

	data []byte
	errs *errList

	depth   int
	recover bool
	debug   bool

	memoize bool
	// memoization table for the packrat algorithm:
	// map[offset in source] map[expression or rule] {value, match}
	memo map[int]map[any]resultTuple

	// rules table, maps the rule identifier to the rule node
	rules map[string]*rule
	// variables stack, map of label to value
	vstack []map[string]any
	// rule stack, allows identification of the current rule in errors
	rstack []*rule

	// parse fail
	maxFailPos            position
	maxFailExpected       []string
	maxFailInvertExpected bool

	// max number of expressions to be parsed
	maxExprCnt uint64
	// entrypoint for the parser
	entrypoint string

	allowInvalidUTF8 bool

	*Stats

	choiceNoMatch string
	// recovery expression stack, keeps track of the currently available recovery expression, these are traversed in reverse
	recoveryStack []map[string]any
}

// push a variable set on the vstack.
func (p *parser) pushV() { _ = "STUB: not implemented"; return }

// create new empty slot in the stack

// slice to 1 more

// get the last args set

// empty map, all good

// pop a variable set from the vstack.
func (p *parser) popV() {
	_ = "STUB: not implemented"
	// if the map is not empty, clear it
	return
}

// GC that map

// push a recovery expression with its labels to the recoveryStack
func (p *parser) pushRecovery(labels []string, expr any) { _ = "STUB: not implemented"; return }

// create new empty slot in the stack

// slice to 1 more

// pop a recovery expression from the recoveryStack
func (p *parser) popRecovery() {
	_ = "STUB: not implemented"
	// GC that map
	return
}

func (p *parser) print(prefix, s string) string { _ = "STUB: not implemented"; return "" }

func (p *parser) printIndent(mark string, s string) string { _ = "STUB: not implemented"; return "" }

func (p *parser) in(s string) string { _ = "STUB: not implemented"; return "" }

func (p *parser) out(s string) string { _ = "STUB: not implemented"; return "" }

func (p *parser) addErr(err error) { _ = "STUB: not implemented"; return }

func (p *parser) addErrAt(err error, pos position, expected []string) {
	_ = "STUB: not implemented"
	return
}

func (p *parser) failAt(fail bool, pos position, want string) {
	_ = "STUB: not implemented"
	// process fail if parsing fails and not inverted or parsing succeeds and invert is set
	return
}

// read advances the parser to the next rune.
func (p *parser) read() { _ = "STUB: not implemented"; return }

// see utf8.DecodeRune

// restore parser position to the savepoint pt.
func (p *parser) restore(pt savepoint) { _ = "STUB: not implemented"; return }

// Cloner is implemented by any value that has a Clone method, which returns a
// copy of the value. This is mainly used for types which are not passed by
// value (e.g map, slice, chan) or structs that contain such types.
//
// This is used in conjunction with the global state feature to create proper
// copies of the state to allow the parser to properly restore the state in
// the case of backtracking.
type Cloner interface {
	Clone() any
}

var statePool = &sync.Pool{
	New: func() any { return make(storeDict) },
}

func (sd storeDict) Discard() { _ = "STUB: not implemented"; return }

// clone and return parser current state.
func (p *parser) cloneState() storeDict { _ = "STUB: not implemented"; return *new(storeDict) }

// restore parser current state to the state storeDict.
// every restoreState should applied only one time for every cloned state
func (p *parser) restoreState(state storeDict) { _ = "STUB: not implemented"; return }

// get the slice of bytes from the savepoint start to the current position.
func (p *parser) sliceFrom(start savepoint) []byte { _ = "STUB: not implemented"; return nil }

func (p *parser) getMemoized(node any) (resultTuple, bool) {
	_ = "STUB: not implemented"
	return *new(resultTuple), false
}

func (p *parser) setMemoized(pt savepoint, node any, tuple resultTuple) {
	_ = "STUB: not implemented"
	return
}

func (p *parser) buildRulesTable(g *grammar) { _ = "STUB: not implemented"; return }

// nolint: gocyclo
func (p *parser) parse(g *grammar) (val any, err error) {
	_ = "STUB: not implemented"
	return *new(any), nil
}

// TODO : not super critical but this could be generated

// panic can be used in action code to stop parsing immediately
// and return the panic as an error.

// advance to first rune

// If parsing fails, but no errors have been recorded, the expected values
// for the farthest parser position are returned as error.

func listJoin(list []string, sep string, lastSep string) string {
	_ = "STUB: not implemented"
	return ""
}

func (p *parser) parseRuleMemoize(rule *rule) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (p *parser) parseRuleWrap(rule *rule) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (p *parser) parseRule(rule *rule) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (p *parser) parseExprWrap(expr any) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

// nolint: gocyclo
func (p *parser) parseExpr(expr any) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (p *parser) parseActionExpr(act *actionExpr) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (p *parser) parseAndCodeExpr(and *andCodeExpr) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (p *parser) parseAndExpr(and *andExpr) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (p *parser) parseAnyMatcher(any *anyMatcher) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

// EOF - see utf8.DecodeRune

// nolint: gocyclo
func (p *parser) parseCharClassMatcher(chr *charClassMatcher) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

// can't match EOF
// see utf8.DecodeRune

// try to match in the list of available chars

// try to match in the list of ranges

// try to match in the list of Unicode classes

func (p *parser) incChoiceAltCnt(ch *choiceExpr, altI int) { _ = "STUB: not implemented"; return }

// We increment altI by 1, so the keys do not start at 0

func (p *parser) parseChoiceExpr(ch *choiceExpr) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

// dummy assignment to prevent compile error if optimized

func (p *parser) parseLabeledExpr(lab *labeledExpr) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (p *parser) parseLitMatcher(lit *litMatcher) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (p *parser) parseNotCodeExpr(not *notCodeExpr) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (p *parser) parseNotExpr(not *notExpr) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (p *parser) parseOneOrMoreExpr(expr *oneOrMoreExpr) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

// did not match once, no match

func (p *parser) parseRecoveryExpr(recover *recoveryExpr) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (p *parser) parseRuleRefExpr(ref *ruleRefExpr) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (p *parser) parseSeqExpr(seq *seqExpr) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (p *parser) parseStateCodeExpr(state *stateCodeExpr) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (p *parser) parseThrowExpr(expr *throwExpr) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (p *parser) parseZeroOrMoreExpr(expr *zeroOrMoreExpr) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (p *parser) parseZeroOrOneExpr(expr *zeroOrOneExpr) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

// whether it matched or not, consider it a match
