// Code generated by pigeon; DO NOT EDIT.

package main

import (
	"errors"
	"io"
	"sync"
	"unicode"
)

func toAnySlice(v any) []any { _ = "STUB: not implemented"; return nil }

var g = &grammar{
	rules: []*rule{
		{
			name: "Input",
			pos:  position{line: 13, col: 1, offset: 117},
			expr: &actionExpr{
				pos: position{line: 13, col: 15, offset: 133},
				run: (*parser).callonInput1,
				expr: &seqExpr{
					pos: position{line: 13, col: 15, offset: 133},
					exprs: []any{
						&stateCodeExpr{
							pos: position{line: 13, col: 15, offset: 133},
							run: (*parser).callonInput3,
						},
						&labeledExpr{
							pos:   position{line: 13, col: 59, offset: 177},
							label: "s",
							expr: &ruleRefExpr{
								pos:  position{line: 13, col: 61, offset: 179},
								name: "Statements",
							},
						},
						&labeledExpr{
							pos:   position{line: 13, col: 73, offset: 191},
							label: "r",
							expr: &ruleRefExpr{
								pos:  position{line: 13, col: 75, offset: 193},
								name: "ReturnOp",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 13, col: 84, offset: 202},
							name: "EOF",
						},
					},
				},
			},
		},
		{
			name: "Statements",
			pos:  position{line: 15, col: 1, offset: 312},
			expr: &actionExpr{
				pos: position{line: 15, col: 15, offset: 328},
				run: (*parser).callonStatements1,
				expr: &labeledExpr{
					pos:   position{line: 15, col: 15, offset: 328},
					label: "s",
					expr: &oneOrMoreExpr{
						pos: position{line: 15, col: 17, offset: 330},
						expr: &ruleRefExpr{
							pos:  position{line: 15, col: 17, offset: 330},
							name: "Line",
						},
					},
				},
			},
		},
		{
			name: "Line",
			pos:  position{line: 16, col: 1, offset: 389},
			expr: &actionExpr{
				pos: position{line: 16, col: 15, offset: 405},
				run: (*parser).callonLine1,
				expr: &seqExpr{
					pos: position{line: 16, col: 15, offset: 405},
					exprs: []any{
						&ruleRefExpr{
							pos:  position{line: 16, col: 15, offset: 405},
							name: "INDENTATION",
						},
						&labeledExpr{
							pos:   position{line: 16, col: 27, offset: 417},
							label: "s",
							expr: &ruleRefExpr{
								pos:  position{line: 16, col: 29, offset: 419},
								name: "Statement",
							},
						},
					},
				},
			},
		},
		{
			name: "ReturnOp",
			pos:  position{line: 17, col: 1, offset: 452},
			expr: &actionExpr{
				pos: position{line: 17, col: 15, offset: 468},
				run: (*parser).callonReturnOp1,
				expr: &seqExpr{
					pos: position{line: 17, col: 15, offset: 468},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 17, col: 15, offset: 468},
							val:        "return",
							ignoreCase: false,
							want:       "\"return\"",
						},
						&ruleRefExpr{
							pos:  position{line: 17, col: 24, offset: 477},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 17, col: 26, offset: 479},
							label: "arg",
							expr: &ruleRefExpr{
								pos:  position{line: 17, col: 30, offset: 483},
								name: "Identifier",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 17, col: 41, offset: 494},
							name: "EOL",
						},
					},
				},
			},
		},
		{
			name: "Statement",
			pos:  position{line: 19, col: 1, offset: 545},
			expr: &choiceExpr{
				pos: position{line: 19, col: 15, offset: 561},
				alternatives: []any{
					&actionExpr{
						pos: position{line: 19, col: 15, offset: 561},
						run: (*parser).callonStatement2,
						expr: &seqExpr{
							pos: position{line: 19, col: 15, offset: 561},
							exprs: []any{
								&labeledExpr{
									pos:   position{line: 19, col: 15, offset: 561},
									label: "s",
									expr: &ruleRefExpr{
										pos:  position{line: 19, col: 17, offset: 563},
										name: "Assignment",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 19, col: 28, offset: 574},
									name: "EOL",
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 20, col: 7, offset: 631},
						run: (*parser).callonStatement7,
						expr: &seqExpr{
							pos: position{line: 20, col: 7, offset: 631},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 20, col: 7, offset: 631},
									val:        "if",
									ignoreCase: false,
									want:       "\"if\"",
								},
								&ruleRefExpr{
									pos:  position{line: 20, col: 12, offset: 636},
									name: "_",
								},
								&labeledExpr{
									pos:   position{line: 20, col: 14, offset: 638},
									label: "arg",
									expr: &ruleRefExpr{
										pos:  position{line: 20, col: 18, offset: 642},
										name: "LogicalExpression",
									},
								},
								&zeroOrOneExpr{
									pos: position{line: 20, col: 36, offset: 660},
									expr: &ruleRefExpr{
										pos:  position{line: 20, col: 36, offset: 660},
										name: "_",
									},
								},
								&litMatcher{
									pos:        position{line: 20, col: 39, offset: 663},
									val:        ":",
									ignoreCase: false,
									want:       "\":\"",
								},
								&ruleRefExpr{
									pos:  position{line: 20, col: 43, offset: 667},
									name: "EOL",
								},
								&ruleRefExpr{
									pos:  position{line: 20, col: 47, offset: 671},
									name: "INDENT",
								},
								&labeledExpr{
									pos:   position{line: 20, col: 54, offset: 678},
									label: "s",
									expr: &ruleRefExpr{
										pos:  position{line: 20, col: 56, offset: 680},
										name: "Statements",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 20, col: 67, offset: 691},
									name: "DEDENT",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Assignment",
			pos:  position{line: 24, col: 1, offset: 818},
			expr: &actionExpr{
				pos: position{line: 24, col: 14, offset: 833},
				run: (*parser).callonAssignment1,
				expr: &seqExpr{
					pos: position{line: 24, col: 14, offset: 833},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 24, col: 14, offset: 833},
							label: "lvalue",
							expr: &ruleRefExpr{
								pos:  position{line: 24, col: 21, offset: 840},
								name: "Identifier",
							},
						},
						&zeroOrOneExpr{
							pos: position{line: 24, col: 32, offset: 851},
							expr: &ruleRefExpr{
								pos:  position{line: 24, col: 32, offset: 851},
								name: "_",
							},
						},
						&litMatcher{
							pos:        position{line: 24, col: 35, offset: 854},
							val:        "=",
							ignoreCase: false,
							want:       "\"=\"",
						},
						&zeroOrOneExpr{
							pos: position{line: 24, col: 39, offset: 858},
							expr: &ruleRefExpr{
								pos:  position{line: 24, col: 39, offset: 858},
								name: "_",
							},
						},
						&labeledExpr{
							pos:   position{line: 24, col: 42, offset: 861},
							label: "rvalue",
							expr: &ruleRefExpr{
								pos:  position{line: 24, col: 49, offset: 868},
								name: "AdditiveExpression",
							},
						},
					},
				},
			},
		},
		{
			name: "LogicalExpression",
			pos:  position{line: 27, col: 1, offset: 1018},
			expr: &actionExpr{
				pos: position{line: 27, col: 23, offset: 1042},
				run: (*parser).callonLogicalExpression1,
				expr: &labeledExpr{
					pos:   position{line: 27, col: 23, offset: 1042},
					label: "arg",
					expr: &ruleRefExpr{
						pos:  position{line: 27, col: 27, offset: 1046},
						name: "PrimaryExpression",
					},
				},
			},
		},
		{
			name: "AdditiveExpression",
			pos:  position{line: 28, col: 1, offset: 1129},
			expr: &actionExpr{
				pos: position{line: 28, col: 23, offset: 1153},
				run: (*parser).callonAdditiveExpression1,
				expr: &seqExpr{
					pos: position{line: 28, col: 23, offset: 1153},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 28, col: 23, offset: 1153},
							label: "arg",
							expr: &ruleRefExpr{
								pos:  position{line: 28, col: 27, offset: 1157},
								name: "PrimaryExpression",
							},
						},
						&labeledExpr{
							pos:   position{line: 28, col: 45, offset: 1175},
							label: "rest",
							expr: &zeroOrMoreExpr{
								pos: position{line: 28, col: 50, offset: 1180},
								expr: &seqExpr{
									pos: position{line: 28, col: 52, offset: 1182},
									exprs: []any{
										&ruleRefExpr{
											pos:  position{line: 28, col: 52, offset: 1182},
											name: "_",
										},
										&ruleRefExpr{
											pos:  position{line: 28, col: 54, offset: 1184},
											name: "AddOp",
										},
										&ruleRefExpr{
											pos:  position{line: 28, col: 60, offset: 1190},
											name: "_",
										},
										&ruleRefExpr{
											pos:  position{line: 28, col: 62, offset: 1192},
											name: "PrimaryExpression",
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "PrimaryExpression",
			pos:  position{line: 30, col: 1, offset: 1328},
			expr: &actionExpr{
				pos: position{line: 30, col: 23, offset: 1352},
				run: (*parser).callonPrimaryExpression1,
				expr: &labeledExpr{
					pos:   position{line: 30, col: 23, offset: 1352},
					label: "arg",
					expr: &choiceExpr{
						pos: position{line: 30, col: 28, offset: 1357},
						alternatives: []any{
							&ruleRefExpr{
								pos:  position{line: 30, col: 28, offset: 1357},
								name: "Integer",
							},
							&ruleRefExpr{
								pos:  position{line: 30, col: 38, offset: 1367},
								name: "Identifier",
							},
						},
					},
				},
			},
		},
		{
			name: "Integer",
			pos:  position{line: 33, col: 1, offset: 1466},
			expr: &actionExpr{
				pos: position{line: 33, col: 11, offset: 1478},
				run: (*parser).callonInteger1,
				expr: &oneOrMoreExpr{
					pos: position{line: 33, col: 11, offset: 1478},
					expr: &charClassMatcher{
						pos:        position{line: 33, col: 11, offset: 1478},
						val:        "[0-9]",
						ranges:     []rune{'0', '9'},
						ignoreCase: false,
						inverted:   false,
					},
				},
			},
		},
		{
			name: "Identifier",
			pos:  position{line: 34, col: 1, offset: 1554},
			expr: &actionExpr{
				pos: position{line: 34, col: 14, offset: 1569},
				run: (*parser).callonIdentifier1,
				expr: &seqExpr{
					pos: position{line: 34, col: 14, offset: 1569},
					exprs: []any{
						&charClassMatcher{
							pos:        position{line: 34, col: 14, offset: 1569},
							val:        "[a-zA-Z]",
							ranges:     []rune{'a', 'z', 'A', 'Z'},
							ignoreCase: false,
							inverted:   false,
						},
						&zeroOrMoreExpr{
							pos: position{line: 34, col: 23, offset: 1578},
							expr: &charClassMatcher{
								pos:        position{line: 34, col: 23, offset: 1578},
								val:        "[a-zA-Z0-9]",
								ranges:     []rune{'a', 'z', 'A', 'Z', '0', '9'},
								ignoreCase: false,
								inverted:   false,
							},
						},
					},
				},
			},
		},
		{
			name: "AddOp",
			pos:  position{line: 36, col: 1, offset: 1646},
			expr: &actionExpr{
				pos: position{line: 36, col: 9, offset: 1656},
				run: (*parser).callonAddOp1,
				expr: &choiceExpr{
					pos: position{line: 36, col: 11, offset: 1658},
					alternatives: []any{
						&litMatcher{
							pos:        position{line: 36, col: 11, offset: 1658},
							val:        "+",
							ignoreCase: false,
							want:       "\"+\"",
						},
						&litMatcher{
							pos:        position{line: 36, col: 17, offset: 1664},
							val:        "-",
							ignoreCase: false,
							want:       "\"-\"",
						},
					},
				},
			},
		},
		{
			name: "_",
			pos:  position{line: 38, col: 1, offset: 1723},
			expr: &oneOrMoreExpr{
				pos: position{line: 38, col: 5, offset: 1729},
				expr: &charClassMatcher{
					pos:        position{line: 38, col: 5, offset: 1729},
					val:        "[ \\t]",
					chars:      []rune{' ', '\t'},
					ignoreCase: false,
					inverted:   false,
				},
			},
		},
		{
			name: "EOL",
			pos:  position{line: 40, col: 1, offset: 1737},
			expr: &seqExpr{
				pos: position{line: 40, col: 7, offset: 1745},
				exprs: []any{
					&zeroOrOneExpr{
						pos: position{line: 40, col: 7, offset: 1745},
						expr: &ruleRefExpr{
							pos:  position{line: 40, col: 7, offset: 1745},
							name: "_",
						},
					},
					&zeroOrOneExpr{
						pos: position{line: 40, col: 10, offset: 1748},
						expr: &ruleRefExpr{
							pos:  position{line: 40, col: 10, offset: 1748},
							name: "Comment",
						},
					},
					&choiceExpr{
						pos: position{line: 40, col: 20, offset: 1758},
						alternatives: []any{
							&litMatcher{
								pos:        position{line: 40, col: 20, offset: 1758},
								val:        "\r\n",
								ignoreCase: false,
								want:       "\"\\r\\n\"",
							},
							&litMatcher{
								pos:        position{line: 40, col: 29, offset: 1767},
								val:        "\n\r",
								ignoreCase: false,
								want:       "\"\\n\\r\"",
							},
							&litMatcher{
								pos:        position{line: 40, col: 38, offset: 1776},
								val:        "\r",
								ignoreCase: false,
								want:       "\"\\r\"",
							},
							&litMatcher{
								pos:        position{line: 40, col: 45, offset: 1783},
								val:        "\n",
								ignoreCase: false,
								want:       "\"\\n\"",
							},
							&ruleRefExpr{
								pos:  position{line: 40, col: 52, offset: 1790},
								name: "EOF",
							},
						},
					},
				},
			},
		},
		{
			name: "Comment",
			pos:  position{line: 42, col: 1, offset: 1796},
			expr: &seqExpr{
				pos: position{line: 42, col: 11, offset: 1808},
				exprs: []any{
					&litMatcher{
						pos:        position{line: 42, col: 11, offset: 1808},
						val:        "//",
						ignoreCase: false,
						want:       "\"//\"",
					},
					&zeroOrMoreExpr{
						pos: position{line: 42, col: 16, offset: 1813},
						expr: &charClassMatcher{
							pos:        position{line: 42, col: 16, offset: 1813},
							val:        "[^\\r\\n]",
							chars:      []rune{'\r', '\n'},
							ignoreCase: false,
							inverted:   true,
						},
					},
				},
			},
		},
		{
			name: "EOF",
			pos:  position{line: 44, col: 1, offset: 1823},
			expr: &notExpr{
				pos: position{line: 44, col: 7, offset: 1831},
				expr: &anyMatcher{
					line: 44, col: 8, offset: 1832,
				},
			},
		},
		{
			name: "INDENTATION",
			pos:  position{line: 46, col: 1, offset: 1835},
			expr: &seqExpr{
				pos: position{line: 46, col: 15, offset: 1851},
				exprs: []any{
					&labeledExpr{
						pos:   position{line: 46, col: 15, offset: 1851},
						label: "spaces",
						expr: &zeroOrMoreExpr{
							pos: position{line: 46, col: 22, offset: 1858},
							expr: &litMatcher{
								pos:        position{line: 46, col: 22, offset: 1858},
								val:        " ",
								ignoreCase: false,
								want:       "\" \"",
							},
						},
					},
					&andCodeExpr{
						pos: position{line: 46, col: 27, offset: 1863},
						run: (*parser).callonINDENTATION5,
					},
				},
			},
		},
		{
			name: "INDENT",
			pos:  position{line: 48, col: 1, offset: 1937},
			expr: &stateCodeExpr{
				pos: position{line: 48, col: 10, offset: 1948},
				run: (*parser).callonINDENT1,
			},
		},
		{
			name: "DEDENT",
			pos:  position{line: 50, col: 1, offset: 2024},
			expr: &stateCodeExpr{
				pos: position{line: 50, col: 10, offset: 2035},
				run: (*parser).callonDEDENT1,
			},
		},
	},
}

func (c *current) onInput3() error { _ = "STUB: not implemented"; return nil }

func (p *parser) callonInput3() error { _ = "STUB: not implemented"; return nil }

func (c *current) onInput1(s, r any) (any, error) { _ = "STUB: not implemented"; return *new(any), nil }

func (p *parser) callonInput1() (any, error) { _ = "STUB: not implemented"; return *new(any), nil }

func (c *current) onStatements1(s any) (any, error) {
	_ = "STUB: not implemented"
	return *new(any), nil
}

func (p *parser) callonStatements1() (any, error) { _ = "STUB: not implemented"; return *new(any), nil }

func (c *current) onLine1(s any) (any, error) { _ = "STUB: not implemented"; return *new(any), nil }

func (p *parser) callonLine1() (any, error) { _ = "STUB: not implemented"; return *new(any), nil }

func (c *current) onReturnOp1(arg any) (any, error) {
	_ = "STUB: not implemented"
	return *new(any), nil
}

func (p *parser) callonReturnOp1() (any, error) { _ = "STUB: not implemented"; return *new(any), nil }

func (c *current) onStatement2(s any) (any, error) {
	_ = "STUB: not implemented"
	return *new(any), nil
}

func (p *parser) callonStatement2() (any, error) { _ = "STUB: not implemented"; return *new(any), nil }

func (c *current) onStatement7(arg, s any) (any, error) {
	_ = "STUB: not implemented"
	return *new(any), nil
}

func (p *parser) callonStatement7() (any, error) { _ = "STUB: not implemented"; return *new(any), nil }

func (c *current) onAssignment1(lvalue, rvalue any) (any, error) {
	_ = "STUB: not implemented"
	return *new(any), nil
}

func (p *parser) callonAssignment1() (any, error) { _ = "STUB: not implemented"; return *new(any), nil }

func (c *current) onLogicalExpression1(arg any) (any, error) {
	_ = "STUB: not implemented"
	return *new(any), nil
}

func (p *parser) callonLogicalExpression1() (any, error) {
	_ = "STUB: not implemented"
	return *new(any), nil
}

func (c *current) onAdditiveExpression1(arg, rest any) (any, error) {
	_ = "STUB: not implemented"
	return *new(any), nil
}

func (p *parser) callonAdditiveExpression1() (any, error) {
	_ = "STUB: not implemented"
	return *new(any), nil
}

func (c *current) onPrimaryExpression1(arg any) (any, error) {
	_ = "STUB: not implemented"
	return *new(any), nil
}

func (p *parser) callonPrimaryExpression1() (any, error) {
	_ = "STUB: not implemented"
	return *new(any), nil
}

func (c *current) onInteger1() (any, error) { _ = "STUB: not implemented"; return *new(any), nil }

func (p *parser) callonInteger1() (any, error) { _ = "STUB: not implemented"; return *new(any), nil }

func (c *current) onIdentifier1() (any, error) { _ = "STUB: not implemented"; return *new(any), nil }

func (p *parser) callonIdentifier1() (any, error) { _ = "STUB: not implemented"; return *new(any), nil }

func (c *current) onAddOp1() (any, error) { _ = "STUB: not implemented"; return *new(any), nil }

func (p *parser) callonAddOp1() (any, error) { _ = "STUB: not implemented"; return *new(any), nil }

func (c *current) onINDENTATION5(spaces any) (bool, error) {
	_ = "STUB: not implemented"
	return false, nil
}

func (p *parser) callonINDENTATION5() (bool, error) { _ = "STUB: not implemented"; return false, nil }

func (c *current) onINDENT1() error { _ = "STUB: not implemented"; return nil }

func (p *parser) callonINDENT1() error { _ = "STUB: not implemented"; return nil }

func (c *current) onDEDENT1() error { _ = "STUB: not implemented"; return nil }

func (p *parser) callonDEDENT1() error { _ = "STUB: not implemented"; return nil }

var (
	// errNoRule is returned when the grammar to parse has no rule.
	errNoRule = errors.New("grammar has no rule")

	// errInvalidEntrypoint is returned when the specified entrypoint rule
	// does not exit.
	errInvalidEntrypoint = errors.New("invalid entrypoint")

	// errInvalidEncoding is returned when the source is not properly
	// utf8-encoded.
	errInvalidEncoding = errors.New("invalid encoding")

	// errMaxExprCnt is used to signal that the maximum number of
	// expressions have been parsed.
	errMaxExprCnt = errors.New("max number of expressions parsed")
)

// Option is a function that can set an option on the parser. It returns
// the previous setting as an Option.
type Option func(*parser) Option

// MaxExpressions creates an Option to stop parsing after the provided
// number of expressions have been parsed, if the value is 0 then the parser will
// parse for as many steps as needed (possibly an infinite number).
//
// The default for maxExprCnt is 0.
func MaxExpressions(maxExprCnt uint64) Option { _ = "STUB: not implemented"; return *new(Option) }

// Entrypoint creates an Option to set the rule name to use as entrypoint.
// The rule name must have been specified in the -alternate-entrypoints
// if generating the parser with the -optimize-grammar flag, otherwise
// it may have been optimized out. Passing an empty string sets the
// entrypoint to the first rule in the grammar.
//
// The default is to start parsing at the first rule in the grammar.
func Entrypoint(ruleName string) Option { _ = "STUB: not implemented"; return *new(Option) }

// Statistics adds a user provided Stats struct to the parser to allow
// the user to process the results after the parsing has finished.
// Also the key for the "no match" counter is set.
//
// Example usage:
//
//	input := "input"
//	stats := Stats{}
//	_, err := Parse("input-file", []byte(input), Statistics(&stats, "no match"))
//	if err != nil {
//	    log.Panicln(err)
//	}
//	b, err := json.MarshalIndent(stats.ChoiceAltCnt, "", "  ")
//	if err != nil {
//	    log.Panicln(err)
//	}
//	fmt.Println(string(b))
func Statistics(stats *Stats, choiceNoMatch string) Option {
	_ = "STUB: not implemented"
	return *new(Option)
}

// Debug creates an Option to set the debug flag to b. When set to true,
// debugging information is printed to stdout while parsing.
//
// The default is false.
func Debug(b bool) Option { _ = "STUB: not implemented"; return *new(Option) }

// Memoize creates an Option to set the memoize flag to b. When set to true,
// the parser will cache all results so each expression is evaluated only
// once. This guarantees linear parsing time even for pathological cases,
// at the expense of more memory and slower times for typical cases.
//
// The default is false.
func Memoize(b bool) Option { _ = "STUB: not implemented"; return *new(Option) }

// AllowInvalidUTF8 creates an Option to allow invalid UTF-8 bytes.
// Every invalid UTF-8 byte is treated as a utf8.RuneError (U+FFFD)
// by character class matchers and is matched by the any matcher.
// The returned matched value, c.text and c.offset are NOT affected.
//
// The default is false.
func AllowInvalidUTF8(b bool) Option { _ = "STUB: not implemented"; return *new(Option) }

// Recover creates an Option to set the recover flag to b. When set to
// true, this causes the parser to recover from panics and convert it
// to an error. Setting it to false can be useful while debugging to
// access the full stack trace.
//
// The default is true.
func Recover(b bool) Option { _ = "STUB: not implemented"; return *new(Option) }

// GlobalStore creates an Option to set a key to a certain value in
// the globalStore.
func GlobalStore(key string, value any) Option { _ = "STUB: not implemented"; return *new(Option) }

// InitState creates an Option to set a key to a certain value in
// the global "state" store.
func InitState(key string, value any) Option { _ = "STUB: not implemented"; return *new(Option) }

// ParseFile parses the file identified by filename.
func ParseFile(filename string, opts ...Option) (i any, err error) {
	_ = "STUB: not implemented" // nolint: deadcode
	return *new(any), nil
}

// ParseReader parses the data from r using filename as information in the
// error messages.
func ParseReader(filename string, r io.Reader, opts ...Option) (any, error) {
	_ = "STUB: not implemented" // nolint: deadcode
	return *new(any), nil
}

// Parse parses the data from b using filename as information in the
// error messages.
func Parse(filename string, b []byte, opts ...Option) (any, error) {
	_ = "STUB: not implemented"
	return *new(any), nil
}

// position records a position in the text.
type position struct {
	line, col, offset int
}

func (p position) String() string { _ = "STUB: not implemented"; return "" }

// savepoint stores all state required to go back to this point in the
// parser.
type savepoint struct {
	position
	rn rune
	w  int
}

type current struct {
	pos  position // start position of the match
	text []byte   // raw text of the match

	// state is a store for arbitrary key,value pairs that the user wants to be
	// tied to the backtracking of the parser.
	// This is always rolled back if a parsing rule fails.
	state storeDict

	// globalStore is a general store for the user to store arbitrary key-value
	// pairs that they need to manage and that they do not want tied to the
	// backtracking of the parser. This is only modified by the user and never
	// rolled back by the parser. It is always up to the user to keep this in a
	// consistent state.
	globalStore storeDict
}

type storeDict map[string]any

// the AST types...

// nolint: structcheck
type grammar struct {
	pos   position
	rules []*rule
}

// nolint: structcheck
type rule struct {
	pos         position
	name        string
	displayName string
	expr        any
}

// nolint: structcheck
type choiceExpr struct {
	pos          position
	alternatives []any
}

// nolint: structcheck
type actionExpr struct {
	pos  position
	expr any
	run  func(*parser) (any, error)
}

// nolint: structcheck
type recoveryExpr struct {
	pos          position
	expr         any
	recoverExpr  any
	failureLabel []string
}

// nolint: structcheck
type seqExpr struct {
	pos   position
	exprs []any
}

// nolint: structcheck
type throwExpr struct {
	pos   position
	label string
}

// nolint: structcheck
type labeledExpr struct {
	pos   position
	label string
	expr  any
}

// nolint: structcheck
type expr struct {
	pos  position
	expr any
}

type (
	andExpr        expr // nolint: structcheck
	notExpr        expr // nolint: structcheck
	zeroOrOneExpr  expr // nolint: structcheck
	zeroOrMoreExpr expr // nolint: structcheck
	oneOrMoreExpr  expr // nolint: structcheck
)

// nolint: structcheck
type ruleRefExpr struct {
	pos  position
	name string
}

// nolint: structcheck
type stateCodeExpr struct {
	pos position
	run func(*parser) error
}

// nolint: structcheck
type andCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

// nolint: structcheck
type notCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

// nolint: structcheck
type litMatcher struct {
	pos        position
	val        string
	ignoreCase bool
	want       string
}

// nolint: structcheck
type charClassMatcher struct {
	pos             position
	val             string
	basicLatinChars [128]bool
	chars           []rune
	ranges          []rune
	classes         []*unicode.RangeTable
	ignoreCase      bool
	inverted        bool
}

type anyMatcher position // nolint: structcheck

// errList cumulates the errors found by the parser.
type errList []error

func (e *errList) add(err error) { _ = "STUB: not implemented"; return }

func (e errList) err() error { _ = "STUB: not implemented"; return nil }

func (e *errList) dedupe() { _ = "STUB: not implemented"; return }

func (e errList) Error() string { _ = "STUB: not implemented"; return "" }

// parserError wraps an error with a prefix indicating the rule in which
// the error occurred. The original error is stored in the Inner field.
type parserError struct {
	Inner    error
	pos      position
	prefix   string
	expected []string
}

// Error returns the error message.
func (p *parserError) Error() string { _ = "STUB: not implemented"; return "" }

// newParser creates a parser with the specified input source and options.
func newParser(filename string, b []byte, opts ...Option) *parser {
	_ = "STUB: not implemented"
	return nil
}

// start rule is rule [0] unless an alternate entrypoint is specified

// setOptions applies the options to the parser.
func (p *parser) setOptions(opts []Option) { _ = "STUB: not implemented"; return }

// nolint: structcheck,deadcode
type resultTuple struct {
	v   any
	b   bool
	end savepoint
}

// nolint: varcheck
const choiceNoMatch = -1

// Stats stores some statistics, gathered during parsing
type Stats struct {
	// ExprCnt counts the number of expressions processed during parsing
	// This value is compared to the maximum number of expressions allowed
	// (set by the MaxExpressions option).
	ExprCnt uint64

	// ChoiceAltCnt is used to count for each ordered choice expression,
	// which alternative is used how may times.
	// These numbers allow to optimize the order of the ordered choice expression
	// to increase the performance of the parser
	//
	// The outer key of ChoiceAltCnt is composed of the name of the rule as well
	// as the line and the column of the ordered choice.
	// The inner key of ChoiceAltCnt is the number (one-based) of the matching alternative.
	// For each alternative the number of matches are counted. If an ordered choice does not
	// match, a special counter is incremented. The name of this counter is set with
	// the parser option Statistics.
	// For an alternative to be included in ChoiceAltCnt, it has to match at least once.
	ChoiceAltCnt map[string]map[string]int
}

// nolint: structcheck,maligned
type parser struct {
	filename string
	pt       savepoint
	cur      current

	data []byte
	errs *errList

	depth   int
	recover bool
	debug   bool

	memoize bool
	// memoization table for the packrat algorithm:
	// map[offset in source] map[expression or rule] {value, match}
	memo map[int]map[any]resultTuple

	// rules table, maps the rule identifier to the rule node
	rules map[string]*rule
	// variables stack, map of label to value
	vstack []map[string]any
	// rule stack, allows identification of the current rule in errors
	rstack []*rule

	// parse fail
	maxFailPos            position
	maxFailExpected       []string
	maxFailInvertExpected bool

	// max number of expressions to be parsed
	maxExprCnt uint64
	// entrypoint for the parser
	entrypoint string

	allowInvalidUTF8 bool

	*Stats

	choiceNoMatch string
	// recovery expression stack, keeps track of the currently available recovery expression, these are traversed in reverse
	recoveryStack []map[string]any
}

// push a variable set on the vstack.
func (p *parser) pushV() { _ = "STUB: not implemented"; return }

// create new empty slot in the stack

// slice to 1 more

// get the last args set

// empty map, all good

// pop a variable set from the vstack.
func (p *parser) popV() {
	_ = "STUB: not implemented"
	// if the map is not empty, clear it
	return
}

// GC that map

// push a recovery expression with its labels to the recoveryStack
func (p *parser) pushRecovery(labels []string, expr any) { _ = "STUB: not implemented"; return }

// create new empty slot in the stack

// slice to 1 more

// pop a recovery expression from the recoveryStack
func (p *parser) popRecovery() {
	_ = "STUB: not implemented"
	// GC that map
	return
}

func (p *parser) print(prefix, s string) string { _ = "STUB: not implemented"; return "" }

func (p *parser) printIndent(mark string, s string) string { _ = "STUB: not implemented"; return "" }

func (p *parser) in(s string) string { _ = "STUB: not implemented"; return "" }

func (p *parser) out(s string) string { _ = "STUB: not implemented"; return "" }

func (p *parser) addErr(err error) { _ = "STUB: not implemented"; return }

func (p *parser) addErrAt(err error, pos position, expected []string) {
	_ = "STUB: not implemented"
	return
}

func (p *parser) failAt(fail bool, pos position, want string) {
	_ = "STUB: not implemented"
	// process fail if parsing fails and not inverted or parsing succeeds and invert is set
	return
}

// read advances the parser to the next rune.
func (p *parser) read() { _ = "STUB: not implemented"; return }

// see utf8.DecodeRune

// restore parser position to the savepoint pt.
func (p *parser) restore(pt savepoint) { _ = "STUB: not implemented"; return }

// Cloner is implemented by any value that has a Clone method, which returns a
// copy of the value. This is mainly used for types which are not passed by
// value (e.g map, slice, chan) or structs that contain such types.
//
// This is used in conjunction with the global state feature to create proper
// copies of the state to allow the parser to properly restore the state in
// the case of backtracking.
type Cloner interface {
	Clone() any
}

var statePool = &sync.Pool{
	New: func() any { return make(storeDict) },
}

func (sd storeDict) Discard() { _ = "STUB: not implemented"; return }

// clone and return parser current state.
func (p *parser) cloneState() storeDict { _ = "STUB: not implemented"; return *new(storeDict) }

// restore parser current state to the state storeDict.
// every restoreState should applied only one time for every cloned state
func (p *parser) restoreState(state storeDict) { _ = "STUB: not implemented"; return }

// get the slice of bytes from the savepoint start to the current position.
func (p *parser) sliceFrom(start savepoint) []byte { _ = "STUB: not implemented"; return nil }

func (p *parser) getMemoized(node any) (resultTuple, bool) {
	_ = "STUB: not implemented"
	return *new(resultTuple), false
}

func (p *parser) setMemoized(pt savepoint, node any, tuple resultTuple) {
	_ = "STUB: not implemented"
	return
}

func (p *parser) buildRulesTable(g *grammar) { _ = "STUB: not implemented"; return }

// nolint: gocyclo
func (p *parser) parse(g *grammar) (val any, err error) {
	_ = "STUB: not implemented"
	return *new(any), nil
}

// TODO : not super critical but this could be generated

// panic can be used in action code to stop parsing immediately
// and return the panic as an error.

// advance to first rune

// If parsing fails, but no errors have been recorded, the expected values
// for the farthest parser position are returned as error.

func listJoin(list []string, sep string, lastSep string) string {
	_ = "STUB: not implemented"
	return ""
}

func (p *parser) parseRuleMemoize(rule *rule) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (p *parser) parseRuleWrap(rule *rule) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (p *parser) parseRule(rule *rule) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (p *parser) parseExprWrap(expr any) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

// nolint: gocyclo
func (p *parser) parseExpr(expr any) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (p *parser) parseActionExpr(act *actionExpr) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (p *parser) parseAndCodeExpr(and *andCodeExpr) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (p *parser) parseAndExpr(and *andExpr) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (p *parser) parseAnyMatcher(any *anyMatcher) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

// EOF - see utf8.DecodeRune

// nolint: gocyclo
func (p *parser) parseCharClassMatcher(chr *charClassMatcher) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

// can't match EOF
// see utf8.DecodeRune

// try to match in the list of available chars

// try to match in the list of ranges

// try to match in the list of Unicode classes

func (p *parser) incChoiceAltCnt(ch *choiceExpr, altI int) { _ = "STUB: not implemented"; return }

// We increment altI by 1, so the keys do not start at 0

func (p *parser) parseChoiceExpr(ch *choiceExpr) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

// dummy assignment to prevent compile error if optimized

func (p *parser) parseLabeledExpr(lab *labeledExpr) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (p *parser) parseLitMatcher(lit *litMatcher) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (p *parser) parseNotCodeExpr(not *notCodeExpr) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (p *parser) parseNotExpr(not *notExpr) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (p *parser) parseOneOrMoreExpr(expr *oneOrMoreExpr) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

// did not match once, no match

func (p *parser) parseRecoveryExpr(recover *recoveryExpr) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (p *parser) parseRuleRefExpr(ref *ruleRefExpr) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (p *parser) parseSeqExpr(seq *seqExpr) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (p *parser) parseStateCodeExpr(state *stateCodeExpr) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (p *parser) parseThrowExpr(expr *throwExpr) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (p *parser) parseZeroOrMoreExpr(expr *zeroOrMoreExpr) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (p *parser) parseZeroOrOneExpr(expr *zeroOrOneExpr) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

// whether it matched or not, consider it a match
