// Code generated by pigeon; DO NOT EDIT.

package leftrecursionthrownrecover

import (
	"errors"
	"io"
	"sync"
	"unicode"
)

var g = &grammar{
	rules: []*rule{
		{
			name: "Start",
			pos:  position{line: 6, col: 1, offset: 41},
			expr: &andCodeExpr{
				pos: position{line: 6, col: 9, offset: 49},
				run: (*parser).callonStart1,
			},
			leader:        false,
			leftRecursive: false,
		},
		{
			name: "case01",
			pos:  position{line: 11, col: 1, offset: 108},
			expr: &actionExpr{
				pos: position{line: 11, col: 10, offset: 117},
				run: (*parser).calloncase011,
				expr: &labeledExpr{
					pos:   position{line: 11, col: 10, offset: 117},
					label: "case01",
					expr: &ruleRefExpr{
						pos:  position{line: 11, col: 17, offset: 124},
						name: "MultiLabelRecover",
					},
				},
			},
			leader:        false,
			leftRecursive: false,
		},
		{
			name: "MultiLabelRecover",
			pos:  position{line: 13, col: 1, offset: 166},
			expr: &recoveryExpr{
				pos: position{line: 13, col: 21, offset: 186},
				expr: &ruleRefExpr{
					pos:  position{line: 13, col: 21, offset: 186},
					name: "number",
				},
				recoverExpr: &ruleRefExpr{
					pos:  position{line: 13, col: 51, offset: 216},
					name: "ErrNonNumber",
				},
				failureLabel: []string{
					"errAlpha",
					"errOther",
				},
			},
			leader:        false,
			leftRecursive: false,
		},
		{
			name: "number",
			pos:  position{line: 15, col: 1, offset: 230},
			expr: &choiceExpr{
				pos: position{line: 15, col: 10, offset: 239},
				alternatives: []any{
					&notExpr{
						pos: position{line: 15, col: 10, offset: 239},
						expr: &anyMatcher{
							line: 15, col: 11, offset: 240,
						},
					},
					&actionExpr{
						pos: position{line: 15, col: 15, offset: 244},
						run: (*parser).callonnumber4,
						expr: &seqExpr{
							pos: position{line: 15, col: 16, offset: 245},
							exprs: []any{
								&labeledExpr{
									pos:   position{line: 15, col: 16, offset: 245},
									label: "n",
									expr: &ruleRefExpr{
										pos:  position{line: 15, col: 18, offset: 247},
										name: "number",
									},
								},
								&labeledExpr{
									pos:   position{line: 15, col: 25, offset: 254},
									label: "d",
									expr: &ruleRefExpr{
										pos:  position{line: 15, col: 27, offset: 256},
										name: "digit",
									},
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 17, col: 5, offset: 309},
						run: (*parser).callonnumber10,
						expr: &labeledExpr{
							pos:   position{line: 17, col: 5, offset: 309},
							label: "d",
							expr: &ruleRefExpr{
								pos:  position{line: 17, col: 7, offset: 311},
								name: "digit",
							},
						},
					},
				},
			},
			leader:        true,
			leftRecursive: true,
		},
		{
			name: "digit",
			pos:  position{line: 21, col: 1, offset: 349},
			expr: &choiceExpr{
				pos: position{line: 21, col: 9, offset: 357},
				alternatives: []any{
					&actionExpr{
						pos: position{line: 21, col: 9, offset: 357},
						run: (*parser).callondigit2,
						expr: &charClassMatcher{
							pos:        position{line: 21, col: 9, offset: 357},
							val:        "[0-9]",
							ranges:     []rune{'0', '9'},
							ignoreCase: false,
							inverted:   false,
						},
					},
					&actionExpr{
						pos: position{line: 23, col: 5, offset: 400},
						run: (*parser).callondigit4,
						expr: &labeledExpr{
							pos:   position{line: 23, col: 5, offset: 400},
							label: "x",
							expr: &seqExpr{
								pos: position{line: 23, col: 9, offset: 404},
								exprs: []any{
									&andExpr{
										pos: position{line: 23, col: 9, offset: 404},
										expr: &charClassMatcher{
											pos:        position{line: 23, col: 10, offset: 405},
											val:        "[a-z]",
											ranges:     []rune{'a', 'z'},
											ignoreCase: false,
											inverted:   false,
										},
									},
									&throwExpr{
										pos:   position{line: 23, col: 16, offset: 411},
										label: "errAlpha",
									},
								},
							},
						},
					},
					&throwExpr{
						pos:   position{line: 25, col: 5, offset: 460},
						label: "errOther",
					},
				},
			},
			leader:        false,
			leftRecursive: false,
		},
		{
			name: "ErrNonNumber",
			pos:  position{line: 27, col: 1, offset: 473},
			expr: &actionExpr{
				pos: position{line: 27, col: 16, offset: 488},
				run: (*parser).callonErrNonNumber1,
				expr: &seqExpr{
					pos: position{line: 27, col: 16, offset: 488},
					exprs: []any{
						&andCodeExpr{
							pos: position{line: 27, col: 16, offset: 488},
							run: (*parser).callonErrNonNumber3,
						},
						&zeroOrMoreExpr{
							pos: position{line: 29, col: 3, offset: 543},
							expr: &seqExpr{
								pos: position{line: 29, col: 5, offset: 545},
								exprs: []any{
									&notExpr{
										pos: position{line: 29, col: 5, offset: 545},
										expr: &charClassMatcher{
											pos:        position{line: 29, col: 6, offset: 546},
											val:        "[0-9]",
											ranges:     []rune{'0', '9'},
											ignoreCase: false,
											inverted:   false,
										},
									},
									&anyMatcher{
										line: 29, col: 12, offset: 552,
									},
								},
							},
						},
					},
				},
			},
			leader:        false,
			leftRecursive: false,
		},
		{
			name: "case02",
			pos:  position{line: 34, col: 1, offset: 614},
			expr: &choiceExpr{
				pos: position{line: 34, col: 11, offset: 624},
				alternatives: []any{
					&ruleRefExpr{
						pos:  position{line: 34, col: 11, offset: 624},
						name: "ThrowUndefLabel",
					},
					&andCodeExpr{
						pos: position{line: 34, col: 29, offset: 642},
						run: (*parser).calloncase023,
					},
				},
			},
			leader:        false,
			leftRecursive: false,
		},
		{
			name: "ThrowUndefLabel",
			pos:  position{line: 36, col: 1, offset: 699},
			expr: &seqExpr{
				pos: position{line: 36, col: 19, offset: 717},
				exprs: []any{
					&ruleRefExpr{
						pos:  position{line: 36, col: 19, offset: 717},
						name: "ThrowUndefLabel",
					},
					&throwExpr{
						pos:   position{line: 36, col: 35, offset: 733},
						label: "undeflabel",
					},
				},
			},
			leader:        true,
			leftRecursive: true,
		},
		{
			name: "case03",
			pos:  position{line: 41, col: 1, offset: 777},
			expr: &actionExpr{
				pos: position{line: 41, col: 10, offset: 786},
				run: (*parser).calloncase031,
				expr: &labeledExpr{
					pos:   position{line: 41, col: 10, offset: 786},
					label: "case03",
					expr: &ruleRefExpr{
						pos:  position{line: 41, col: 17, offset: 793},
						name: "OuterRecover03",
					},
				},
			},
			leader:        false,
			leftRecursive: false,
		},
		{
			name: "OuterRecover03",
			pos:  position{line: 43, col: 1, offset: 832},
			expr: &recoveryExpr{
				pos: position{line: 43, col: 18, offset: 849},
				expr: &recoveryExpr{
					pos: position{line: 43, col: 18, offset: 849},
					expr: &ruleRefExpr{
						pos:  position{line: 43, col: 18, offset: 849},
						name: "InnerRecover03",
					},
					recoverExpr: &ruleRefExpr{
						pos:  position{line: 43, col: 66, offset: 897},
						name: "ErrAlphaOuter03",
					},
					failureLabel: []string{
						"errAlphaLower",
						"errAlphaUpper",
					},
				},
				recoverExpr: &ruleRefExpr{
					pos:  position{line: 43, col: 95, offset: 926},
					name: "ErrOtherOuter03",
				},
				failureLabel: []string{
					"errOther",
				},
			},
			leader:        false,
			leftRecursive: false,
		},
		{
			name: "InnerRecover03",
			pos:  position{line: 45, col: 1, offset: 943},
			expr: &recoveryExpr{
				pos: position{line: 45, col: 18, offset: 960},
				expr: &ruleRefExpr{
					pos:  position{line: 45, col: 18, offset: 960},
					name: "number03",
				},
				recoverExpr: &ruleRefExpr{
					pos:  position{line: 45, col: 45, offset: 987},
					name: "ErrAlphaInner03",
				},
				failureLabel: []string{
					"errAlphaLower",
				},
			},
			leader:        false,
			leftRecursive: false,
		},
		{
			name: "number03",
			pos:  position{line: 47, col: 1, offset: 1004},
			expr: &choiceExpr{
				pos: position{line: 47, col: 12, offset: 1015},
				alternatives: []any{
					&notExpr{
						pos: position{line: 47, col: 12, offset: 1015},
						expr: &anyMatcher{
							line: 47, col: 13, offset: 1016,
						},
					},
					&actionExpr{
						pos: position{line: 47, col: 17, offset: 1020},
						run: (*parser).callonnumber034,
						expr: &seqExpr{
							pos: position{line: 47, col: 18, offset: 1021},
							exprs: []any{
								&labeledExpr{
									pos:   position{line: 47, col: 18, offset: 1021},
									label: "n",
									expr: &ruleRefExpr{
										pos:  position{line: 47, col: 20, offset: 1023},
										name: "number03",
									},
								},
								&labeledExpr{
									pos:   position{line: 47, col: 29, offset: 1032},
									label: "d",
									expr: &ruleRefExpr{
										pos:  position{line: 47, col: 31, offset: 1034},
										name: "digit03",
									},
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 49, col: 5, offset: 1089},
						run: (*parser).callonnumber0310,
						expr: &labeledExpr{
							pos:   position{line: 49, col: 5, offset: 1089},
							label: "d",
							expr: &ruleRefExpr{
								pos:  position{line: 49, col: 7, offset: 1091},
								name: "digit03",
							},
						},
					},
				},
			},
			leader:        true,
			leftRecursive: true,
		},
		{
			name: "digit03",
			pos:  position{line: 53, col: 1, offset: 1131},
			expr: &choiceExpr{
				pos: position{line: 53, col: 11, offset: 1141},
				alternatives: []any{
					&actionExpr{
						pos: position{line: 53, col: 11, offset: 1141},
						run: (*parser).callondigit032,
						expr: &charClassMatcher{
							pos:        position{line: 53, col: 11, offset: 1141},
							val:        "[0-9]",
							ranges:     []rune{'0', '9'},
							ignoreCase: false,
							inverted:   false,
						},
					},
					&actionExpr{
						pos: position{line: 55, col: 5, offset: 1184},
						run: (*parser).callondigit034,
						expr: &labeledExpr{
							pos:   position{line: 55, col: 5, offset: 1184},
							label: "x",
							expr: &seqExpr{
								pos: position{line: 55, col: 9, offset: 1188},
								exprs: []any{
									&andExpr{
										pos: position{line: 55, col: 9, offset: 1188},
										expr: &charClassMatcher{
											pos:        position{line: 55, col: 10, offset: 1189},
											val:        "[a-z]",
											ranges:     []rune{'a', 'z'},
											ignoreCase: false,
											inverted:   false,
										},
									},
									&throwExpr{
										pos:   position{line: 55, col: 16, offset: 1195},
										label: "errAlphaLower",
									},
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 57, col: 5, offset: 1249},
						run: (*parser).callondigit0310,
						expr: &labeledExpr{
							pos:   position{line: 57, col: 5, offset: 1249},
							label: "x",
							expr: &seqExpr{
								pos: position{line: 57, col: 9, offset: 1253},
								exprs: []any{
									&andExpr{
										pos: position{line: 57, col: 9, offset: 1253},
										expr: &charClassMatcher{
											pos:        position{line: 57, col: 10, offset: 1254},
											val:        "[A-Z]",
											ranges:     []rune{'A', 'Z'},
											ignoreCase: false,
											inverted:   false,
										},
									},
									&throwExpr{
										pos:   position{line: 57, col: 16, offset: 1260},
										label: "errAlphaUpper",
									},
								},
							},
						},
					},
					&throwExpr{
						pos:   position{line: 59, col: 5, offset: 1314},
						label: "errOther",
					},
				},
			},
			leader:        false,
			leftRecursive: false,
		},
		{
			name: "ErrAlphaInner03",
			pos:  position{line: 61, col: 1, offset: 1327},
			expr: &actionExpr{
				pos: position{line: 61, col: 19, offset: 1345},
				run: (*parser).callonErrAlphaInner031,
				expr: &seqExpr{
					pos: position{line: 61, col: 19, offset: 1345},
					exprs: []any{
						&andCodeExpr{
							pos: position{line: 61, col: 19, offset: 1345},
							run: (*parser).callonErrAlphaInner033,
						},
						&zeroOrMoreExpr{
							pos: position{line: 63, col: 3, offset: 1421},
							expr: &seqExpr{
								pos: position{line: 63, col: 5, offset: 1423},
								exprs: []any{
									&notExpr{
										pos: position{line: 63, col: 5, offset: 1423},
										expr: &charClassMatcher{
											pos:        position{line: 63, col: 6, offset: 1424},
											val:        "[0-9]",
											ranges:     []rune{'0', '9'},
											ignoreCase: false,
											inverted:   false,
										},
									},
									&anyMatcher{
										line: 63, col: 12, offset: 1430,
									},
								},
							},
						},
					},
				},
			},
			leader:        false,
			leftRecursive: false,
		},
		{
			name: "ErrAlphaOuter03",
			pos:  position{line: 65, col: 1, offset: 1456},
			expr: &actionExpr{
				pos: position{line: 65, col: 19, offset: 1474},
				run: (*parser).callonErrAlphaOuter031,
				expr: &seqExpr{
					pos: position{line: 65, col: 19, offset: 1474},
					exprs: []any{
						&andCodeExpr{
							pos: position{line: 65, col: 19, offset: 1474},
							run: (*parser).callonErrAlphaOuter033,
						},
						&zeroOrMoreExpr{
							pos: position{line: 67, col: 3, offset: 1550},
							expr: &seqExpr{
								pos: position{line: 67, col: 5, offset: 1552},
								exprs: []any{
									&notExpr{
										pos: position{line: 67, col: 5, offset: 1552},
										expr: &charClassMatcher{
											pos:        position{line: 67, col: 6, offset: 1553},
											val:        "[0-9]",
											ranges:     []rune{'0', '9'},
											ignoreCase: false,
											inverted:   false,
										},
									},
									&anyMatcher{
										line: 67, col: 12, offset: 1559,
									},
								},
							},
						},
					},
				},
			},
			leader:        false,
			leftRecursive: false,
		},
		{
			name: "ErrOtherOuter03",
			pos:  position{line: 69, col: 1, offset: 1585},
			expr: &actionExpr{
				pos: position{line: 69, col: 19, offset: 1603},
				run: (*parser).callonErrOtherOuter031,
				expr: &seqExpr{
					pos: position{line: 69, col: 19, offset: 1603},
					exprs: []any{
						&andCodeExpr{
							pos: position{line: 69, col: 19, offset: 1603},
							run: (*parser).callonErrOtherOuter033,
						},
						&zeroOrMoreExpr{
							pos: position{line: 71, col: 3, offset: 1674},
							expr: &seqExpr{
								pos: position{line: 71, col: 5, offset: 1676},
								exprs: []any{
									&notExpr{
										pos: position{line: 71, col: 5, offset: 1676},
										expr: &charClassMatcher{
											pos:        position{line: 71, col: 6, offset: 1677},
											val:        "[0-9]",
											ranges:     []rune{'0', '9'},
											ignoreCase: false,
											inverted:   false,
										},
									},
									&anyMatcher{
										line: 71, col: 12, offset: 1683,
									},
								},
							},
						},
					},
				},
			},
			leader:        false,
			leftRecursive: false,
		},
		{
			name: "case04",
			pos:  position{line: 76, col: 1, offset: 1768},
			expr: &actionExpr{
				pos: position{line: 76, col: 10, offset: 1777},
				run: (*parser).calloncase041,
				expr: &labeledExpr{
					pos:   position{line: 76, col: 10, offset: 1777},
					label: "case04",
					expr: &ruleRefExpr{
						pos:  position{line: 76, col: 17, offset: 1784},
						name: "OuterRecover04",
					},
				},
			},
			leader:        false,
			leftRecursive: false,
		},
		{
			name: "OuterRecover04",
			pos:  position{line: 78, col: 1, offset: 1823},
			expr: &recoveryExpr{
				pos: position{line: 78, col: 18, offset: 1840},
				expr: &recoveryExpr{
					pos: position{line: 78, col: 18, offset: 1840},
					expr: &ruleRefExpr{
						pos:  position{line: 78, col: 18, offset: 1840},
						name: "InnerRecover04",
					},
					recoverExpr: &ruleRefExpr{
						pos:  position{line: 78, col: 66, offset: 1888},
						name: "ErrAlphaOuter04",
					},
					failureLabel: []string{
						"errAlphaLower",
						"errAlphaUpper",
					},
				},
				recoverExpr: &ruleRefExpr{
					pos:  position{line: 78, col: 95, offset: 1917},
					name: "ErrOtherOuter04",
				},
				failureLabel: []string{
					"errOther",
				},
			},
			leader:        false,
			leftRecursive: false,
		},
		{
			name: "InnerRecover04",
			pos:  position{line: 80, col: 1, offset: 1934},
			expr: &recoveryExpr{
				pos: position{line: 80, col: 18, offset: 1951},
				expr: &ruleRefExpr{
					pos:  position{line: 80, col: 18, offset: 1951},
					name: "number04",
				},
				recoverExpr: &ruleRefExpr{
					pos:  position{line: 80, col: 45, offset: 1978},
					name: "ErrAlphaInner04",
				},
				failureLabel: []string{
					"errAlphaLower",
				},
			},
			leader:        false,
			leftRecursive: false,
		},
		{
			name: "number04",
			pos:  position{line: 82, col: 1, offset: 1995},
			expr: &choiceExpr{
				pos: position{line: 82, col: 12, offset: 2006},
				alternatives: []any{
					&notExpr{
						pos: position{line: 82, col: 12, offset: 2006},
						expr: &anyMatcher{
							line: 82, col: 13, offset: 2007,
						},
					},
					&actionExpr{
						pos: position{line: 82, col: 17, offset: 2011},
						run: (*parser).callonnumber044,
						expr: &seqExpr{
							pos: position{line: 82, col: 18, offset: 2012},
							exprs: []any{
								&labeledExpr{
									pos:   position{line: 82, col: 18, offset: 2012},
									label: "n",
									expr: &ruleRefExpr{
										pos:  position{line: 82, col: 20, offset: 2014},
										name: "number04",
									},
								},
								&labeledExpr{
									pos:   position{line: 82, col: 29, offset: 2023},
									label: "d",
									expr: &ruleRefExpr{
										pos:  position{line: 82, col: 31, offset: 2025},
										name: "digit04",
									},
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 84, col: 5, offset: 2080},
						run: (*parser).callonnumber0410,
						expr: &labeledExpr{
							pos:   position{line: 84, col: 5, offset: 2080},
							label: "d",
							expr: &ruleRefExpr{
								pos:  position{line: 84, col: 7, offset: 2082},
								name: "digit04",
							},
						},
					},
				},
			},
			leader:        true,
			leftRecursive: true,
		},
		{
			name: "digit04",
			pos:  position{line: 88, col: 1, offset: 2122},
			expr: &choiceExpr{
				pos: position{line: 88, col: 11, offset: 2132},
				alternatives: []any{
					&actionExpr{
						pos: position{line: 88, col: 11, offset: 2132},
						run: (*parser).callondigit042,
						expr: &charClassMatcher{
							pos:        position{line: 88, col: 11, offset: 2132},
							val:        "[0-9]",
							ranges:     []rune{'0', '9'},
							ignoreCase: false,
							inverted:   false,
						},
					},
					&actionExpr{
						pos: position{line: 90, col: 5, offset: 2175},
						run: (*parser).callondigit044,
						expr: &labeledExpr{
							pos:   position{line: 90, col: 5, offset: 2175},
							label: "x",
							expr: &seqExpr{
								pos: position{line: 90, col: 9, offset: 2179},
								exprs: []any{
									&andExpr{
										pos: position{line: 90, col: 9, offset: 2179},
										expr: &charClassMatcher{
											pos:        position{line: 90, col: 10, offset: 2180},
											val:        "[a-z]",
											ranges:     []rune{'a', 'z'},
											ignoreCase: false,
											inverted:   false,
										},
									},
									&throwExpr{
										pos:   position{line: 90, col: 16, offset: 2186},
										label: "errAlphaLower",
									},
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 92, col: 5, offset: 2240},
						run: (*parser).callondigit0410,
						expr: &labeledExpr{
							pos:   position{line: 92, col: 5, offset: 2240},
							label: "x",
							expr: &seqExpr{
								pos: position{line: 92, col: 9, offset: 2244},
								exprs: []any{
									&andExpr{
										pos: position{line: 92, col: 9, offset: 2244},
										expr: &charClassMatcher{
											pos:        position{line: 92, col: 10, offset: 2245},
											val:        "[A-Z]",
											ranges:     []rune{'A', 'Z'},
											ignoreCase: false,
											inverted:   false,
										},
									},
									&throwExpr{
										pos:   position{line: 92, col: 16, offset: 2251},
										label: "errAlphaUpper",
									},
								},
							},
						},
					},
					&throwExpr{
						pos:   position{line: 94, col: 5, offset: 2305},
						label: "errOther",
					},
				},
			},
			leader:        false,
			leftRecursive: false,
		},
		{
			name: "ErrAlphaInner04",
			pos:  position{line: 96, col: 1, offset: 2318},
			expr: &andCodeExpr{
				pos: position{line: 96, col: 19, offset: 2336},
				run: (*parser).callonErrAlphaInner041,
			},
			leader:        false,
			leftRecursive: false,
		},
		{
			name: "ErrAlphaOuter04",
			pos:  position{line: 100, col: 1, offset: 2364},
			expr: &actionExpr{
				pos: position{line: 100, col: 19, offset: 2382},
				run: (*parser).callonErrAlphaOuter041,
				expr: &seqExpr{
					pos: position{line: 100, col: 19, offset: 2382},
					exprs: []any{
						&andCodeExpr{
							pos: position{line: 100, col: 19, offset: 2382},
							run: (*parser).callonErrAlphaOuter043,
						},
						&zeroOrMoreExpr{
							pos: position{line: 102, col: 3, offset: 2449},
							expr: &seqExpr{
								pos: position{line: 102, col: 5, offset: 2451},
								exprs: []any{
									&notExpr{
										pos: position{line: 102, col: 5, offset: 2451},
										expr: &charClassMatcher{
											pos:        position{line: 102, col: 6, offset: 2452},
											val:        "[0-9]",
											ranges:     []rune{'0', '9'},
											ignoreCase: false,
											inverted:   false,
										},
									},
									&anyMatcher{
										line: 102, col: 12, offset: 2458,
									},
								},
							},
						},
					},
				},
			},
			leader:        false,
			leftRecursive: false,
		},
		{
			name: "ErrOtherOuter04",
			pos:  position{line: 104, col: 1, offset: 2484},
			expr: &actionExpr{
				pos: position{line: 104, col: 19, offset: 2502},
				run: (*parser).callonErrOtherOuter041,
				expr: &seqExpr{
					pos: position{line: 104, col: 19, offset: 2502},
					exprs: []any{
						&andCodeExpr{
							pos: position{line: 104, col: 19, offset: 2502},
							run: (*parser).callonErrOtherOuter043,
						},
						&zeroOrMoreExpr{
							pos: position{line: 106, col: 3, offset: 2573},
							expr: &seqExpr{
								pos: position{line: 106, col: 5, offset: 2575},
								exprs: []any{
									&notExpr{
										pos: position{line: 106, col: 5, offset: 2575},
										expr: &charClassMatcher{
											pos:        position{line: 106, col: 6, offset: 2576},
											val:        "[0-9]",
											ranges:     []rune{'0', '9'},
											ignoreCase: false,
											inverted:   false,
										},
									},
									&anyMatcher{
										line: 106, col: 12, offset: 2582,
									},
								},
							},
						},
					},
				},
			},
			leader:        false,
			leftRecursive: false,
		},
	},
}

func (c *current) onStart1() (bool, error) { _ = "STUB: not implemented"; return false, nil }

func (p *parser) callonStart1() (bool, error) { _ = "STUB: not implemented"; return false, nil }

func (c *current) oncase011(case01 any) (any, error) {
	_ = "STUB: not implemented"
	return *new(any), nil
}

func (p *parser) calloncase011() (any, error) { _ = "STUB: not implemented"; return *new(any), nil }

func (c *current) onnumber4(n, d any) (any, error) {
	_ = "STUB: not implemented"
	return *new(any), nil
}

func (p *parser) callonnumber4() (any, error) { _ = "STUB: not implemented"; return *new(any), nil }

func (c *current) onnumber10(d any) (any, error) { _ = "STUB: not implemented"; return *new(any), nil }

func (p *parser) callonnumber10() (any, error) { _ = "STUB: not implemented"; return *new(any), nil }

func (c *current) ondigit2() (any, error) { _ = "STUB: not implemented"; return *new(any), nil }

func (p *parser) callondigit2() (any, error) { _ = "STUB: not implemented"; return *new(any), nil }

func (c *current) ondigit4(x any) (any, error) { _ = "STUB: not implemented"; return *new(any), nil }

func (p *parser) callondigit4() (any, error) { _ = "STUB: not implemented"; return *new(any), nil }

func (c *current) onErrNonNumber3() (bool, error) { _ = "STUB: not implemented"; return false, nil }

func (p *parser) callonErrNonNumber3() (bool, error) { _ = "STUB: not implemented"; return false, nil }

func (c *current) onErrNonNumber1() (any, error) { _ = "STUB: not implemented"; return *new(any), nil }

func (p *parser) callonErrNonNumber1() (any, error) {
	_ = "STUB: not implemented"
	return *new(any), nil
}

func (c *current) oncase023() (bool, error) { _ = "STUB: not implemented"; return false, nil }

func (p *parser) calloncase023() (bool, error) { _ = "STUB: not implemented"; return false, nil }

func (c *current) oncase031(case03 any) (any, error) {
	_ = "STUB: not implemented"
	return *new(any), nil
}

func (p *parser) calloncase031() (any, error) { _ = "STUB: not implemented"; return *new(any), nil }

func (c *current) onnumber034(n, d any) (any, error) {
	_ = "STUB: not implemented"
	return *new(any), nil
}

func (p *parser) callonnumber034() (any, error) { _ = "STUB: not implemented"; return *new(any), nil }

func (c *current) onnumber0310(d any) (any, error) {
	_ = "STUB: not implemented"
	return *new(any), nil
}

func (p *parser) callonnumber0310() (any, error) { _ = "STUB: not implemented"; return *new(any), nil }

func (c *current) ondigit032() (any, error) { _ = "STUB: not implemented"; return *new(any), nil }

func (p *parser) callondigit032() (any, error) { _ = "STUB: not implemented"; return *new(any), nil }

func (c *current) ondigit034(x any) (any, error) { _ = "STUB: not implemented"; return *new(any), nil }

func (p *parser) callondigit034() (any, error) { _ = "STUB: not implemented"; return *new(any), nil }

func (c *current) ondigit0310(x any) (any, error) { _ = "STUB: not implemented"; return *new(any), nil }

func (p *parser) callondigit0310() (any, error) { _ = "STUB: not implemented"; return *new(any), nil }

func (c *current) onErrAlphaInner033() (bool, error) { _ = "STUB: not implemented"; return false, nil }

func (p *parser) callonErrAlphaInner033() (bool, error) {
	_ = "STUB: not implemented"
	return false, nil
}

func (c *current) onErrAlphaInner031() (any, error) {
	_ = "STUB: not implemented"
	return *new(any), nil
}

func (p *parser) callonErrAlphaInner031() (any, error) {
	_ = "STUB: not implemented"
	return *new(any), nil
}

func (c *current) onErrAlphaOuter033() (bool, error) { _ = "STUB: not implemented"; return false, nil }

func (p *parser) callonErrAlphaOuter033() (bool, error) {
	_ = "STUB: not implemented"
	return false, nil
}

func (c *current) onErrAlphaOuter031() (any, error) {
	_ = "STUB: not implemented"
	return *new(any), nil
}

func (p *parser) callonErrAlphaOuter031() (any, error) {
	_ = "STUB: not implemented"
	return *new(any), nil
}

func (c *current) onErrOtherOuter033() (bool, error) { _ = "STUB: not implemented"; return false, nil }

func (p *parser) callonErrOtherOuter033() (bool, error) {
	_ = "STUB: not implemented"
	return false, nil
}

func (c *current) onErrOtherOuter031() (any, error) {
	_ = "STUB: not implemented"
	return *new(any), nil
}

func (p *parser) callonErrOtherOuter031() (any, error) {
	_ = "STUB: not implemented"
	return *new(any), nil
}

func (c *current) oncase041(case04 any) (any, error) {
	_ = "STUB: not implemented"
	return *new(any), nil
}

func (p *parser) calloncase041() (any, error) { _ = "STUB: not implemented"; return *new(any), nil }

func (c *current) onnumber044(n, d any) (any, error) {
	_ = "STUB: not implemented"
	return *new(any), nil
}

func (p *parser) callonnumber044() (any, error) { _ = "STUB: not implemented"; return *new(any), nil }

func (c *current) onnumber0410(d any) (any, error) {
	_ = "STUB: not implemented"
	return *new(any), nil
}

func (p *parser) callonnumber0410() (any, error) { _ = "STUB: not implemented"; return *new(any), nil }

func (c *current) ondigit042() (any, error) { _ = "STUB: not implemented"; return *new(any), nil }

func (p *parser) callondigit042() (any, error) { _ = "STUB: not implemented"; return *new(any), nil }

func (c *current) ondigit044(x any) (any, error) { _ = "STUB: not implemented"; return *new(any), nil }

func (p *parser) callondigit044() (any, error) { _ = "STUB: not implemented"; return *new(any), nil }

func (c *current) ondigit0410(x any) (any, error) { _ = "STUB: not implemented"; return *new(any), nil }

func (p *parser) callondigit0410() (any, error) { _ = "STUB: not implemented"; return *new(any), nil }

func (c *current) onErrAlphaInner041() (bool, error) { _ = "STUB: not implemented"; return false, nil }

func (p *parser) callonErrAlphaInner041() (bool, error) {
	_ = "STUB: not implemented"
	return false, nil
}

func (c *current) onErrAlphaOuter043() (bool, error) { _ = "STUB: not implemented"; return false, nil }

func (p *parser) callonErrAlphaOuter043() (bool, error) {
	_ = "STUB: not implemented"
	return false, nil
}

func (c *current) onErrAlphaOuter041() (any, error) {
	_ = "STUB: not implemented"
	return *new(any), nil
}

func (p *parser) callonErrAlphaOuter041() (any, error) {
	_ = "STUB: not implemented"
	return *new(any), nil
}

func (c *current) onErrOtherOuter043() (bool, error) { _ = "STUB: not implemented"; return false, nil }

func (p *parser) callonErrOtherOuter043() (bool, error) {
	_ = "STUB: not implemented"
	return false, nil
}

func (c *current) onErrOtherOuter041() (any, error) {
	_ = "STUB: not implemented"
	return *new(any), nil
}

func (p *parser) callonErrOtherOuter041() (any, error) {
	_ = "STUB: not implemented"
	return *new(any), nil
}

var (
	// errNoRule is returned when the grammar to parse has no rule.
	errNoRule = errors.New("grammar has no rule")

	// errInvalidEntrypoint is returned when the specified entrypoint rule
	// does not exit.
	errInvalidEntrypoint = errors.New("invalid entrypoint")

	// errInvalidEncoding is returned when the source is not properly
	// utf8-encoded.
	errInvalidEncoding = errors.New("invalid encoding")

	// errMaxExprCnt is used to signal that the maximum number of
	// expressions have been parsed.
	errMaxExprCnt = errors.New("max number of expressions parsed")
)

// Option is a function that can set an option on the parser. It returns
// the previous setting as an Option.
type Option func(*parser) Option

// MaxExpressions creates an Option to stop parsing after the provided
// number of expressions have been parsed, if the value is 0 then the parser will
// parse for as many steps as needed (possibly an infinite number).
//
// The default for maxExprCnt is 0.
func MaxExpressions(maxExprCnt uint64) Option { _ = "STUB: not implemented"; return *new(Option) }

// Entrypoint creates an Option to set the rule name to use as entrypoint.
// The rule name must have been specified in the -alternate-entrypoints
// if generating the parser with the -optimize-grammar flag, otherwise
// it may have been optimized out. Passing an empty string sets the
// entrypoint to the first rule in the grammar.
//
// The default is to start parsing at the first rule in the grammar.
func Entrypoint(ruleName string) Option { _ = "STUB: not implemented"; return *new(Option) }

// Statistics adds a user provided Stats struct to the parser to allow
// the user to process the results after the parsing has finished.
// Also the key for the "no match" counter is set.
//
// Example usage:
//
//	input := "input"
//	stats := Stats{}
//	_, err := Parse("input-file", []byte(input), Statistics(&stats, "no match"))
//	if err != nil {
//	    log.Panicln(err)
//	}
//	b, err := json.MarshalIndent(stats.ChoiceAltCnt, "", "  ")
//	if err != nil {
//	    log.Panicln(err)
//	}
//	fmt.Println(string(b))
func Statistics(stats *Stats, choiceNoMatch string) Option {
	_ = "STUB: not implemented"
	return *new(Option)
}

// Debug creates an Option to set the debug flag to b. When set to true,
// debugging information is printed to stdout while parsing.
//
// The default is false.
func Debug(b bool) Option { _ = "STUB: not implemented"; return *new(Option) }

// Memoize creates an Option to set the memoize flag to b. When set to true,
// the parser will cache all results so each expression is evaluated only
// once. This guarantees linear parsing time even for pathological cases,
// at the expense of more memory and slower times for typical cases.
//
// The default is false.
func Memoize(b bool) Option { _ = "STUB: not implemented"; return *new(Option) }

// AllowInvalidUTF8 creates an Option to allow invalid UTF-8 bytes.
// Every invalid UTF-8 byte is treated as a utf8.RuneError (U+FFFD)
// by character class matchers and is matched by the any matcher.
// The returned matched value, c.text and c.offset are NOT affected.
//
// The default is false.
func AllowInvalidUTF8(b bool) Option { _ = "STUB: not implemented"; return *new(Option) }

// Recover creates an Option to set the recover flag to b. When set to
// true, this causes the parser to recover from panics and convert it
// to an error. Setting it to false can be useful while debugging to
// access the full stack trace.
//
// The default is true.
func Recover(b bool) Option { _ = "STUB: not implemented"; return *new(Option) }

// GlobalStore creates an Option to set a key to a certain value in
// the globalStore.
func GlobalStore(key string, value any) Option { _ = "STUB: not implemented"; return *new(Option) }

// InitState creates an Option to set a key to a certain value in
// the global "state" store.
func InitState(key string, value any) Option { _ = "STUB: not implemented"; return *new(Option) }

// ParseFile parses the file identified by filename.
func ParseFile(filename string, opts ...Option) (i any, err error) {
	_ = "STUB: not implemented" // nolint: deadcode
	return *new(any), nil
}

// ParseReader parses the data from r using filename as information in the
// error messages.
func ParseReader(filename string, r io.Reader, opts ...Option) (any, error) {
	_ = "STUB: not implemented" // nolint: deadcode
	return *new(any), nil
}

// Parse parses the data from b using filename as information in the
// error messages.
func Parse(filename string, b []byte, opts ...Option) (any, error) {
	_ = "STUB: not implemented"
	return *new(any), nil
}

// position records a position in the text.
type position struct {
	line, col, offset int
}

func (p position) String() string { _ = "STUB: not implemented"; return "" }

// savepoint stores all state required to go back to this point in the
// parser.
type savepoint struct {
	position
	rn rune
	w  int
}

type current struct {
	pos  position // start position of the match
	text []byte   // raw text of the match

	// state is a store for arbitrary key,value pairs that the user wants to be
	// tied to the backtracking of the parser.
	// This is always rolled back if a parsing rule fails.
	state storeDict

	// globalStore is a general store for the user to store arbitrary key-value
	// pairs that they need to manage and that they do not want tied to the
	// backtracking of the parser. This is only modified by the user and never
	// rolled back by the parser. It is always up to the user to keep this in a
	// consistent state.
	globalStore storeDict
}

type storeDict map[string]any

// the AST types...

// nolint: structcheck
type grammar struct {
	pos   position
	rules []*rule
}

// nolint: structcheck
type rule struct {
	pos         position
	name        string
	displayName string
	expr        any

	leader        bool
	leftRecursive bool
}

// nolint: structcheck
type choiceExpr struct {
	pos          position
	alternatives []any
}

// nolint: structcheck
type actionExpr struct {
	pos  position
	expr any
	run  func(*parser) (any, error)
}

// nolint: structcheck
type recoveryExpr struct {
	pos          position
	expr         any
	recoverExpr  any
	failureLabel []string
}

// nolint: structcheck
type seqExpr struct {
	pos   position
	exprs []any
}

// nolint: structcheck
type throwExpr struct {
	pos   position
	label string
}

// nolint: structcheck
type labeledExpr struct {
	pos   position
	label string
	expr  any
}

// nolint: structcheck
type expr struct {
	pos  position
	expr any
}

type (
	andExpr        expr // nolint: structcheck
	notExpr        expr // nolint: structcheck
	zeroOrOneExpr  expr // nolint: structcheck
	zeroOrMoreExpr expr // nolint: structcheck
	oneOrMoreExpr  expr // nolint: structcheck
)

// nolint: structcheck
type ruleRefExpr struct {
	pos  position
	name string
}

// nolint: structcheck
type stateCodeExpr struct {
	pos position
	run func(*parser) error
}

// nolint: structcheck
type andCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

// nolint: structcheck
type notCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

// nolint: structcheck
type litMatcher struct {
	pos        position
	val        string
	ignoreCase bool
	want       string
}

// nolint: structcheck
type charClassMatcher struct {
	pos             position
	val             string
	basicLatinChars [128]bool
	chars           []rune
	ranges          []rune
	classes         []*unicode.RangeTable
	ignoreCase      bool
	inverted        bool
}

type anyMatcher position // nolint: structcheck

// errList cumulates the errors found by the parser.
type errList []error

func (e *errList) add(err error) { _ = "STUB: not implemented"; return }

func (e errList) err() error { _ = "STUB: not implemented"; return nil }

func (e *errList) dedupe() { _ = "STUB: not implemented"; return }

func (e errList) Error() string { _ = "STUB: not implemented"; return "" }

// parserError wraps an error with a prefix indicating the rule in which
// the error occurred. The original error is stored in the Inner field.
type parserError struct {
	Inner    error
	pos      position
	prefix   string
	expected []string
}

// Error returns the error message.
func (p *parserError) Error() string { _ = "STUB: not implemented"; return "" }

// newParser creates a parser with the specified input source and options.
func newParser(filename string, b []byte, opts ...Option) *parser {
	_ = "STUB: not implemented"
	return nil
}

// start rule is rule [0] unless an alternate entrypoint is specified

// setOptions applies the options to the parser.
func (p *parser) setOptions(opts []Option) { _ = "STUB: not implemented"; return }

// nolint: structcheck,deadcode
type resultTuple struct {
	v   any
	b   bool
	end savepoint
}

// nolint: varcheck
const choiceNoMatch = -1

// Stats stores some statistics, gathered during parsing
type Stats struct {
	// ExprCnt counts the number of expressions processed during parsing
	// This value is compared to the maximum number of expressions allowed
	// (set by the MaxExpressions option).
	ExprCnt uint64

	// ChoiceAltCnt is used to count for each ordered choice expression,
	// which alternative is used how may times.
	// These numbers allow to optimize the order of the ordered choice expression
	// to increase the performance of the parser
	//
	// The outer key of ChoiceAltCnt is composed of the name of the rule as well
	// as the line and the column of the ordered choice.
	// The inner key of ChoiceAltCnt is the number (one-based) of the matching alternative.
	// For each alternative the number of matches are counted. If an ordered choice does not
	// match, a special counter is incremented. The name of this counter is set with
	// the parser option Statistics.
	// For an alternative to be included in ChoiceAltCnt, it has to match at least once.
	ChoiceAltCnt map[string]map[string]int
}

type ruleWithExpsStack struct {
	rule   *rule
	estack []any
}

// nolint: structcheck,maligned
type parser struct {
	filename string
	pt       savepoint
	cur      current

	data []byte
	errs *errList

	depth   int
	recover bool
	debug   bool

	memoize bool
	// memoization table for the packrat algorithm:
	// map[offset in source] map[expression or rule] {value, match}
	memo map[int]map[any]resultTuple

	// rules table, maps the rule identifier to the rule node
	rules map[string]*rule
	// variables stack, map of label to value
	vstack []map[string]any
	// rule stack, allows identification of the current rule in errors
	rstack []*rule

	// parse fail
	maxFailPos            position
	maxFailExpected       []string
	maxFailInvertExpected bool

	// max number of expressions to be parsed
	maxExprCnt uint64
	// entrypoint for the parser
	entrypoint string

	allowInvalidUTF8 bool

	*Stats

	choiceNoMatch string
	// recovery expression stack, keeps track of the currently available recovery expression, these are traversed in reverse
	recoveryStack []map[string]any
}

// push a variable set on the vstack.
func (p *parser) pushV() { _ = "STUB: not implemented"; return }

// create new empty slot in the stack

// slice to 1 more

// get the last args set

// empty map, all good

// pop a variable set from the vstack.
func (p *parser) popV() {
	_ = "STUB: not implemented"
	// if the map is not empty, clear it
	return
}

// GC that map

// push a recovery expression with its labels to the recoveryStack
func (p *parser) pushRecovery(labels []string, expr any) { _ = "STUB: not implemented"; return }

// create new empty slot in the stack

// slice to 1 more

// pop a recovery expression from the recoveryStack
func (p *parser) popRecovery() {
	_ = "STUB: not implemented"
	// GC that map
	return
}

func (p *parser) print(prefix, s string) string { _ = "STUB: not implemented"; return "" }

func (p *parser) printIndent(mark string, s string) string { _ = "STUB: not implemented"; return "" }

func (p *parser) in(s string) string { _ = "STUB: not implemented"; return "" }

func (p *parser) out(s string) string { _ = "STUB: not implemented"; return "" }

func (p *parser) addErr(err error) { _ = "STUB: not implemented"; return }

func (p *parser) addErrAt(err error, pos position, expected []string) {
	_ = "STUB: not implemented"
	return
}

func (p *parser) failAt(fail bool, pos position, want string) {
	_ = "STUB: not implemented"
	// process fail if parsing fails and not inverted or parsing succeeds and invert is set
	return
}

// read advances the parser to the next rune.
func (p *parser) read() { _ = "STUB: not implemented"; return }

// see utf8.DecodeRune

// restore parser position to the savepoint pt.
func (p *parser) restore(pt savepoint) { _ = "STUB: not implemented"; return }

// Cloner is implemented by any value that has a Clone method, which returns a
// copy of the value. This is mainly used for types which are not passed by
// value (e.g map, slice, chan) or structs that contain such types.
//
// This is used in conjunction with the global state feature to create proper
// copies of the state to allow the parser to properly restore the state in
// the case of backtracking.
type Cloner interface {
	Clone() any
}

var statePool = &sync.Pool{
	New: func() any { return make(storeDict) },
}

func (sd storeDict) Discard() { _ = "STUB: not implemented"; return }

// clone and return parser current state.
func (p *parser) cloneState() storeDict { _ = "STUB: not implemented"; return *new(storeDict) }

// restore parser current state to the state storeDict.
// every restoreState should applied only one time for every cloned state
func (p *parser) restoreState(state storeDict) { _ = "STUB: not implemented"; return }

// get the slice of bytes from the savepoint start to the current position.
func (p *parser) sliceFrom(start savepoint) []byte { _ = "STUB: not implemented"; return nil }

func (p *parser) getMemoized(node any) (resultTuple, bool) {
	_ = "STUB: not implemented"
	return *new(resultTuple), false
}

func (p *parser) setMemoized(pt savepoint, node any, tuple resultTuple) {
	_ = "STUB: not implemented"
	return
}

func (p *parser) buildRulesTable(g *grammar) { _ = "STUB: not implemented"; return }

// nolint: gocyclo
func (p *parser) parse(g *grammar) (val any, err error) {
	_ = "STUB: not implemented"
	return *new(any), nil
}

// TODO : not super critical but this could be generated

// panic can be used in action code to stop parsing immediately
// and return the panic as an error.

// advance to first rune

// If parsing fails, but no errors have been recorded, the expected values
// for the farthest parser position are returned as error.

func listJoin(list []string, sep string, lastSep string) string {
	_ = "STUB: not implemented"
	return ""
}

func (p *parser) parseRuleRecursiveLeader(rule *rule) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (p *parser) parseRuleRecursiveNoLeader(rule *rule) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (p *parser) parseRuleMemoize(rule *rule) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (p *parser) parseRuleWrap(rule *rule) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (p *parser) parseRule(rule *rule) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (p *parser) parseExprWrap(expr any) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

// nolint: gocyclo
func (p *parser) parseExpr(expr any) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (p *parser) parseActionExpr(act *actionExpr) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (p *parser) parseAndCodeExpr(and *andCodeExpr) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (p *parser) parseAndExpr(and *andExpr) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (p *parser) parseAnyMatcher(any *anyMatcher) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

// EOF - see utf8.DecodeRune

// nolint: gocyclo
func (p *parser) parseCharClassMatcher(chr *charClassMatcher) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

// can't match EOF
// see utf8.DecodeRune

// try to match in the list of available chars

// try to match in the list of ranges

// try to match in the list of Unicode classes

func (p *parser) incChoiceAltCnt(ch *choiceExpr, altI int) { _ = "STUB: not implemented"; return }

// We increment altI by 1, so the keys do not start at 0

func (p *parser) parseChoiceExpr(ch *choiceExpr) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

// dummy assignment to prevent compile error if optimized

func (p *parser) parseLabeledExpr(lab *labeledExpr) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (p *parser) parseLitMatcher(lit *litMatcher) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (p *parser) parseNotCodeExpr(not *notCodeExpr) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (p *parser) parseNotExpr(not *notExpr) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (p *parser) parseOneOrMoreExpr(expr *oneOrMoreExpr) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

// did not match once, no match

func (p *parser) parseRecoveryExpr(recover *recoveryExpr) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (p *parser) parseRuleRefExpr(ref *ruleRefExpr) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (p *parser) parseSeqExpr(seq *seqExpr) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (p *parser) parseStateCodeExpr(state *stateCodeExpr) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (p *parser) parseThrowExpr(expr *throwExpr) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (p *parser) parseZeroOrMoreExpr(expr *zeroOrMoreExpr) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (p *parser) parseZeroOrOneExpr(expr *zeroOrOneExpr) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

// whether it matched or not, consider it a match
