// Simple program to generate variables with the static code for the builder
// based on real .go source files.
// This allows for easier modification of the static code.
package main

import (
	"os"
)

const (
	delimiter = "// IMPORTANT: All code below this line is added to the parser as static code"

	header = `// Code generated by static_code_generator with go generate; DO NOT EDIT.

package builder

var %s = ` + "`"

	footer = "`"

	eol = "\n"
)

func generateFile(source, dest, varname string) { _ = "STUB: not implemented"; return }

func main() {
	if len(os.Args) > 1 && os.Args[1] == "--" {
		os.Args = os.Args[2:]
	} else {
		os.Args = os.Args[1:]
	}
	if len(os.Args) < 3 {
		panic("not enough args")
	}
	generateFile(os.Args[0], os.Args[1], os.Args[2])
}
