// Code generated by pigeon; DO NOT EDIT.

package main

import (
	"errors"
	"io"
	"sync"
	"unicode"
)

var g = &grammar{
	rules: []*rule{
		{
			name: "Grammar",
			pos:  position{line: 5, col: 1, offset: 18},
			expr: &actionExpr{
				pos: position{line: 5, col: 11, offset: 30},
				run: (*parser).callonGrammar1,
				expr: &seqExpr{
					pos: position{line: 5, col: 11, offset: 30},
					exprs: []any{
						&ruleRefExpr{
							pos:  position{line: 5, col: 11, offset: 30},
							name: "__",
						},
						&labeledExpr{
							pos:   position{line: 5, col: 14, offset: 33},
							label: "initializer",
							expr: &zeroOrOneExpr{
								pos: position{line: 5, col: 28, offset: 47},
								expr: &seqExpr{
									pos: position{line: 5, col: 28, offset: 47},
									exprs: []any{
										&ruleRefExpr{
											pos:  position{line: 5, col: 28, offset: 47},
											name: "Initializer",
										},
										&ruleRefExpr{
											pos:  position{line: 5, col: 40, offset: 59},
											name: "__",
										},
									},
								},
							},
						},
						&labeledExpr{
							pos:   position{line: 5, col: 46, offset: 65},
							label: "rules",
							expr: &oneOrMoreExpr{
								pos: position{line: 5, col: 54, offset: 73},
								expr: &seqExpr{
									pos: position{line: 5, col: 54, offset: 73},
									exprs: []any{
										&ruleRefExpr{
											pos:  position{line: 5, col: 54, offset: 73},
											name: "Rule",
										},
										&ruleRefExpr{
											pos:  position{line: 5, col: 59, offset: 78},
											name: "__",
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Initializer",
			pos:  position{line: 24, col: 1, offset: 509},
			expr: &actionExpr{
				pos: position{line: 24, col: 15, offset: 525},
				run: (*parser).callonInitializer1,
				expr: &seqExpr{
					pos: position{line: 24, col: 15, offset: 525},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 24, col: 15, offset: 525},
							label: "code",
							expr: &ruleRefExpr{
								pos:  position{line: 24, col: 20, offset: 530},
								name: "CodeBlock",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 24, col: 30, offset: 540},
							name: "EOS",
						},
					},
				},
			},
		},
		{
			name: "Rule",
			pos:  position{line: 28, col: 1, offset: 570},
			expr: &actionExpr{
				pos: position{line: 28, col: 8, offset: 579},
				run: (*parser).callonRule1,
				expr: &seqExpr{
					pos: position{line: 28, col: 8, offset: 579},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 28, col: 8, offset: 579},
							label: "name",
							expr: &ruleRefExpr{
								pos:  position{line: 28, col: 13, offset: 584},
								name: "IdentifierName",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 28, col: 28, offset: 599},
							name: "__",
						},
						&labeledExpr{
							pos:   position{line: 28, col: 31, offset: 602},
							label: "display",
							expr: &zeroOrOneExpr{
								pos: position{line: 28, col: 41, offset: 612},
								expr: &seqExpr{
									pos: position{line: 28, col: 41, offset: 612},
									exprs: []any{
										&ruleRefExpr{
											pos:  position{line: 28, col: 41, offset: 612},
											name: "StringLiteral",
										},
										&ruleRefExpr{
											pos:  position{line: 28, col: 55, offset: 626},
											name: "__",
										},
									},
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 28, col: 61, offset: 632},
							name: "RuleDefOp",
						},
						&ruleRefExpr{
							pos:  position{line: 28, col: 71, offset: 642},
							name: "__",
						},
						&labeledExpr{
							pos:   position{line: 28, col: 74, offset: 645},
							label: "expr",
							expr: &ruleRefExpr{
								pos:  position{line: 28, col: 79, offset: 650},
								name: "Expression",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 28, col: 90, offset: 661},
							name: "EOS",
						},
					},
				},
			},
		},
		{
			name: "Expression",
			pos:  position{line: 41, col: 1, offset: 943},
			expr: &ruleRefExpr{
				pos:  position{line: 41, col: 14, offset: 958},
				name: "ChoiceExpr",
			},
		},
		{
			name: "ChoiceExpr",
			pos:  position{line: 43, col: 1, offset: 970},
			expr: &actionExpr{
				pos: position{line: 43, col: 14, offset: 985},
				run: (*parser).callonChoiceExpr1,
				expr: &seqExpr{
					pos: position{line: 43, col: 14, offset: 985},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 43, col: 14, offset: 985},
							label: "first",
							expr: &ruleRefExpr{
								pos:  position{line: 43, col: 20, offset: 991},
								name: "ActionExpr",
							},
						},
						&labeledExpr{
							pos:   position{line: 43, col: 31, offset: 1002},
							label: "rest",
							expr: &zeroOrMoreExpr{
								pos: position{line: 43, col: 38, offset: 1009},
								expr: &seqExpr{
									pos: position{line: 43, col: 38, offset: 1009},
									exprs: []any{
										&ruleRefExpr{
											pos:  position{line: 43, col: 38, offset: 1009},
											name: "__",
										},
										&litMatcher{
											pos:        position{line: 43, col: 41, offset: 1012},
											val:        "/",
											ignoreCase: false,
											want:       "\"/\"",
										},
										&ruleRefExpr{
											pos:  position{line: 43, col: 45, offset: 1016},
											name: "__",
										},
										&ruleRefExpr{
											pos:  position{line: 43, col: 48, offset: 1019},
											name: "ActionExpr",
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "ActionExpr",
			pos:  position{line: 58, col: 1, offset: 1414},
			expr: &actionExpr{
				pos: position{line: 58, col: 14, offset: 1429},
				run: (*parser).callonActionExpr1,
				expr: &seqExpr{
					pos: position{line: 58, col: 14, offset: 1429},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 58, col: 14, offset: 1429},
							label: "expr",
							expr: &ruleRefExpr{
								pos:  position{line: 58, col: 19, offset: 1434},
								name: "SeqExpr",
							},
						},
						&labeledExpr{
							pos:   position{line: 58, col: 27, offset: 1442},
							label: "code",
							expr: &zeroOrOneExpr{
								pos: position{line: 58, col: 34, offset: 1449},
								expr: &seqExpr{
									pos: position{line: 58, col: 34, offset: 1449},
									exprs: []any{
										&ruleRefExpr{
											pos:  position{line: 58, col: 34, offset: 1449},
											name: "__",
										},
										&ruleRefExpr{
											pos:  position{line: 58, col: 37, offset: 1452},
											name: "CodeBlock",
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "SeqExpr",
			pos:  position{line: 72, col: 1, offset: 1716},
			expr: &actionExpr{
				pos: position{line: 72, col: 11, offset: 1728},
				run: (*parser).callonSeqExpr1,
				expr: &seqExpr{
					pos: position{line: 72, col: 11, offset: 1728},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 72, col: 11, offset: 1728},
							label: "first",
							expr: &ruleRefExpr{
								pos:  position{line: 72, col: 17, offset: 1734},
								name: "LabeledExpr",
							},
						},
						&labeledExpr{
							pos:   position{line: 72, col: 29, offset: 1746},
							label: "rest",
							expr: &zeroOrMoreExpr{
								pos: position{line: 72, col: 36, offset: 1753},
								expr: &seqExpr{
									pos: position{line: 72, col: 36, offset: 1753},
									exprs: []any{
										&ruleRefExpr{
											pos:  position{line: 72, col: 36, offset: 1753},
											name: "__",
										},
										&ruleRefExpr{
											pos:  position{line: 72, col: 39, offset: 1756},
											name: "LabeledExpr",
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "LabeledExpr",
			pos:  position{line: 85, col: 1, offset: 2097},
			expr: &choiceExpr{
				pos: position{line: 85, col: 15, offset: 2113},
				alternatives: []any{
					&actionExpr{
						pos: position{line: 85, col: 15, offset: 2113},
						run: (*parser).callonLabeledExpr2,
						expr: &seqExpr{
							pos: position{line: 85, col: 15, offset: 2113},
							exprs: []any{
								&labeledExpr{
									pos:   position{line: 85, col: 15, offset: 2113},
									label: "label",
									expr: &ruleRefExpr{
										pos:  position{line: 85, col: 21, offset: 2119},
										name: "Identifier",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 85, col: 32, offset: 2130},
									name: "__",
								},
								&litMatcher{
									pos:        position{line: 85, col: 35, offset: 2133},
									val:        ":",
									ignoreCase: false,
									want:       "\":\"",
								},
								&ruleRefExpr{
									pos:  position{line: 85, col: 39, offset: 2137},
									name: "__",
								},
								&labeledExpr{
									pos:   position{line: 85, col: 42, offset: 2140},
									label: "expr",
									expr: &ruleRefExpr{
										pos:  position{line: 85, col: 47, offset: 2145},
										name: "PrefixedExpr",
									},
								},
							},
						},
					},
					&ruleRefExpr{
						pos:  position{line: 91, col: 5, offset: 2318},
						name: "PrefixedExpr",
					},
				},
			},
		},
		{
			name: "PrefixedExpr",
			pos:  position{line: 93, col: 1, offset: 2332},
			expr: &choiceExpr{
				pos: position{line: 93, col: 16, offset: 2349},
				alternatives: []any{
					&actionExpr{
						pos: position{line: 93, col: 16, offset: 2349},
						run: (*parser).callonPrefixedExpr2,
						expr: &seqExpr{
							pos: position{line: 93, col: 16, offset: 2349},
							exprs: []any{
								&labeledExpr{
									pos:   position{line: 93, col: 16, offset: 2349},
									label: "op",
									expr: &ruleRefExpr{
										pos:  position{line: 93, col: 19, offset: 2352},
										name: "PrefixedOp",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 93, col: 30, offset: 2363},
									name: "__",
								},
								&labeledExpr{
									pos:   position{line: 93, col: 33, offset: 2366},
									label: "expr",
									expr: &ruleRefExpr{
										pos:  position{line: 93, col: 38, offset: 2371},
										name: "SuffixedExpr",
									},
								},
							},
						},
					},
					&ruleRefExpr{
						pos:  position{line: 104, col: 5, offset: 2653},
						name: "SuffixedExpr",
					},
				},
			},
		},
		{
			name: "PrefixedOp",
			pos:  position{line: 106, col: 1, offset: 2667},
			expr: &actionExpr{
				pos: position{line: 106, col: 14, offset: 2682},
				run: (*parser).callonPrefixedOp1,
				expr: &choiceExpr{
					pos: position{line: 106, col: 16, offset: 2684},
					alternatives: []any{
						&litMatcher{
							pos:        position{line: 106, col: 16, offset: 2684},
							val:        "&",
							ignoreCase: false,
							want:       "\"&\"",
						},
						&litMatcher{
							pos:        position{line: 106, col: 22, offset: 2690},
							val:        "!",
							ignoreCase: false,
							want:       "\"!\"",
						},
					},
				},
			},
		},
		{
			name: "SuffixedExpr",
			pos:  position{line: 110, col: 1, offset: 2732},
			expr: &choiceExpr{
				pos: position{line: 110, col: 16, offset: 2749},
				alternatives: []any{
					&actionExpr{
						pos: position{line: 110, col: 16, offset: 2749},
						run: (*parser).callonSuffixedExpr2,
						expr: &seqExpr{
							pos: position{line: 110, col: 16, offset: 2749},
							exprs: []any{
								&labeledExpr{
									pos:   position{line: 110, col: 16, offset: 2749},
									label: "expr",
									expr: &ruleRefExpr{
										pos:  position{line: 110, col: 21, offset: 2754},
										name: "PrimaryExpr",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 110, col: 33, offset: 2766},
									name: "__",
								},
								&labeledExpr{
									pos:   position{line: 110, col: 36, offset: 2769},
									label: "op",
									expr: &ruleRefExpr{
										pos:  position{line: 110, col: 39, offset: 2772},
										name: "SuffixedOp",
									},
								},
							},
						},
					},
					&ruleRefExpr{
						pos:  position{line: 129, col: 5, offset: 3302},
						name: "PrimaryExpr",
					},
				},
			},
		},
		{
			name: "SuffixedOp",
			pos:  position{line: 131, col: 1, offset: 3316},
			expr: &actionExpr{
				pos: position{line: 131, col: 14, offset: 3331},
				run: (*parser).callonSuffixedOp1,
				expr: &choiceExpr{
					pos: position{line: 131, col: 16, offset: 3333},
					alternatives: []any{
						&litMatcher{
							pos:        position{line: 131, col: 16, offset: 3333},
							val:        "?",
							ignoreCase: false,
							want:       "\"?\"",
						},
						&litMatcher{
							pos:        position{line: 131, col: 22, offset: 3339},
							val:        "*",
							ignoreCase: false,
							want:       "\"*\"",
						},
						&litMatcher{
							pos:        position{line: 131, col: 28, offset: 3345},
							val:        "+",
							ignoreCase: false,
							want:       "\"+\"",
						},
					},
				},
			},
		},
		{
			name: "PrimaryExpr",
			pos:  position{line: 135, col: 1, offset: 3387},
			expr: &choiceExpr{
				pos: position{line: 135, col: 15, offset: 3403},
				alternatives: []any{
					&ruleRefExpr{
						pos:  position{line: 135, col: 15, offset: 3403},
						name: "LitMatcher",
					},
					&ruleRefExpr{
						pos:  position{line: 135, col: 28, offset: 3416},
						name: "CharClassMatcher",
					},
					&ruleRefExpr{
						pos:  position{line: 135, col: 47, offset: 3435},
						name: "AnyMatcher",
					},
					&ruleRefExpr{
						pos:  position{line: 135, col: 60, offset: 3448},
						name: "RuleRefExpr",
					},
					&ruleRefExpr{
						pos:  position{line: 135, col: 74, offset: 3462},
						name: "SemanticPredExpr",
					},
					&actionExpr{
						pos: position{line: 135, col: 93, offset: 3481},
						run: (*parser).callonPrimaryExpr7,
						expr: &seqExpr{
							pos: position{line: 135, col: 93, offset: 3481},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 135, col: 93, offset: 3481},
									val:        "(",
									ignoreCase: false,
									want:       "\"(\"",
								},
								&ruleRefExpr{
									pos:  position{line: 135, col: 97, offset: 3485},
									name: "__",
								},
								&labeledExpr{
									pos:   position{line: 135, col: 100, offset: 3488},
									label: "expr",
									expr: &ruleRefExpr{
										pos:  position{line: 135, col: 105, offset: 3493},
										name: "Expression",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 135, col: 116, offset: 3504},
									name: "__",
								},
								&litMatcher{
									pos:        position{line: 135, col: 119, offset: 3507},
									val:        ")",
									ignoreCase: false,
									want:       "\")\"",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "RuleRefExpr",
			pos:  position{line: 138, col: 1, offset: 3536},
			expr: &actionExpr{
				pos: position{line: 138, col: 15, offset: 3552},
				run: (*parser).callonRuleRefExpr1,
				expr: &seqExpr{
					pos: position{line: 138, col: 15, offset: 3552},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 138, col: 15, offset: 3552},
							label: "name",
							expr: &ruleRefExpr{
								pos:  position{line: 138, col: 20, offset: 3557},
								name: "IdentifierName",
							},
						},
						&notExpr{
							pos: position{line: 138, col: 35, offset: 3572},
							expr: &seqExpr{
								pos: position{line: 138, col: 38, offset: 3575},
								exprs: []any{
									&ruleRefExpr{
										pos:  position{line: 138, col: 38, offset: 3575},
										name: "__",
									},
									&zeroOrOneExpr{
										pos: position{line: 138, col: 43, offset: 3580},
										expr: &seqExpr{
											pos: position{line: 138, col: 43, offset: 3580},
											exprs: []any{
												&ruleRefExpr{
													pos:  position{line: 138, col: 43, offset: 3580},
													name: "StringLiteral",
												},
												&ruleRefExpr{
													pos:  position{line: 138, col: 57, offset: 3594},
													name: "__",
												},
											},
										},
									},
									&ruleRefExpr{
										pos:  position{line: 138, col: 63, offset: 3600},
										name: "RuleDefOp",
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "SemanticPredExpr",
			pos:  position{line: 143, col: 1, offset: 3716},
			expr: &actionExpr{
				pos: position{line: 143, col: 20, offset: 3737},
				run: (*parser).callonSemanticPredExpr1,
				expr: &seqExpr{
					pos: position{line: 143, col: 20, offset: 3737},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 143, col: 20, offset: 3737},
							label: "op",
							expr: &ruleRefExpr{
								pos:  position{line: 143, col: 23, offset: 3740},
								name: "SemanticPredOp",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 143, col: 38, offset: 3755},
							name: "__",
						},
						&labeledExpr{
							pos:   position{line: 143, col: 41, offset: 3758},
							label: "code",
							expr: &ruleRefExpr{
								pos:  position{line: 143, col: 46, offset: 3763},
								name: "CodeBlock",
							},
						},
					},
				},
			},
		},
		{
			name: "SemanticPredOp",
			pos:  position{line: 154, col: 1, offset: 4040},
			expr: &actionExpr{
				pos: position{line: 154, col: 18, offset: 4059},
				run: (*parser).callonSemanticPredOp1,
				expr: &choiceExpr{
					pos: position{line: 154, col: 20, offset: 4061},
					alternatives: []any{
						&litMatcher{
							pos:        position{line: 154, col: 20, offset: 4061},
							val:        "&",
							ignoreCase: false,
							want:       "\"&\"",
						},
						&litMatcher{
							pos:        position{line: 154, col: 26, offset: 4067},
							val:        "!",
							ignoreCase: false,
							want:       "\"!\"",
						},
					},
				},
			},
		},
		{
			name: "RuleDefOp",
			pos:  position{line: 158, col: 1, offset: 4109},
			expr: &choiceExpr{
				pos: position{line: 158, col: 13, offset: 4123},
				alternatives: []any{
					&litMatcher{
						pos:        position{line: 158, col: 13, offset: 4123},
						val:        "=",
						ignoreCase: false,
						want:       "\"=\"",
					},
					&litMatcher{
						pos:        position{line: 158, col: 19, offset: 4129},
						val:        "<-",
						ignoreCase: false,
						want:       "\"<-\"",
					},
					&litMatcher{
						pos:        position{line: 158, col: 26, offset: 4136},
						val:        "←",
						ignoreCase: false,
						want:       "\"←\"",
					},
					&litMatcher{
						pos:        position{line: 158, col: 37, offset: 4147},
						val:        "⟵",
						ignoreCase: false,
						want:       "\"⟵\"",
					},
				},
			},
		},
		{
			name: "SourceChar",
			pos:  position{line: 160, col: 1, offset: 4157},
			expr: &anyMatcher{
				line: 160, col: 14, offset: 4172,
			},
		},
		{
			name: "Comment",
			pos:  position{line: 161, col: 1, offset: 4174},
			expr: &choiceExpr{
				pos: position{line: 161, col: 11, offset: 4186},
				alternatives: []any{
					&ruleRefExpr{
						pos:  position{line: 161, col: 11, offset: 4186},
						name: "MultiLineComment",
					},
					&ruleRefExpr{
						pos:  position{line: 161, col: 30, offset: 4205},
						name: "SingleLineComment",
					},
				},
			},
		},
		{
			name: "MultiLineComment",
			pos:  position{line: 162, col: 1, offset: 4223},
			expr: &seqExpr{
				pos: position{line: 162, col: 20, offset: 4244},
				exprs: []any{
					&litMatcher{
						pos:        position{line: 162, col: 20, offset: 4244},
						val:        "/*",
						ignoreCase: false,
						want:       "\"/*\"",
					},
					&zeroOrMoreExpr{
						pos: position{line: 162, col: 27, offset: 4251},
						expr: &seqExpr{
							pos: position{line: 162, col: 27, offset: 4251},
							exprs: []any{
								&notExpr{
									pos: position{line: 162, col: 27, offset: 4251},
									expr: &litMatcher{
										pos:        position{line: 162, col: 28, offset: 4252},
										val:        "*/",
										ignoreCase: false,
										want:       "\"*/\"",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 162, col: 33, offset: 4257},
									name: "SourceChar",
								},
							},
						},
					},
					&litMatcher{
						pos:        position{line: 162, col: 47, offset: 4271},
						val:        "*/",
						ignoreCase: false,
						want:       "\"*/\"",
					},
				},
			},
		},
		{
			name: "MultiLineCommentNoLineTerminator",
			pos:  position{line: 163, col: 1, offset: 4276},
			expr: &seqExpr{
				pos: position{line: 163, col: 36, offset: 4313},
				exprs: []any{
					&litMatcher{
						pos:        position{line: 163, col: 36, offset: 4313},
						val:        "/*",
						ignoreCase: false,
						want:       "\"/*\"",
					},
					&zeroOrMoreExpr{
						pos: position{line: 163, col: 43, offset: 4320},
						expr: &seqExpr{
							pos: position{line: 163, col: 43, offset: 4320},
							exprs: []any{
								&notExpr{
									pos: position{line: 163, col: 43, offset: 4320},
									expr: &choiceExpr{
										pos: position{line: 163, col: 46, offset: 4323},
										alternatives: []any{
											&litMatcher{
												pos:        position{line: 163, col: 46, offset: 4323},
												val:        "*/",
												ignoreCase: false,
												want:       "\"*/\"",
											},
											&ruleRefExpr{
												pos:  position{line: 163, col: 53, offset: 4330},
												name: "EOL",
											},
										},
									},
								},
								&ruleRefExpr{
									pos:  position{line: 163, col: 59, offset: 4336},
									name: "SourceChar",
								},
							},
						},
					},
					&litMatcher{
						pos:        position{line: 163, col: 73, offset: 4350},
						val:        "*/",
						ignoreCase: false,
						want:       "\"*/\"",
					},
				},
			},
		},
		{
			name: "SingleLineComment",
			pos:  position{line: 164, col: 1, offset: 4355},
			expr: &seqExpr{
				pos: position{line: 164, col: 21, offset: 4377},
				exprs: []any{
					&litMatcher{
						pos:        position{line: 164, col: 21, offset: 4377},
						val:        "//",
						ignoreCase: false,
						want:       "\"//\"",
					},
					&zeroOrMoreExpr{
						pos: position{line: 164, col: 28, offset: 4384},
						expr: &seqExpr{
							pos: position{line: 164, col: 28, offset: 4384},
							exprs: []any{
								&notExpr{
									pos: position{line: 164, col: 28, offset: 4384},
									expr: &ruleRefExpr{
										pos:  position{line: 164, col: 29, offset: 4385},
										name: "EOL",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 164, col: 33, offset: 4389},
									name: "SourceChar",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Identifier",
			pos:  position{line: 166, col: 1, offset: 4404},
			expr: &ruleRefExpr{
				pos:  position{line: 166, col: 14, offset: 4419},
				name: "IdentifierName",
			},
		},
		{
			name: "IdentifierName",
			pos:  position{line: 167, col: 1, offset: 4434},
			expr: &actionExpr{
				pos: position{line: 167, col: 18, offset: 4453},
				run: (*parser).callonIdentifierName1,
				expr: &seqExpr{
					pos: position{line: 167, col: 18, offset: 4453},
					exprs: []any{
						&ruleRefExpr{
							pos:  position{line: 167, col: 18, offset: 4453},
							name: "IdentifierStart",
						},
						&zeroOrMoreExpr{
							pos: position{line: 167, col: 34, offset: 4469},
							expr: &ruleRefExpr{
								pos:  position{line: 167, col: 34, offset: 4469},
								name: "IdentifierPart",
							},
						},
					},
				},
			},
		},
		{
			name: "IdentifierStart",
			pos:  position{line: 170, col: 1, offset: 4551},
			expr: &charClassMatcher{
				pos:        position{line: 170, col: 19, offset: 4571},
				val:        "[a-z_]i",
				chars:      []rune{'_'},
				ranges:     []rune{'a', 'z'},
				ignoreCase: true,
				inverted:   false,
			},
		},
		{
			name: "IdentifierPart",
			pos:  position{line: 171, col: 1, offset: 4579},
			expr: &choiceExpr{
				pos: position{line: 171, col: 18, offset: 4598},
				alternatives: []any{
					&ruleRefExpr{
						pos:  position{line: 171, col: 18, offset: 4598},
						name: "IdentifierStart",
					},
					&charClassMatcher{
						pos:        position{line: 171, col: 36, offset: 4616},
						val:        "[0-9]",
						ranges:     []rune{'0', '9'},
						ignoreCase: false,
						inverted:   false,
					},
				},
			},
		},
		{
			name: "LitMatcher",
			pos:  position{line: 173, col: 1, offset: 4623},
			expr: &actionExpr{
				pos: position{line: 173, col: 14, offset: 4638},
				run: (*parser).callonLitMatcher1,
				expr: &seqExpr{
					pos: position{line: 173, col: 14, offset: 4638},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 173, col: 14, offset: 4638},
							label: "lit",
							expr: &ruleRefExpr{
								pos:  position{line: 173, col: 18, offset: 4642},
								name: "StringLiteral",
							},
						},
						&labeledExpr{
							pos:   position{line: 173, col: 32, offset: 4656},
							label: "ignore",
							expr: &zeroOrOneExpr{
								pos: position{line: 173, col: 39, offset: 4663},
								expr: &litMatcher{
									pos:        position{line: 173, col: 39, offset: 4663},
									val:        "i",
									ignoreCase: false,
									want:       "\"i\"",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "StringLiteral",
			pos:  position{line: 183, col: 1, offset: 4889},
			expr: &actionExpr{
				pos: position{line: 183, col: 17, offset: 4907},
				run: (*parser).callonStringLiteral1,
				expr: &choiceExpr{
					pos: position{line: 183, col: 19, offset: 4909},
					alternatives: []any{
						&seqExpr{
							pos: position{line: 183, col: 19, offset: 4909},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 183, col: 19, offset: 4909},
									val:        "\"",
									ignoreCase: false,
									want:       "\"\\\"\"",
								},
								&zeroOrMoreExpr{
									pos: position{line: 183, col: 23, offset: 4913},
									expr: &ruleRefExpr{
										pos:  position{line: 183, col: 23, offset: 4913},
										name: "DoubleStringChar",
									},
								},
								&litMatcher{
									pos:        position{line: 183, col: 41, offset: 4931},
									val:        "\"",
									ignoreCase: false,
									want:       "\"\\\"\"",
								},
							},
						},
						&seqExpr{
							pos: position{line: 183, col: 47, offset: 4937},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 183, col: 47, offset: 4937},
									val:        "'",
									ignoreCase: false,
									want:       "\"'\"",
								},
								&ruleRefExpr{
									pos:  position{line: 183, col: 51, offset: 4941},
									name: "SingleStringChar",
								},
								&litMatcher{
									pos:        position{line: 183, col: 68, offset: 4958},
									val:        "'",
									ignoreCase: false,
									want:       "\"'\"",
								},
							},
						},
						&seqExpr{
							pos: position{line: 183, col: 74, offset: 4964},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 183, col: 74, offset: 4964},
									val:        "`",
									ignoreCase: false,
									want:       "\"`\"",
								},
								&zeroOrMoreExpr{
									pos: position{line: 183, col: 78, offset: 4968},
									expr: &ruleRefExpr{
										pos:  position{line: 183, col: 78, offset: 4968},
										name: "RawStringChar",
									},
								},
								&litMatcher{
									pos:        position{line: 183, col: 93, offset: 4983},
									val:        "`",
									ignoreCase: false,
									want:       "\"`\"",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "DoubleStringChar",
			pos:  position{line: 186, col: 1, offset: 5054},
			expr: &choiceExpr{
				pos: position{line: 186, col: 20, offset: 5075},
				alternatives: []any{
					&seqExpr{
						pos: position{line: 186, col: 20, offset: 5075},
						exprs: []any{
							&notExpr{
								pos: position{line: 186, col: 20, offset: 5075},
								expr: &choiceExpr{
									pos: position{line: 186, col: 23, offset: 5078},
									alternatives: []any{
										&litMatcher{
											pos:        position{line: 186, col: 23, offset: 5078},
											val:        "\"",
											ignoreCase: false,
											want:       "\"\\\"\"",
										},
										&litMatcher{
											pos:        position{line: 186, col: 29, offset: 5084},
											val:        "\\",
											ignoreCase: false,
											want:       "\"\\\\\"",
										},
										&ruleRefExpr{
											pos:  position{line: 186, col: 36, offset: 5091},
											name: "EOL",
										},
									},
								},
							},
							&ruleRefExpr{
								pos:  position{line: 186, col: 42, offset: 5097},
								name: "SourceChar",
							},
						},
					},
					&seqExpr{
						pos: position{line: 186, col: 55, offset: 5110},
						exprs: []any{
							&litMatcher{
								pos:        position{line: 186, col: 55, offset: 5110},
								val:        "\\",
								ignoreCase: false,
								want:       "\"\\\\\"",
							},
							&ruleRefExpr{
								pos:  position{line: 186, col: 60, offset: 5115},
								name: "DoubleStringEscape",
							},
						},
					},
				},
			},
		},
		{
			name: "SingleStringChar",
			pos:  position{line: 187, col: 1, offset: 5134},
			expr: &choiceExpr{
				pos: position{line: 187, col: 20, offset: 5155},
				alternatives: []any{
					&seqExpr{
						pos: position{line: 187, col: 20, offset: 5155},
						exprs: []any{
							&notExpr{
								pos: position{line: 187, col: 20, offset: 5155},
								expr: &choiceExpr{
									pos: position{line: 187, col: 23, offset: 5158},
									alternatives: []any{
										&litMatcher{
											pos:        position{line: 187, col: 23, offset: 5158},
											val:        "'",
											ignoreCase: false,
											want:       "\"'\"",
										},
										&litMatcher{
											pos:        position{line: 187, col: 29, offset: 5164},
											val:        "\\",
											ignoreCase: false,
											want:       "\"\\\\\"",
										},
										&ruleRefExpr{
											pos:  position{line: 187, col: 36, offset: 5171},
											name: "EOL",
										},
									},
								},
							},
							&ruleRefExpr{
								pos:  position{line: 187, col: 42, offset: 5177},
								name: "SourceChar",
							},
						},
					},
					&seqExpr{
						pos: position{line: 187, col: 55, offset: 5190},
						exprs: []any{
							&litMatcher{
								pos:        position{line: 187, col: 55, offset: 5190},
								val:        "\\",
								ignoreCase: false,
								want:       "\"\\\\\"",
							},
							&ruleRefExpr{
								pos:  position{line: 187, col: 60, offset: 5195},
								name: "SingleStringEscape",
							},
						},
					},
				},
			},
		},
		{
			name: "RawStringChar",
			pos:  position{line: 188, col: 1, offset: 5214},
			expr: &seqExpr{
				pos: position{line: 188, col: 17, offset: 5232},
				exprs: []any{
					&notExpr{
						pos: position{line: 188, col: 17, offset: 5232},
						expr: &litMatcher{
							pos:        position{line: 188, col: 18, offset: 5233},
							val:        "`",
							ignoreCase: false,
							want:       "\"`\"",
						},
					},
					&ruleRefExpr{
						pos:  position{line: 188, col: 22, offset: 5237},
						name: "SourceChar",
					},
				},
			},
		},
		{
			name: "DoubleStringEscape",
			pos:  position{line: 190, col: 1, offset: 5249},
			expr: &choiceExpr{
				pos: position{line: 190, col: 22, offset: 5272},
				alternatives: []any{
					&litMatcher{
						pos:        position{line: 190, col: 22, offset: 5272},
						val:        "\"",
						ignoreCase: false,
						want:       "\"\\\"\"",
					},
					&ruleRefExpr{
						pos:  position{line: 190, col: 28, offset: 5278},
						name: "CommonEscapeSequence",
					},
				},
			},
		},
		{
			name: "SingleStringEscape",
			pos:  position{line: 191, col: 1, offset: 5299},
			expr: &choiceExpr{
				pos: position{line: 191, col: 22, offset: 5322},
				alternatives: []any{
					&litMatcher{
						pos:        position{line: 191, col: 22, offset: 5322},
						val:        "'",
						ignoreCase: false,
						want:       "\"'\"",
					},
					&ruleRefExpr{
						pos:  position{line: 191, col: 28, offset: 5328},
						name: "CommonEscapeSequence",
					},
				},
			},
		},
		{
			name: "CommonEscapeSequence",
			pos:  position{line: 193, col: 1, offset: 5350},
			expr: &choiceExpr{
				pos: position{line: 193, col: 24, offset: 5375},
				alternatives: []any{
					&ruleRefExpr{
						pos:  position{line: 193, col: 24, offset: 5375},
						name: "SingleCharEscape",
					},
					&ruleRefExpr{
						pos:  position{line: 193, col: 43, offset: 5394},
						name: "OctalEscape",
					},
					&ruleRefExpr{
						pos:  position{line: 193, col: 57, offset: 5408},
						name: "HexEscape",
					},
					&ruleRefExpr{
						pos:  position{line: 193, col: 69, offset: 5420},
						name: "LongUnicodeEscape",
					},
					&ruleRefExpr{
						pos:  position{line: 193, col: 89, offset: 5440},
						name: "ShortUnicodeEscape",
					},
				},
			},
		},
		{
			name: "SingleCharEscape",
			pos:  position{line: 194, col: 1, offset: 5459},
			expr: &choiceExpr{
				pos: position{line: 194, col: 20, offset: 5480},
				alternatives: []any{
					&litMatcher{
						pos:        position{line: 194, col: 20, offset: 5480},
						val:        "a",
						ignoreCase: false,
						want:       "\"a\"",
					},
					&litMatcher{
						pos:        position{line: 194, col: 26, offset: 5486},
						val:        "b",
						ignoreCase: false,
						want:       "\"b\"",
					},
					&litMatcher{
						pos:        position{line: 194, col: 32, offset: 5492},
						val:        "n",
						ignoreCase: false,
						want:       "\"n\"",
					},
					&litMatcher{
						pos:        position{line: 194, col: 38, offset: 5498},
						val:        "f",
						ignoreCase: false,
						want:       "\"f\"",
					},
					&litMatcher{
						pos:        position{line: 194, col: 44, offset: 5504},
						val:        "r",
						ignoreCase: false,
						want:       "\"r\"",
					},
					&litMatcher{
						pos:        position{line: 194, col: 50, offset: 5510},
						val:        "t",
						ignoreCase: false,
						want:       "\"t\"",
					},
					&litMatcher{
						pos:        position{line: 194, col: 56, offset: 5516},
						val:        "v",
						ignoreCase: false,
						want:       "\"v\"",
					},
					&litMatcher{
						pos:        position{line: 194, col: 62, offset: 5522},
						val:        "\\",
						ignoreCase: false,
						want:       "\"\\\\\"",
					},
				},
			},
		},
		{
			name: "OctalEscape",
			pos:  position{line: 195, col: 1, offset: 5527},
			expr: &seqExpr{
				pos: position{line: 195, col: 15, offset: 5543},
				exprs: []any{
					&ruleRefExpr{
						pos:  position{line: 195, col: 15, offset: 5543},
						name: "OctalDigit",
					},
					&ruleRefExpr{
						pos:  position{line: 195, col: 26, offset: 5554},
						name: "OctalDigit",
					},
					&ruleRefExpr{
						pos:  position{line: 195, col: 37, offset: 5565},
						name: "OctalDigit",
					},
				},
			},
		},
		{
			name: "HexEscape",
			pos:  position{line: 196, col: 1, offset: 5576},
			expr: &seqExpr{
				pos: position{line: 196, col: 13, offset: 5590},
				exprs: []any{
					&litMatcher{
						pos:        position{line: 196, col: 13, offset: 5590},
						val:        "x",
						ignoreCase: false,
						want:       "\"x\"",
					},
					&ruleRefExpr{
						pos:  position{line: 196, col: 17, offset: 5594},
						name: "HexDigit",
					},
					&ruleRefExpr{
						pos:  position{line: 196, col: 26, offset: 5603},
						name: "HexDigit",
					},
				},
			},
		},
		{
			name: "LongUnicodeEscape",
			pos:  position{line: 197, col: 1, offset: 5612},
			expr: &seqExpr{
				pos: position{line: 197, col: 21, offset: 5634},
				exprs: []any{
					&litMatcher{
						pos:        position{line: 197, col: 21, offset: 5634},
						val:        "U",
						ignoreCase: false,
						want:       "\"U\"",
					},
					&ruleRefExpr{
						pos:  position{line: 197, col: 25, offset: 5638},
						name: "HexDigit",
					},
					&ruleRefExpr{
						pos:  position{line: 197, col: 34, offset: 5647},
						name: "HexDigit",
					},
					&ruleRefExpr{
						pos:  position{line: 197, col: 43, offset: 5656},
						name: "HexDigit",
					},
					&ruleRefExpr{
						pos:  position{line: 197, col: 52, offset: 5665},
						name: "HexDigit",
					},
					&ruleRefExpr{
						pos:  position{line: 197, col: 61, offset: 5674},
						name: "HexDigit",
					},
					&ruleRefExpr{
						pos:  position{line: 197, col: 70, offset: 5683},
						name: "HexDigit",
					},
					&ruleRefExpr{
						pos:  position{line: 197, col: 79, offset: 5692},
						name: "HexDigit",
					},
					&ruleRefExpr{
						pos:  position{line: 197, col: 88, offset: 5701},
						name: "HexDigit",
					},
				},
			},
		},
		{
			name: "ShortUnicodeEscape",
			pos:  position{line: 198, col: 1, offset: 5710},
			expr: &seqExpr{
				pos: position{line: 198, col: 22, offset: 5733},
				exprs: []any{
					&litMatcher{
						pos:        position{line: 198, col: 22, offset: 5733},
						val:        "u",
						ignoreCase: false,
						want:       "\"u\"",
					},
					&ruleRefExpr{
						pos:  position{line: 198, col: 26, offset: 5737},
						name: "HexDigit",
					},
					&ruleRefExpr{
						pos:  position{line: 198, col: 35, offset: 5746},
						name: "HexDigit",
					},
					&ruleRefExpr{
						pos:  position{line: 198, col: 44, offset: 5755},
						name: "HexDigit",
					},
					&ruleRefExpr{
						pos:  position{line: 198, col: 53, offset: 5764},
						name: "HexDigit",
					},
				},
			},
		},
		{
			name: "OctalDigit",
			pos:  position{line: 200, col: 1, offset: 5774},
			expr: &charClassMatcher{
				pos:        position{line: 200, col: 14, offset: 5789},
				val:        "[0-7]",
				ranges:     []rune{'0', '7'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "DecimalDigit",
			pos:  position{line: 201, col: 1, offset: 5795},
			expr: &charClassMatcher{
				pos:        position{line: 201, col: 16, offset: 5812},
				val:        "[0-9]",
				ranges:     []rune{'0', '9'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "HexDigit",
			pos:  position{line: 202, col: 1, offset: 5818},
			expr: &charClassMatcher{
				pos:        position{line: 202, col: 12, offset: 5831},
				val:        "[0-9a-f]i",
				ranges:     []rune{'0', '9', 'a', 'f'},
				ignoreCase: true,
				inverted:   false,
			},
		},
		{
			name: "CharClassMatcher",
			pos:  position{line: 204, col: 1, offset: 5842},
			expr: &actionExpr{
				pos: position{line: 204, col: 20, offset: 5863},
				run: (*parser).callonCharClassMatcher1,
				expr: &seqExpr{
					pos: position{line: 204, col: 20, offset: 5863},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 204, col: 20, offset: 5863},
							val:        "[",
							ignoreCase: false,
							want:       "\"[\"",
						},
						&zeroOrMoreExpr{
							pos: position{line: 204, col: 26, offset: 5869},
							expr: &choiceExpr{
								pos: position{line: 204, col: 26, offset: 5869},
								alternatives: []any{
									&ruleRefExpr{
										pos:  position{line: 204, col: 26, offset: 5869},
										name: "ClassCharRange",
									},
									&ruleRefExpr{
										pos:  position{line: 204, col: 43, offset: 5886},
										name: "ClassChar",
									},
									&seqExpr{
										pos: position{line: 204, col: 55, offset: 5898},
										exprs: []any{
											&litMatcher{
												pos:        position{line: 204, col: 55, offset: 5898},
												val:        "\\",
												ignoreCase: false,
												want:       "\"\\\\\"",
											},
											&ruleRefExpr{
												pos:  position{line: 204, col: 60, offset: 5903},
												name: "UnicodeClassEscape",
											},
										},
									},
								},
							},
						},
						&litMatcher{
							pos:        position{line: 204, col: 82, offset: 5925},
							val:        "]",
							ignoreCase: false,
							want:       "\"]\"",
						},
						&zeroOrOneExpr{
							pos: position{line: 204, col: 86, offset: 5929},
							expr: &litMatcher{
								pos:        position{line: 204, col: 86, offset: 5929},
								val:        "i",
								ignoreCase: false,
								want:       "\"i\"",
							},
						},
					},
				},
			},
		},
		{
			name: "ClassCharRange",
			pos:  position{line: 209, col: 1, offset: 6034},
			expr: &seqExpr{
				pos: position{line: 209, col: 18, offset: 6053},
				exprs: []any{
					&ruleRefExpr{
						pos:  position{line: 209, col: 18, offset: 6053},
						name: "ClassChar",
					},
					&litMatcher{
						pos:        position{line: 209, col: 28, offset: 6063},
						val:        "-",
						ignoreCase: false,
						want:       "\"-\"",
					},
					&ruleRefExpr{
						pos:  position{line: 209, col: 32, offset: 6067},
						name: "ClassChar",
					},
				},
			},
		},
		{
			name: "ClassChar",
			pos:  position{line: 210, col: 1, offset: 6077},
			expr: &choiceExpr{
				pos: position{line: 210, col: 13, offset: 6091},
				alternatives: []any{
					&seqExpr{
						pos: position{line: 210, col: 13, offset: 6091},
						exprs: []any{
							&notExpr{
								pos: position{line: 210, col: 13, offset: 6091},
								expr: &choiceExpr{
									pos: position{line: 210, col: 16, offset: 6094},
									alternatives: []any{
										&litMatcher{
											pos:        position{line: 210, col: 16, offset: 6094},
											val:        "]",
											ignoreCase: false,
											want:       "\"]\"",
										},
										&litMatcher{
											pos:        position{line: 210, col: 22, offset: 6100},
											val:        "\\",
											ignoreCase: false,
											want:       "\"\\\\\"",
										},
										&ruleRefExpr{
											pos:  position{line: 210, col: 29, offset: 6107},
											name: "EOL",
										},
									},
								},
							},
							&ruleRefExpr{
								pos:  position{line: 210, col: 35, offset: 6113},
								name: "SourceChar",
							},
						},
					},
					&seqExpr{
						pos: position{line: 210, col: 48, offset: 6126},
						exprs: []any{
							&litMatcher{
								pos:        position{line: 210, col: 48, offset: 6126},
								val:        "\\",
								ignoreCase: false,
								want:       "\"\\\\\"",
							},
							&ruleRefExpr{
								pos:  position{line: 210, col: 53, offset: 6131},
								name: "CharClassEscape",
							},
						},
					},
				},
			},
		},
		{
			name: "CharClassEscape",
			pos:  position{line: 211, col: 1, offset: 6147},
			expr: &choiceExpr{
				pos: position{line: 211, col: 19, offset: 6167},
				alternatives: []any{
					&litMatcher{
						pos:        position{line: 211, col: 19, offset: 6167},
						val:        "]",
						ignoreCase: false,
						want:       "\"]\"",
					},
					&ruleRefExpr{
						pos:  position{line: 211, col: 25, offset: 6173},
						name: "CommonEscapeSequence",
					},
				},
			},
		},
		{
			name: "UnicodeClassEscape",
			pos:  position{line: 213, col: 1, offset: 6195},
			expr: &seqExpr{
				pos: position{line: 213, col: 22, offset: 6218},
				exprs: []any{
					&litMatcher{
						pos:        position{line: 213, col: 22, offset: 6218},
						val:        "p",
						ignoreCase: false,
						want:       "\"p\"",
					},
					&choiceExpr{
						pos: position{line: 213, col: 28, offset: 6224},
						alternatives: []any{
							&ruleRefExpr{
								pos:  position{line: 213, col: 28, offset: 6224},
								name: "SingleCharUnicodeClass",
							},
							&seqExpr{
								pos: position{line: 213, col: 53, offset: 6249},
								exprs: []any{
									&litMatcher{
										pos:        position{line: 213, col: 53, offset: 6249},
										val:        "{",
										ignoreCase: false,
										want:       "\"{\"",
									},
									&ruleRefExpr{
										pos:  position{line: 213, col: 57, offset: 6253},
										name: "UnicodeClass",
									},
									&litMatcher{
										pos:        position{line: 213, col: 70, offset: 6266},
										val:        "}",
										ignoreCase: false,
										want:       "\"}\"",
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "SingleCharUnicodeClass",
			pos:  position{line: 214, col: 1, offset: 6272},
			expr: &charClassMatcher{
				pos:        position{line: 214, col: 26, offset: 6299},
				val:        "[LMNCPZS]",
				chars:      []rune{'L', 'M', 'N', 'C', 'P', 'Z', 'S'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "UnicodeClass",
			pos:  position{line: 215, col: 1, offset: 6309},
			expr: &oneOrMoreExpr{
				pos: position{line: 215, col: 16, offset: 6326},
				expr: &charClassMatcher{
					pos:        position{line: 215, col: 16, offset: 6326},
					val:        "[a-z_]i",
					chars:      []rune{'_'},
					ranges:     []rune{'a', 'z'},
					ignoreCase: true,
					inverted:   false,
				},
			},
		},
		{
			name: "AnyMatcher",
			pos:  position{line: 217, col: 1, offset: 6336},
			expr: &actionExpr{
				pos: position{line: 217, col: 14, offset: 6351},
				run: (*parser).callonAnyMatcher1,
				expr: &litMatcher{
					pos:        position{line: 217, col: 14, offset: 6351},
					val:        ".",
					ignoreCase: false,
					want:       "\".\"",
				},
			},
		},
		{
			name: "CodeBlock",
			pos:  position{line: 222, col: 1, offset: 6426},
			expr: &actionExpr{
				pos: position{line: 222, col: 13, offset: 6440},
				run: (*parser).callonCodeBlock1,
				expr: &seqExpr{
					pos: position{line: 222, col: 13, offset: 6440},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 222, col: 13, offset: 6440},
							val:        "{",
							ignoreCase: false,
							want:       "\"{\"",
						},
						&ruleRefExpr{
							pos:  position{line: 222, col: 17, offset: 6444},
							name: "Code",
						},
						&litMatcher{
							pos:        position{line: 222, col: 22, offset: 6449},
							val:        "}",
							ignoreCase: false,
							want:       "\"}\"",
						},
					},
				},
			},
		},
		{
			name: "Code",
			pos:  position{line: 228, col: 1, offset: 6547},
			expr: &zeroOrMoreExpr{
				pos: position{line: 228, col: 10, offset: 6558},
				expr: &choiceExpr{
					pos: position{line: 228, col: 10, offset: 6558},
					alternatives: []any{
						&oneOrMoreExpr{
							pos: position{line: 228, col: 12, offset: 6560},
							expr: &seqExpr{
								pos: position{line: 228, col: 12, offset: 6560},
								exprs: []any{
									&notExpr{
										pos: position{line: 228, col: 12, offset: 6560},
										expr: &charClassMatcher{
											pos:        position{line: 228, col: 13, offset: 6561},
											val:        "[{}]",
											chars:      []rune{'{', '}'},
											ignoreCase: false,
											inverted:   false,
										},
									},
									&ruleRefExpr{
										pos:  position{line: 228, col: 18, offset: 6566},
										name: "SourceChar",
									},
								},
							},
						},
						&seqExpr{
							pos: position{line: 228, col: 34, offset: 6582},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 228, col: 34, offset: 6582},
									val:        "{",
									ignoreCase: false,
									want:       "\"{\"",
								},
								&ruleRefExpr{
									pos:  position{line: 228, col: 38, offset: 6586},
									name: "Code",
								},
								&litMatcher{
									pos:        position{line: 228, col: 43, offset: 6591},
									val:        "}",
									ignoreCase: false,
									want:       "\"}\"",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "__",
			pos:  position{line: 230, col: 1, offset: 6599},
			expr: &zeroOrMoreExpr{
				pos: position{line: 230, col: 8, offset: 6608},
				expr: &choiceExpr{
					pos: position{line: 230, col: 8, offset: 6608},
					alternatives: []any{
						&ruleRefExpr{
							pos:  position{line: 230, col: 8, offset: 6608},
							name: "Whitespace",
						},
						&ruleRefExpr{
							pos:  position{line: 230, col: 21, offset: 6621},
							name: "EOL",
						},
						&ruleRefExpr{
							pos:  position{line: 230, col: 27, offset: 6627},
							name: "Comment",
						},
					},
				},
			},
		},
		{
			name: "_",
			pos:  position{line: 231, col: 1, offset: 6638},
			expr: &zeroOrMoreExpr{
				pos: position{line: 231, col: 7, offset: 6646},
				expr: &choiceExpr{
					pos: position{line: 231, col: 7, offset: 6646},
					alternatives: []any{
						&ruleRefExpr{
							pos:  position{line: 231, col: 7, offset: 6646},
							name: "Whitespace",
						},
						&ruleRefExpr{
							pos:  position{line: 231, col: 20, offset: 6659},
							name: "MultiLineCommentNoLineTerminator",
						},
					},
				},
			},
		},
		{
			name: "Whitespace",
			pos:  position{line: 233, col: 1, offset: 6696},
			expr: &charClassMatcher{
				pos:        position{line: 233, col: 14, offset: 6711},
				val:        "[ \\t\\r]",
				chars:      []rune{' ', '\t', '\r'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "EOL",
			pos:  position{line: 234, col: 1, offset: 6719},
			expr: &litMatcher{
				pos:        position{line: 234, col: 7, offset: 6727},
				val:        "\n",
				ignoreCase: false,
				want:       "\"\\n\"",
			},
		},
		{
			name: "EOS",
			pos:  position{line: 235, col: 1, offset: 6732},
			expr: &choiceExpr{
				pos: position{line: 235, col: 7, offset: 6740},
				alternatives: []any{
					&seqExpr{
						pos: position{line: 235, col: 7, offset: 6740},
						exprs: []any{
							&ruleRefExpr{
								pos:  position{line: 235, col: 7, offset: 6740},
								name: "__",
							},
							&litMatcher{
								pos:        position{line: 235, col: 10, offset: 6743},
								val:        ";",
								ignoreCase: false,
								want:       "\";\"",
							},
						},
					},
					&seqExpr{
						pos: position{line: 235, col: 16, offset: 6749},
						exprs: []any{
							&ruleRefExpr{
								pos:  position{line: 235, col: 16, offset: 6749},
								name: "_",
							},
							&zeroOrOneExpr{
								pos: position{line: 235, col: 18, offset: 6751},
								expr: &ruleRefExpr{
									pos:  position{line: 235, col: 18, offset: 6751},
									name: "SingleLineComment",
								},
							},
							&ruleRefExpr{
								pos:  position{line: 235, col: 37, offset: 6770},
								name: "EOL",
							},
						},
					},
					&seqExpr{
						pos: position{line: 235, col: 43, offset: 6776},
						exprs: []any{
							&ruleRefExpr{
								pos:  position{line: 235, col: 43, offset: 6776},
								name: "__",
							},
							&ruleRefExpr{
								pos:  position{line: 235, col: 46, offset: 6779},
								name: "EOF",
							},
						},
					},
				},
			},
		},
		{
			name: "EOF",
			pos:  position{line: 237, col: 1, offset: 6784},
			expr: &notExpr{
				pos: position{line: 237, col: 7, offset: 6792},
				expr: &anyMatcher{
					line: 237, col: 8, offset: 6793,
				},
			},
		},
	},
}

func (c *current) onGrammar1(initializer, rules any) (any, error) {
	_ = "STUB: not implemented"

	// create the grammar, assign its initializer
	return *new(any), nil
}

func (p *parser) callonGrammar1() (any, error) { _ = "STUB: not implemented"; return *new(any), nil }

func (c *current) onInitializer1(code any) (any, error) {
	_ = "STUB: not implemented"
	return *new(any), nil
}

func (p *parser) callonInitializer1() (any, error) {
	_ = "STUB: not implemented"
	return *new(any), nil
}

func (c *current) onRule1(name, display, expr any) (any, error) {
	_ = "STUB: not implemented"
	return *new(any), nil
}

func (p *parser) callonRule1() (any, error) { _ = "STUB: not implemented"; return *new(any), nil }

func (c *current) onChoiceExpr1(first, rest any) (any, error) {
	_ = "STUB: not implemented"
	return *new(any), nil
}

func (p *parser) callonChoiceExpr1() (any, error) { _ = "STUB: not implemented"; return *new(any), nil }

func (c *current) onActionExpr1(expr, code any) (any, error) {
	_ = "STUB: not implemented"
	return *new(any), nil
}

func (p *parser) callonActionExpr1() (any, error) { _ = "STUB: not implemented"; return *new(any), nil }

func (c *current) onSeqExpr1(first, rest any) (any, error) {
	_ = "STUB: not implemented"
	return *new(any), nil
}

func (p *parser) callonSeqExpr1() (any, error) { _ = "STUB: not implemented"; return *new(any), nil }

func (c *current) onLabeledExpr2(label, expr any) (any, error) {
	_ = "STUB: not implemented"
	return *new(any), nil
}

func (p *parser) callonLabeledExpr2() (any, error) {
	_ = "STUB: not implemented"
	return *new(any), nil
}

func (c *current) onPrefixedExpr2(op, expr any) (any, error) {
	_ = "STUB: not implemented"
	return *new(any), nil
}

func (p *parser) callonPrefixedExpr2() (any, error) {
	_ = "STUB: not implemented"
	return *new(any), nil
}

func (c *current) onPrefixedOp1() (any, error) { _ = "STUB: not implemented"; return *new(any), nil }

func (p *parser) callonPrefixedOp1() (any, error) { _ = "STUB: not implemented"; return *new(any), nil }

func (c *current) onSuffixedExpr2(expr, op any) (any, error) {
	_ = "STUB: not implemented"
	return *new(any), nil
}

func (p *parser) callonSuffixedExpr2() (any, error) {
	_ = "STUB: not implemented"
	return *new(any), nil
}

func (c *current) onSuffixedOp1() (any, error) { _ = "STUB: not implemented"; return *new(any), nil }

func (p *parser) callonSuffixedOp1() (any, error) { _ = "STUB: not implemented"; return *new(any), nil }

func (c *current) onPrimaryExpr7(expr any) (any, error) {
	_ = "STUB: not implemented"
	return *new(any), nil
}

func (p *parser) callonPrimaryExpr7() (any, error) {
	_ = "STUB: not implemented"
	return *new(any), nil
}

func (c *current) onRuleRefExpr1(name any) (any, error) {
	_ = "STUB: not implemented"
	return *new(any), nil
}

func (p *parser) callonRuleRefExpr1() (any, error) {
	_ = "STUB: not implemented"
	return *new(any), nil
}

func (c *current) onSemanticPredExpr1(op, code any) (any, error) {
	_ = "STUB: not implemented"
	return *new(any), nil
}

func (p *parser) callonSemanticPredExpr1() (any, error) {
	_ = "STUB: not implemented"
	return *new(any), nil
}

func (c *current) onSemanticPredOp1() (any, error) {
	_ = "STUB: not implemented"
	return *new(any), nil
}

func (p *parser) callonSemanticPredOp1() (any, error) {
	_ = "STUB: not implemented"
	return *new(any), nil
}

func (c *current) onIdentifierName1() (any, error) {
	_ = "STUB: not implemented"
	return *new(any), nil
}

func (p *parser) callonIdentifierName1() (any, error) {
	_ = "STUB: not implemented"
	return *new(any), nil
}

func (c *current) onLitMatcher1(lit, ignore any) (any, error) {
	_ = "STUB: not implemented"
	return *new(any), nil
}

func (p *parser) callonLitMatcher1() (any, error) { _ = "STUB: not implemented"; return *new(any), nil }

func (c *current) onStringLiteral1() (any, error) { _ = "STUB: not implemented"; return *new(any), nil }

func (p *parser) callonStringLiteral1() (any, error) {
	_ = "STUB: not implemented"
	return *new(any), nil
}

func (c *current) onCharClassMatcher1() (any, error) {
	_ = "STUB: not implemented"
	return *new(any), nil
}

func (p *parser) callonCharClassMatcher1() (any, error) {
	_ = "STUB: not implemented"
	return *new(any), nil
}

func (c *current) onAnyMatcher1() (any, error) { _ = "STUB: not implemented"; return *new(any), nil }

func (p *parser) callonAnyMatcher1() (any, error) { _ = "STUB: not implemented"; return *new(any), nil }

func (c *current) onCodeBlock1() (any, error) { _ = "STUB: not implemented"; return *new(any), nil }

func (p *parser) callonCodeBlock1() (any, error) { _ = "STUB: not implemented"; return *new(any), nil }

var (
	// errNoRule is returned when the grammar to parse has no rule.
	errNoRule = errors.New("grammar has no rule")

	// errInvalidEntrypoint is returned when the specified entrypoint rule
	// does not exit.
	errInvalidEntrypoint = errors.New("invalid entrypoint")

	// errInvalidEncoding is returned when the source is not properly
	// utf8-encoded.
	errInvalidEncoding = errors.New("invalid encoding")

	// errMaxExprCnt is used to signal that the maximum number of
	// expressions have been parsed.
	errMaxExprCnt = errors.New("max number of expressions parsed")
)

// Option is a function that can set an option on the parser. It returns
// the previous setting as an Option.
type Option func(*parser) Option

// MaxExpressions creates an Option to stop parsing after the provided
// number of expressions have been parsed, if the value is 0 then the parser will
// parse for as many steps as needed (possibly an infinite number).
//
// The default for maxExprCnt is 0.
func MaxExpressions(maxExprCnt uint64) Option { _ = "STUB: not implemented"; return *new(Option) }

// Entrypoint creates an Option to set the rule name to use as entrypoint.
// The rule name must have been specified in the -alternate-entrypoints
// if generating the parser with the -optimize-grammar flag, otherwise
// it may have been optimized out. Passing an empty string sets the
// entrypoint to the first rule in the grammar.
//
// The default is to start parsing at the first rule in the grammar.
func Entrypoint(ruleName string) Option { _ = "STUB: not implemented"; return *new(Option) }

// Statistics adds a user provided Stats struct to the parser to allow
// the user to process the results after the parsing has finished.
// Also the key for the "no match" counter is set.
//
// Example usage:
//
//	input := "input"
//	stats := Stats{}
//	_, err := Parse("input-file", []byte(input), Statistics(&stats, "no match"))
//	if err != nil {
//	    log.Panicln(err)
//	}
//	b, err := json.MarshalIndent(stats.ChoiceAltCnt, "", "  ")
//	if err != nil {
//	    log.Panicln(err)
//	}
//	fmt.Println(string(b))
func Statistics(stats *Stats, choiceNoMatch string) Option {
	_ = "STUB: not implemented"
	return *new(Option)
}

// Debug creates an Option to set the debug flag to b. When set to true,
// debugging information is printed to stdout while parsing.
//
// The default is false.
func Debug(b bool) Option { _ = "STUB: not implemented"; return *new(Option) }

// Memoize creates an Option to set the memoize flag to b. When set to true,
// the parser will cache all results so each expression is evaluated only
// once. This guarantees linear parsing time even for pathological cases,
// at the expense of more memory and slower times for typical cases.
//
// The default is false.
func Memoize(b bool) Option { _ = "STUB: not implemented"; return *new(Option) }

// AllowInvalidUTF8 creates an Option to allow invalid UTF-8 bytes.
// Every invalid UTF-8 byte is treated as a utf8.RuneError (U+FFFD)
// by character class matchers and is matched by the any matcher.
// The returned matched value, c.text and c.offset are NOT affected.
//
// The default is false.
func AllowInvalidUTF8(b bool) Option { _ = "STUB: not implemented"; return *new(Option) }

// Recover creates an Option to set the recover flag to b. When set to
// true, this causes the parser to recover from panics and convert it
// to an error. Setting it to false can be useful while debugging to
// access the full stack trace.
//
// The default is true.
func Recover(b bool) Option { _ = "STUB: not implemented"; return *new(Option) }

// GlobalStore creates an Option to set a key to a certain value in
// the globalStore.
func GlobalStore(key string, value any) Option { _ = "STUB: not implemented"; return *new(Option) }

// InitState creates an Option to set a key to a certain value in
// the global "state" store.
func InitState(key string, value any) Option { _ = "STUB: not implemented"; return *new(Option) }

// ParseFile parses the file identified by filename.
func ParseFile(filename string, opts ...Option) (i any, err error) {
	_ = "STUB: not implemented"
	return *new(any), nil
}

// ParseReader parses the data from r using filename as information in the
// error messages.
func ParseReader(filename string, r io.Reader, opts ...Option) (any, error) {
	_ = "STUB: not implemented"
	return *new(any), nil
}

// Parse parses the data from b using filename as information in the
// error messages.
func Parse(filename string, b []byte, opts ...Option) (any, error) {
	_ = "STUB: not implemented"
	return *new(any), nil
}

// position records a position in the text.
type position struct {
	line, col, offset int
}

func (p position) String() string { _ = "STUB: not implemented"; return "" }

// savepoint stores all state required to go back to this point in the
// parser.
type savepoint struct {
	position
	rn rune
	w  int
}

type current struct {
	pos  position // start position of the match
	text []byte   // raw text of the match

	// state is a store for arbitrary key,value pairs that the user wants to be
	// tied to the backtracking of the parser.
	// This is always rolled back if a parsing rule fails.
	state storeDict

	// globalStore is a general store for the user to store arbitrary key-value
	// pairs that they need to manage and that they do not want tied to the
	// backtracking of the parser. This is only modified by the user and never
	// rolled back by the parser. It is always up to the user to keep this in a
	// consistent state.
	globalStore storeDict
}

type storeDict map[string]any

// the AST types...

type grammar struct {
	pos   position
	rules []*rule
}

type rule struct {
	pos         position
	name        string
	displayName string
	expr        any
}

type choiceExpr struct {
	pos          position
	alternatives []any
}

type actionExpr struct {
	pos  position
	expr any
	run  func(*parser) (any, error)
}

type recoveryExpr struct {
	pos          position
	expr         any
	recoverExpr  any
	failureLabel []string
}

type seqExpr struct {
	pos   position
	exprs []any
}

type throwExpr struct {
	pos   position
	label string
}

type labeledExpr struct {
	pos   position
	label string
	expr  any
}

type expr struct {
	pos  position
	expr any
}

type (
	andExpr        expr
	notExpr        expr
	zeroOrOneExpr  expr
	zeroOrMoreExpr expr
	oneOrMoreExpr  expr
)

type ruleRefExpr struct {
	pos  position
	name string
}

type stateCodeExpr struct {
	pos position
	run func(*parser) error
}

type andCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type notCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type litMatcher struct {
	pos        position
	val        string
	ignoreCase bool
	want       string
}

type charClassMatcher struct {
	pos             position
	val             string
	basicLatinChars [128]bool
	chars           []rune
	ranges          []rune
	classes         []*unicode.RangeTable
	ignoreCase      bool
	inverted        bool
}

type anyMatcher position

// errList cumulates the errors found by the parser.
type errList []error

func (e *errList) add(err error) { _ = "STUB: not implemented"; return }

func (e errList) err() error { _ = "STUB: not implemented"; return nil }

func (e *errList) dedupe() { _ = "STUB: not implemented"; return }

func (e errList) Error() string { _ = "STUB: not implemented"; return "" }

// parserError wraps an error with a prefix indicating the rule in which
// the error occurred. The original error is stored in the Inner field.
type parserError struct {
	Inner    error
	pos      position
	prefix   string
	expected []string
}

// Error returns the error message.
func (p *parserError) Error() string { _ = "STUB: not implemented"; return "" }

// newParser creates a parser with the specified input source and options.
func newParser(filename string, b []byte, opts ...Option) *parser {
	_ = "STUB: not implemented"
	return nil
}

// start rule is rule [0] unless an alternate entrypoint is specified

// setOptions applies the options to the parser.
func (p *parser) setOptions(opts []Option) { _ = "STUB: not implemented"; return }

type resultTuple struct {
	v   any
	b   bool
	end savepoint
}

const choiceNoMatch = -1

// Stats stores some statistics, gathered during parsing
type Stats struct {
	// ExprCnt counts the number of expressions processed during parsing
	// This value is compared to the maximum number of expressions allowed
	// (set by the MaxExpressions option).
	ExprCnt uint64

	// ChoiceAltCnt is used to count for each ordered choice expression,
	// which alternative is used how may times.
	// These numbers allow to optimize the order of the ordered choice expression
	// to increase the performance of the parser
	//
	// The outer key of ChoiceAltCnt is composed of the name of the rule as well
	// as the line and the column of the ordered choice.
	// The inner key of ChoiceAltCnt is the number (one-based) of the matching alternative.
	// For each alternative the number of matches are counted. If an ordered choice does not
	// match, a special counter is incremented. The name of this counter is set with
	// the parser option Statistics.
	// For an alternative to be included in ChoiceAltCnt, it has to match at least once.
	ChoiceAltCnt map[string]map[string]int
}

type parser struct {
	filename string
	pt       savepoint
	cur      current

	data []byte
	errs *errList

	depth   int
	recover bool
	debug   bool

	memoize bool
	// memoization table for the packrat algorithm:
	// map[offset in source] map[expression or rule] {value, match}
	memo map[int]map[any]resultTuple

	// rules table, maps the rule identifier to the rule node
	rules map[string]*rule
	// variables stack, map of label to value
	vstack []map[string]any
	// rule stack, allows identification of the current rule in errors
	rstack []*rule

	// parse fail
	maxFailPos            position
	maxFailExpected       []string
	maxFailInvertExpected bool

	// max number of expressions to be parsed
	maxExprCnt uint64
	// entrypoint for the parser
	entrypoint string

	allowInvalidUTF8 bool

	*Stats

	choiceNoMatch string
	// recovery expression stack, keeps track of the currently available recovery expression, these are traversed in reverse
	recoveryStack []map[string]any
}

// push a variable set on the vstack.
func (p *parser) pushV() { _ = "STUB: not implemented"; return }

// create new empty slot in the stack

// slice to 1 more

// get the last args set

// empty map, all good

// pop a variable set from the vstack.
func (p *parser) popV() {
	_ = "STUB: not implemented"
	// if the map is not empty, clear it
	return
}

// GC that map

// push a recovery expression with its labels to the recoveryStack
func (p *parser) pushRecovery(labels []string, expr any) { _ = "STUB: not implemented"; return }

// create new empty slot in the stack

// slice to 1 more

// pop a recovery expression from the recoveryStack
func (p *parser) popRecovery() {
	_ = "STUB: not implemented"
	// GC that map
	return
}

func (p *parser) print(prefix, s string) string { _ = "STUB: not implemented"; return "" }

func (p *parser) printIndent(mark string, s string) string { _ = "STUB: not implemented"; return "" }

func (p *parser) in(s string) string { _ = "STUB: not implemented"; return "" }

func (p *parser) out(s string) string { _ = "STUB: not implemented"; return "" }

func (p *parser) addErr(err error) { _ = "STUB: not implemented"; return }

func (p *parser) addErrAt(err error, pos position, expected []string) {
	_ = "STUB: not implemented"
	return
}

func (p *parser) failAt(fail bool, pos position, want string) {
	_ = "STUB: not implemented"
	// process fail if parsing fails and not inverted or parsing succeeds and invert is set
	return
}

// read advances the parser to the next rune.
func (p *parser) read() { _ = "STUB: not implemented"; return }

// see utf8.DecodeRune

// restore parser position to the savepoint pt.
func (p *parser) restore(pt savepoint) { _ = "STUB: not implemented"; return }

// Cloner is implemented by any value that has a Clone method, which returns a
// copy of the value. This is mainly used for types which are not passed by
// value (e.g map, slice, chan) or structs that contain such types.
//
// This is used in conjunction with the global state feature to create proper
// copies of the state to allow the parser to properly restore the state in
// the case of backtracking.
type Cloner interface {
	Clone() any
}

var statePool = &sync.Pool{
	New: func() any { return make(storeDict) },
}

func (sd storeDict) Discard() { _ = "STUB: not implemented"; return }

// clone and return parser current state.
func (p *parser) cloneState() storeDict { _ = "STUB: not implemented"; return *new(storeDict) }

// restore parser current state to the state storeDict.
// every restoreState should applied only one time for every cloned state
func (p *parser) restoreState(state storeDict) { _ = "STUB: not implemented"; return }

// get the slice of bytes from the savepoint start to the current position.
func (p *parser) sliceFrom(start savepoint) []byte { _ = "STUB: not implemented"; return nil }

func (p *parser) getMemoized(node any) (resultTuple, bool) {
	_ = "STUB: not implemented"
	return *new(resultTuple), false
}

func (p *parser) setMemoized(pt savepoint, node any, tuple resultTuple) {
	_ = "STUB: not implemented"
	return
}

func (p *parser) buildRulesTable(g *grammar) { _ = "STUB: not implemented"; return }

func (p *parser) parse(g *grammar) (val any, err error) {
	_ = "STUB: not implemented"
	return *new(any), nil
}

// TODO : not super critical but this could be generated

// panic can be used in action code to stop parsing immediately
// and return the panic as an error.

// advance to first rune

// If parsing fails, but no errors have been recorded, the expected values
// for the farthest parser position are returned as error.

func listJoin(list []string, sep string, lastSep string) string {
	_ = "STUB: not implemented"
	return ""
}

func (p *parser) parseRuleMemoize(rule *rule) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (p *parser) parseRuleWrap(rule *rule) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (p *parser) parseRule(rule *rule) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (p *parser) parseExprWrap(expr any) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (p *parser) parseExpr(expr any) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (p *parser) parseActionExpr(act *actionExpr) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (p *parser) parseAndCodeExpr(and *andCodeExpr) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (p *parser) parseAndExpr(and *andExpr) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (p *parser) parseAnyMatcher(any *anyMatcher) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

// EOF - see utf8.DecodeRune

func (p *parser) parseCharClassMatcher(chr *charClassMatcher) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

// can't match EOF
// see utf8.DecodeRune

// try to match in the list of available chars

// try to match in the list of ranges

// try to match in the list of Unicode classes

func (p *parser) incChoiceAltCnt(ch *choiceExpr, altI int) { _ = "STUB: not implemented"; return }

// We increment altI by 1, so the keys do not start at 0

func (p *parser) parseChoiceExpr(ch *choiceExpr) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

// dummy assignment to prevent compile error if optimized

func (p *parser) parseLabeledExpr(lab *labeledExpr) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (p *parser) parseLitMatcher(lit *litMatcher) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (p *parser) parseNotCodeExpr(not *notCodeExpr) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (p *parser) parseNotExpr(not *notExpr) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (p *parser) parseOneOrMoreExpr(expr *oneOrMoreExpr) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

// did not match once, no match

func (p *parser) parseRecoveryExpr(recover *recoveryExpr) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (p *parser) parseRuleRefExpr(ref *ruleRefExpr) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (p *parser) parseSeqExpr(seq *seqExpr) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (p *parser) parseStateCodeExpr(state *stateCodeExpr) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (p *parser) parseThrowExpr(expr *throwExpr) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (p *parser) parseZeroOrMoreExpr(expr *zeroOrMoreExpr) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (p *parser) parseZeroOrOneExpr(expr *zeroOrOneExpr) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

// whether it matched or not, consider it a match
