// Code generated by pigeon; DO NOT EDIT.

package errorpos

import (
	"errors"
	"io"
	"sync"
	"unicode"
)

var g = &grammar{
	rules: []*rule{
		{
			name: "Input",
			pos:  position{line: 5, col: 1, offset: 22},
			expr: &seqExpr{
				pos: position{line: 5, col: 9, offset: 32},
				exprs: []any{
					&ruleRefExpr{
						pos:  position{line: 5, col: 9, offset: 32},
						name: "_",
					},
					&choiceExpr{
						pos: position{line: 5, col: 12, offset: 35},
						alternatives: []any{
							&ruleRefExpr{
								pos:  position{line: 5, col: 12, offset: 35},
								name: "case01",
							},
							&ruleRefExpr{
								pos:  position{line: 5, col: 21, offset: 44},
								name: "case02",
							},
							&ruleRefExpr{
								pos:  position{line: 5, col: 30, offset: 53},
								name: "case03",
							},
							&ruleRefExpr{
								pos:  position{line: 5, col: 39, offset: 62},
								name: "case04",
							},
							&ruleRefExpr{
								pos:  position{line: 5, col: 48, offset: 71},
								name: "case05",
							},
							&ruleRefExpr{
								pos:  position{line: 5, col: 57, offset: 80},
								name: "case06",
							},
							&ruleRefExpr{
								pos:  position{line: 5, col: 66, offset: 89},
								name: "case07",
							},
							&ruleRefExpr{
								pos:  position{line: 5, col: 75, offset: 98},
								name: "case08",
							},
							&ruleRefExpr{
								pos:  position{line: 5, col: 84, offset: 107},
								name: "case09",
							},
							&ruleRefExpr{
								pos:  position{line: 5, col: 93, offset: 116},
								name: "case10",
							},
							&ruleRefExpr{
								pos:  position{line: 5, col: 102, offset: 125},
								name: "case11",
							},
						},
					},
					&ruleRefExpr{
						pos:  position{line: 5, col: 110, offset: 133},
						name: "EOF",
					},
				},
			},
		},
		{
			name: "case01",
			pos:  position{line: 7, col: 1, offset: 138},
			expr: &seqExpr{
				pos: position{line: 7, col: 10, offset: 149},
				exprs: []any{
					&litMatcher{
						pos:        position{line: 7, col: 10, offset: 149},
						val:        "case01",
						ignoreCase: false,
						want:       "\"case01\"",
					},
					&ruleRefExpr{
						pos:  position{line: 7, col: 19, offset: 158},
						name: "_",
					},
					&oneOrMoreExpr{
						pos: position{line: 7, col: 21, offset: 160},
						expr: &seqExpr{
							pos: position{line: 7, col: 22, offset: 161},
							exprs: []any{
								&choiceExpr{
									pos: position{line: 7, col: 23, offset: 162},
									alternatives: []any{
										&ruleRefExpr{
											pos:  position{line: 7, col: 23, offset: 162},
											name: "increment",
										},
										&ruleRefExpr{
											pos:  position{line: 7, col: 35, offset: 174},
											name: "decrement",
										},
										&ruleRefExpr{
											pos:  position{line: 7, col: 47, offset: 186},
											name: "zero",
										},
									},
								},
								&ruleRefExpr{
									pos:  position{line: 7, col: 53, offset: 192},
									name: "_",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "case02",
			pos:  position{line: 8, col: 1, offset: 197},
			expr: &seqExpr{
				pos: position{line: 8, col: 10, offset: 208},
				exprs: []any{
					&litMatcher{
						pos:        position{line: 8, col: 10, offset: 208},
						val:        "case02",
						ignoreCase: false,
						want:       "\"case02\"",
					},
					&ruleRefExpr{
						pos:  position{line: 8, col: 19, offset: 217},
						name: "__",
					},
					&oneOrMoreExpr{
						pos: position{line: 8, col: 22, offset: 220},
						expr: &charClassMatcher{
							pos:        position{line: 8, col: 22, offset: 220},
							val:        "[^abc]",
							chars:      []rune{'a', 'b', 'c'},
							ignoreCase: false,
							inverted:   true,
						},
					},
				},
			},
		},
		{
			name: "case03",
			pos:  position{line: 9, col: 1, offset: 228},
			expr: &seqExpr{
				pos: position{line: 9, col: 10, offset: 239},
				exprs: []any{
					&litMatcher{
						pos:        position{line: 9, col: 10, offset: 239},
						val:        "case03",
						ignoreCase: false,
						want:       "\"case03\"",
					},
					&ruleRefExpr{
						pos:  position{line: 9, col: 19, offset: 248},
						name: "__",
					},
					&zeroOrOneExpr{
						pos: position{line: 9, col: 22, offset: 251},
						expr: &litMatcher{
							pos:        position{line: 9, col: 22, offset: 251},
							val:        "x",
							ignoreCase: false,
							want:       "\"x\"",
						},
					},
					&charClassMatcher{
						pos:        position{line: 9, col: 27, offset: 256},
						val:        "[0-9]",
						ranges:     []rune{'0', '9'},
						ignoreCase: false,
						inverted:   false,
					},
				},
			},
		},
		{
			name: "case04",
			pos:  position{line: 10, col: 1, offset: 262},
			expr: &seqExpr{
				pos: position{line: 10, col: 10, offset: 273},
				exprs: []any{
					&litMatcher{
						pos:        position{line: 10, col: 10, offset: 273},
						val:        "case04",
						ignoreCase: false,
						want:       "\"case04\"",
					},
					&ruleRefExpr{
						pos:  position{line: 10, col: 19, offset: 282},
						name: "__",
					},
					&charClassMatcher{
						pos:        position{line: 10, col: 22, offset: 285},
						val:        "[\\x30-\\x39]",
						ranges:     []rune{'0', '9'},
						ignoreCase: false,
						inverted:   false,
					},
					&charClassMatcher{
						pos:        position{line: 10, col: 34, offset: 297},
						val:        "[^\\x30-\\x39]",
						ranges:     []rune{'0', '9'},
						ignoreCase: false,
						inverted:   true,
					},
					&charClassMatcher{
						pos:        position{line: 10, col: 47, offset: 310},
						val:        "[\\pN]",
						classes:    []*unicode.RangeTable{rangeTable("N")},
						ignoreCase: false,
						inverted:   false,
					},
					&charClassMatcher{
						pos:        position{line: 10, col: 53, offset: 316},
						val:        "[^\\pN]",
						classes:    []*unicode.RangeTable{rangeTable("N")},
						ignoreCase: false,
						inverted:   true,
					},
				},
			},
		},
		{
			name: "case05",
			pos:  position{line: 11, col: 1, offset: 323},
			expr: &seqExpr{
				pos: position{line: 11, col: 10, offset: 334},
				exprs: []any{
					&litMatcher{
						pos:        position{line: 11, col: 10, offset: 334},
						val:        "case05",
						ignoreCase: false,
						want:       "\"case05\"",
					},
					&ruleRefExpr{
						pos:  position{line: 11, col: 19, offset: 343},
						name: "__",
					},
					&notExpr{
						pos: position{line: 11, col: 22, offset: 346},
						expr: &litMatcher{
							pos:        position{line: 11, col: 23, offset: 347},
							val:        "not",
							ignoreCase: false,
							want:       "\"not\"",
						},
					},
					&litMatcher{
						pos:        position{line: 11, col: 29, offset: 353},
						val:        "yes",
						ignoreCase: false,
						want:       "\"yes\"",
					},
				},
			},
		},
		{
			name: "case06",
			pos:  position{line: 12, col: 1, offset: 359},
			expr: &seqExpr{
				pos: position{line: 12, col: 10, offset: 370},
				exprs: []any{
					&litMatcher{
						pos:        position{line: 12, col: 10, offset: 370},
						val:        "case06",
						ignoreCase: false,
						want:       "\"case06\"",
					},
					&ruleRefExpr{
						pos:  position{line: 12, col: 19, offset: 379},
						name: "__",
					},
					&notExpr{
						pos: position{line: 12, col: 22, offset: 382},
						expr: &charClassMatcher{
							pos:        position{line: 12, col: 23, offset: 383},
							val:        "[0-9]",
							ranges:     []rune{'0', '9'},
							ignoreCase: false,
							inverted:   false,
						},
					},
					&litMatcher{
						pos:        position{line: 12, col: 29, offset: 389},
						val:        "x",
						ignoreCase: false,
						want:       "\"x\"",
					},
				},
			},
		},
		{
			name: "case07",
			pos:  position{line: 13, col: 1, offset: 393},
			expr: &seqExpr{
				pos: position{line: 13, col: 10, offset: 404},
				exprs: []any{
					&litMatcher{
						pos:        position{line: 13, col: 10, offset: 404},
						val:        "case07",
						ignoreCase: false,
						want:       "\"case07\"",
					},
					&ruleRefExpr{
						pos:  position{line: 13, col: 19, offset: 413},
						name: "__",
					},
					&notExpr{
						pos: position{line: 13, col: 22, offset: 416},
						expr: &choiceExpr{
							pos: position{line: 13, col: 24, offset: 418},
							alternatives: []any{
								&litMatcher{
									pos:        position{line: 13, col: 24, offset: 418},
									val:        "abc",
									ignoreCase: true,
									want:       "\"abc\"i",
								},
								&charClassMatcher{
									pos:        position{line: 13, col: 33, offset: 427},
									val:        "[a-c]i",
									ranges:     []rune{'a', 'c'},
									ignoreCase: true,
									inverted:   false,
								},
								&charClassMatcher{
									pos:        position{line: 13, col: 42, offset: 436},
									val:        "[\\pL]",
									classes:    []*unicode.RangeTable{rangeTable("L")},
									ignoreCase: false,
									inverted:   false,
								},
							},
						},
					},
					&charClassMatcher{
						pos:        position{line: 13, col: 49, offset: 443},
						val:        "[0-9]",
						ranges:     []rune{'0', '9'},
						ignoreCase: false,
						inverted:   false,
					},
				},
			},
		},
		{
			name: "case08",
			pos:  position{line: 14, col: 1, offset: 449},
			expr: &seqExpr{
				pos: position{line: 14, col: 10, offset: 460},
				exprs: []any{
					&litMatcher{
						pos:        position{line: 14, col: 10, offset: 460},
						val:        "case08",
						ignoreCase: false,
						want:       "\"case08\"",
					},
					&ruleRefExpr{
						pos:  position{line: 14, col: 19, offset: 469},
						name: "__",
					},
					&andExpr{
						pos: position{line: 14, col: 22, offset: 472},
						expr: &litMatcher{
							pos:        position{line: 14, col: 23, offset: 473},
							val:        "a",
							ignoreCase: true,
							want:       "\"a\"i",
						},
					},
					&anyMatcher{
						line: 14, col: 28, offset: 478,
					},
				},
			},
		},
		{
			name: "case09",
			pos:  position{line: 15, col: 1, offset: 480},
			expr: &seqExpr{
				pos: position{line: 15, col: 10, offset: 491},
				exprs: []any{
					&litMatcher{
						pos:        position{line: 15, col: 10, offset: 491},
						val:        "case09",
						ignoreCase: false,
						want:       "\"case09\"",
					},
					&ruleRefExpr{
						pos:  position{line: 15, col: 19, offset: 500},
						name: "__",
					},
					&andExpr{
						pos: position{line: 15, col: 22, offset: 503},
						expr: &charClassMatcher{
							pos:        position{line: 15, col: 23, offset: 504},
							val:        "[0-9]",
							ranges:     []rune{'0', '9'},
							ignoreCase: false,
							inverted:   false,
						},
					},
					&anyMatcher{
						line: 15, col: 29, offset: 510,
					},
				},
			},
		},
		{
			name: "case10",
			pos:  position{line: 16, col: 1, offset: 512},
			expr: &seqExpr{
				pos: position{line: 16, col: 10, offset: 523},
				exprs: []any{
					&litMatcher{
						pos:        position{line: 16, col: 10, offset: 523},
						val:        "case10",
						ignoreCase: false,
						want:       "\"case10\"",
					},
					&ruleRefExpr{
						pos:  position{line: 16, col: 19, offset: 532},
						name: "__",
					},
					&andExpr{
						pos: position{line: 16, col: 22, offset: 535},
						expr: &choiceExpr{
							pos: position{line: 16, col: 24, offset: 537},
							alternatives: []any{
								&litMatcher{
									pos:        position{line: 16, col: 24, offset: 537},
									val:        "0",
									ignoreCase: false,
									want:       "\"0\"",
								},
								&charClassMatcher{
									pos:        position{line: 16, col: 30, offset: 543},
									val:        "[012]",
									chars:      []rune{'0', '1', '2'},
									ignoreCase: false,
									inverted:   false,
								},
								&charClassMatcher{
									pos:        position{line: 16, col: 38, offset: 551},
									val:        "[3-9]",
									ranges:     []rune{'3', '9'},
									ignoreCase: false,
									inverted:   false,
								},
								&charClassMatcher{
									pos:        position{line: 16, col: 46, offset: 559},
									val:        "[\\pN]",
									classes:    []*unicode.RangeTable{rangeTable("N")},
									ignoreCase: false,
									inverted:   false,
								},
							},
						},
					},
					&anyMatcher{
						line: 16, col: 53, offset: 566,
					},
				},
			},
		},
		{
			name: "case11",
			pos:  position{line: 17, col: 1, offset: 568},
			expr: &seqExpr{
				pos: position{line: 17, col: 10, offset: 579},
				exprs: []any{
					&litMatcher{
						pos:        position{line: 17, col: 10, offset: 579},
						val:        "case11",
						ignoreCase: false,
						want:       "\"case11\"",
					},
					&ruleRefExpr{
						pos:  position{line: 17, col: 19, offset: 588},
						name: "__",
					},
					&notExpr{
						pos: position{line: 17, col: 22, offset: 591},
						expr: &notExpr{
							pos: position{line: 17, col: 24, offset: 593},
							expr: &litMatcher{
								pos:        position{line: 17, col: 26, offset: 595},
								val:        "a",
								ignoreCase: false,
								want:       "\"a\"",
							},
						},
					},
					&litMatcher{
						pos:        position{line: 17, col: 32, offset: 601},
						val:        "a",
						ignoreCase: false,
						want:       "\"a\"",
					},
				},
			},
		},
		{
			name: "increment",
			pos:  position{line: 19, col: 1, offset: 606},
			expr: &litMatcher{
				pos:        position{line: 19, col: 13, offset: 620},
				val:        "inc",
				ignoreCase: false,
				want:       "\"inc\"",
			},
		},
		{
			name: "decrement",
			pos:  position{line: 20, col: 1, offset: 626},
			expr: &litMatcher{
				pos:        position{line: 20, col: 13, offset: 640},
				val:        "dec",
				ignoreCase: false,
				want:       "\"dec\"",
			},
		},
		{
			name: "zero",
			pos:  position{line: 21, col: 1, offset: 646},
			expr: &litMatcher{
				pos:        position{line: 21, col: 8, offset: 655},
				val:        "zero",
				ignoreCase: false,
				want:       "\"zero\"",
			},
		},
		{
			name: "oneOrMore",
			pos:  position{line: 22, col: 1, offset: 662},
			expr: &litMatcher{
				pos:        position{line: 22, col: 13, offset: 676},
				val:        "oneOrMore",
				ignoreCase: false,
				want:       "\"oneOrMore\"",
			},
		},
		{
			name: "_",
			pos:  position{line: 23, col: 1, offset: 688},
			expr: &zeroOrMoreExpr{
				pos: position{line: 23, col: 5, offset: 694},
				expr: &charClassMatcher{
					pos:        position{line: 23, col: 5, offset: 694},
					val:        "[ \\t\\n\\r]",
					chars:      []rune{' ', '\t', '\n', '\r'},
					ignoreCase: false,
					inverted:   false,
				},
			},
		},
		{
			name: "__",
			pos:  position{line: 24, col: 1, offset: 705},
			expr: &charClassMatcher{
				pos:        position{line: 24, col: 6, offset: 712},
				val:        "[ ]",
				chars:      []rune{' '},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "EOF",
			pos:  position{line: 25, col: 1, offset: 716},
			expr: &notExpr{
				pos: position{line: 25, col: 7, offset: 724},
				expr: &anyMatcher{
					line: 25, col: 8, offset: 725,
				},
			},
		},
	},
}

var (
	// errNoRule is returned when the grammar to parse has no rule.
	errNoRule = errors.New("grammar has no rule")

	// errInvalidEntrypoint is returned when the specified entrypoint rule
	// does not exit.
	errInvalidEntrypoint = errors.New("invalid entrypoint")

	// errInvalidEncoding is returned when the source is not properly
	// utf8-encoded.
	errInvalidEncoding = errors.New("invalid encoding")

	// errMaxExprCnt is used to signal that the maximum number of
	// expressions have been parsed.
	errMaxExprCnt = errors.New("max number of expressions parsed")
)

// Option is a function that can set an option on the parser. It returns
// the previous setting as an Option.
type Option func(*parser) Option

// MaxExpressions creates an Option to stop parsing after the provided
// number of expressions have been parsed, if the value is 0 then the parser will
// parse for as many steps as needed (possibly an infinite number).
//
// The default for maxExprCnt is 0.
func MaxExpressions(maxExprCnt uint64) Option { _ = "STUB: not implemented"; return *new(Option) }

// Entrypoint creates an Option to set the rule name to use as entrypoint.
// The rule name must have been specified in the -alternate-entrypoints
// if generating the parser with the -optimize-grammar flag, otherwise
// it may have been optimized out. Passing an empty string sets the
// entrypoint to the first rule in the grammar.
//
// The default is to start parsing at the first rule in the grammar.
func Entrypoint(ruleName string) Option { _ = "STUB: not implemented"; return *new(Option) }

// Statistics adds a user provided Stats struct to the parser to allow
// the user to process the results after the parsing has finished.
// Also the key for the "no match" counter is set.
//
// Example usage:
//
//	input := "input"
//	stats := Stats{}
//	_, err := Parse("input-file", []byte(input), Statistics(&stats, "no match"))
//	if err != nil {
//	    log.Panicln(err)
//	}
//	b, err := json.MarshalIndent(stats.ChoiceAltCnt, "", "  ")
//	if err != nil {
//	    log.Panicln(err)
//	}
//	fmt.Println(string(b))
func Statistics(stats *Stats, choiceNoMatch string) Option {
	_ = "STUB: not implemented"
	return *new(Option)
}

// Debug creates an Option to set the debug flag to b. When set to true,
// debugging information is printed to stdout while parsing.
//
// The default is false.
func Debug(b bool) Option { _ = "STUB: not implemented"; return *new(Option) }

// Memoize creates an Option to set the memoize flag to b. When set to true,
// the parser will cache all results so each expression is evaluated only
// once. This guarantees linear parsing time even for pathological cases,
// at the expense of more memory and slower times for typical cases.
//
// The default is false.
func Memoize(b bool) Option { _ = "STUB: not implemented"; return *new(Option) }

// AllowInvalidUTF8 creates an Option to allow invalid UTF-8 bytes.
// Every invalid UTF-8 byte is treated as a utf8.RuneError (U+FFFD)
// by character class matchers and is matched by the any matcher.
// The returned matched value, c.text and c.offset are NOT affected.
//
// The default is false.
func AllowInvalidUTF8(b bool) Option { _ = "STUB: not implemented"; return *new(Option) }

// Recover creates an Option to set the recover flag to b. When set to
// true, this causes the parser to recover from panics and convert it
// to an error. Setting it to false can be useful while debugging to
// access the full stack trace.
//
// The default is true.
func Recover(b bool) Option { _ = "STUB: not implemented"; return *new(Option) }

// GlobalStore creates an Option to set a key to a certain value in
// the globalStore.
func GlobalStore(key string, value any) Option { _ = "STUB: not implemented"; return *new(Option) }

// InitState creates an Option to set a key to a certain value in
// the global "state" store.
func InitState(key string, value any) Option { _ = "STUB: not implemented"; return *new(Option) }

// ParseFile parses the file identified by filename.
func ParseFile(filename string, opts ...Option) (i any, err error) {
	_ = "STUB: not implemented" // nolint: deadcode
	return *new(any), nil
}

// ParseReader parses the data from r using filename as information in the
// error messages.
func ParseReader(filename string, r io.Reader, opts ...Option) (any, error) {
	_ = "STUB: not implemented" // nolint: deadcode
	return *new(any), nil
}

// Parse parses the data from b using filename as information in the
// error messages.
func Parse(filename string, b []byte, opts ...Option) (any, error) {
	_ = "STUB: not implemented"
	return *new(any), nil
}

// position records a position in the text.
type position struct {
	line, col, offset int
}

func (p position) String() string { _ = "STUB: not implemented"; return "" }

// savepoint stores all state required to go back to this point in the
// parser.
type savepoint struct {
	position
	rn rune
	w  int
}

type current struct {
	pos  position // start position of the match
	text []byte   // raw text of the match

	// state is a store for arbitrary key,value pairs that the user wants to be
	// tied to the backtracking of the parser.
	// This is always rolled back if a parsing rule fails.
	state storeDict

	// globalStore is a general store for the user to store arbitrary key-value
	// pairs that they need to manage and that they do not want tied to the
	// backtracking of the parser. This is only modified by the user and never
	// rolled back by the parser. It is always up to the user to keep this in a
	// consistent state.
	globalStore storeDict
}

type storeDict map[string]any

// the AST types...

// nolint: structcheck
type grammar struct {
	pos   position
	rules []*rule
}

// nolint: structcheck
type rule struct {
	pos         position
	name        string
	displayName string
	expr        any
}

// nolint: structcheck
type choiceExpr struct {
	pos          position
	alternatives []any
}

// nolint: structcheck
type actionExpr struct {
	pos  position
	expr any
	run  func(*parser) (any, error)
}

// nolint: structcheck
type recoveryExpr struct {
	pos          position
	expr         any
	recoverExpr  any
	failureLabel []string
}

// nolint: structcheck
type seqExpr struct {
	pos   position
	exprs []any
}

// nolint: structcheck
type throwExpr struct {
	pos   position
	label string
}

// nolint: structcheck
type labeledExpr struct {
	pos   position
	label string
	expr  any
}

// nolint: structcheck
type expr struct {
	pos  position
	expr any
}

type (
	andExpr        expr // nolint: structcheck
	notExpr        expr // nolint: structcheck
	zeroOrOneExpr  expr // nolint: structcheck
	zeroOrMoreExpr expr // nolint: structcheck
	oneOrMoreExpr  expr // nolint: structcheck
)

// nolint: structcheck
type ruleRefExpr struct {
	pos  position
	name string
}

// nolint: structcheck
type stateCodeExpr struct {
	pos position
	run func(*parser) error
}

// nolint: structcheck
type andCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

// nolint: structcheck
type notCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

// nolint: structcheck
type litMatcher struct {
	pos        position
	val        string
	ignoreCase bool
	want       string
}

// nolint: structcheck
type charClassMatcher struct {
	pos             position
	val             string
	basicLatinChars [128]bool
	chars           []rune
	ranges          []rune
	classes         []*unicode.RangeTable
	ignoreCase      bool
	inverted        bool
}

type anyMatcher position // nolint: structcheck

// errList cumulates the errors found by the parser.
type errList []error

func (e *errList) add(err error) { _ = "STUB: not implemented"; return }

func (e errList) err() error { _ = "STUB: not implemented"; return nil }

func (e *errList) dedupe() { _ = "STUB: not implemented"; return }

func (e errList) Error() string { _ = "STUB: not implemented"; return "" }

// parserError wraps an error with a prefix indicating the rule in which
// the error occurred. The original error is stored in the Inner field.
type parserError struct {
	Inner    error
	pos      position
	prefix   string
	expected []string
}

// Error returns the error message.
func (p *parserError) Error() string { _ = "STUB: not implemented"; return "" }

// newParser creates a parser with the specified input source and options.
func newParser(filename string, b []byte, opts ...Option) *parser {
	_ = "STUB: not implemented"
	return nil
}

// start rule is rule [0] unless an alternate entrypoint is specified

// setOptions applies the options to the parser.
func (p *parser) setOptions(opts []Option) { _ = "STUB: not implemented"; return }

// nolint: structcheck,deadcode
type resultTuple struct {
	v   any
	b   bool
	end savepoint
}

// nolint: varcheck
const choiceNoMatch = -1

// Stats stores some statistics, gathered during parsing
type Stats struct {
	// ExprCnt counts the number of expressions processed during parsing
	// This value is compared to the maximum number of expressions allowed
	// (set by the MaxExpressions option).
	ExprCnt uint64

	// ChoiceAltCnt is used to count for each ordered choice expression,
	// which alternative is used how may times.
	// These numbers allow to optimize the order of the ordered choice expression
	// to increase the performance of the parser
	//
	// The outer key of ChoiceAltCnt is composed of the name of the rule as well
	// as the line and the column of the ordered choice.
	// The inner key of ChoiceAltCnt is the number (one-based) of the matching alternative.
	// For each alternative the number of matches are counted. If an ordered choice does not
	// match, a special counter is incremented. The name of this counter is set with
	// the parser option Statistics.
	// For an alternative to be included in ChoiceAltCnt, it has to match at least once.
	ChoiceAltCnt map[string]map[string]int
}

// nolint: structcheck,maligned
type parser struct {
	filename string
	pt       savepoint
	cur      current

	data []byte
	errs *errList

	depth   int
	recover bool
	debug   bool

	memoize bool
	// memoization table for the packrat algorithm:
	// map[offset in source] map[expression or rule] {value, match}
	memo map[int]map[any]resultTuple

	// rules table, maps the rule identifier to the rule node
	rules map[string]*rule
	// variables stack, map of label to value
	vstack []map[string]any
	// rule stack, allows identification of the current rule in errors
	rstack []*rule

	// parse fail
	maxFailPos            position
	maxFailExpected       []string
	maxFailInvertExpected bool

	// max number of expressions to be parsed
	maxExprCnt uint64
	// entrypoint for the parser
	entrypoint string

	allowInvalidUTF8 bool

	*Stats

	choiceNoMatch string
	// recovery expression stack, keeps track of the currently available recovery expression, these are traversed in reverse
	recoveryStack []map[string]any
}

// push a variable set on the vstack.
func (p *parser) pushV() { _ = "STUB: not implemented"; return }

// create new empty slot in the stack

// slice to 1 more

// get the last args set

// empty map, all good

// pop a variable set from the vstack.
func (p *parser) popV() {
	_ = "STUB: not implemented"
	// if the map is not empty, clear it
	return
}

// GC that map

// push a recovery expression with its labels to the recoveryStack
func (p *parser) pushRecovery(labels []string, expr any) { _ = "STUB: not implemented"; return }

// create new empty slot in the stack

// slice to 1 more

// pop a recovery expression from the recoveryStack
func (p *parser) popRecovery() {
	_ = "STUB: not implemented"
	// GC that map
	return
}

func (p *parser) print(prefix, s string) string { _ = "STUB: not implemented"; return "" }

func (p *parser) printIndent(mark string, s string) string { _ = "STUB: not implemented"; return "" }

func (p *parser) in(s string) string { _ = "STUB: not implemented"; return "" }

func (p *parser) out(s string) string { _ = "STUB: not implemented"; return "" }

func (p *parser) addErr(err error) { _ = "STUB: not implemented"; return }

func (p *parser) addErrAt(err error, pos position, expected []string) {
	_ = "STUB: not implemented"
	return
}

func (p *parser) failAt(fail bool, pos position, want string) {
	_ = "STUB: not implemented"
	// process fail if parsing fails and not inverted or parsing succeeds and invert is set
	return
}

// read advances the parser to the next rune.
func (p *parser) read() { _ = "STUB: not implemented"; return }

// see utf8.DecodeRune

// restore parser position to the savepoint pt.
func (p *parser) restore(pt savepoint) { _ = "STUB: not implemented"; return }

// Cloner is implemented by any value that has a Clone method, which returns a
// copy of the value. This is mainly used for types which are not passed by
// value (e.g map, slice, chan) or structs that contain such types.
//
// This is used in conjunction with the global state feature to create proper
// copies of the state to allow the parser to properly restore the state in
// the case of backtracking.
type Cloner interface {
	Clone() any
}

var statePool = &sync.Pool{
	New: func() any { return make(storeDict) },
}

func (sd storeDict) Discard() { _ = "STUB: not implemented"; return }

// clone and return parser current state.
func (p *parser) cloneState() storeDict { _ = "STUB: not implemented"; return *new(storeDict) }

// restore parser current state to the state storeDict.
// every restoreState should applied only one time for every cloned state
func (p *parser) restoreState(state storeDict) { _ = "STUB: not implemented"; return }

// get the slice of bytes from the savepoint start to the current position.
func (p *parser) sliceFrom(start savepoint) []byte { _ = "STUB: not implemented"; return nil }

func (p *parser) getMemoized(node any) (resultTuple, bool) {
	_ = "STUB: not implemented"
	return *new(resultTuple), false
}

func (p *parser) setMemoized(pt savepoint, node any, tuple resultTuple) {
	_ = "STUB: not implemented"
	return
}

func (p *parser) buildRulesTable(g *grammar) { _ = "STUB: not implemented"; return }

// nolint: gocyclo
func (p *parser) parse(g *grammar) (val any, err error) {
	_ = "STUB: not implemented"
	return *new(any), nil
}

// TODO : not super critical but this could be generated

// panic can be used in action code to stop parsing immediately
// and return the panic as an error.

// advance to first rune

// If parsing fails, but no errors have been recorded, the expected values
// for the farthest parser position are returned as error.

func listJoin(list []string, sep string, lastSep string) string {
	_ = "STUB: not implemented"
	return ""
}

func (p *parser) parseRuleMemoize(rule *rule) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (p *parser) parseRuleWrap(rule *rule) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (p *parser) parseRule(rule *rule) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (p *parser) parseExprWrap(expr any) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

// nolint: gocyclo
func (p *parser) parseExpr(expr any) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (p *parser) parseActionExpr(act *actionExpr) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (p *parser) parseAndCodeExpr(and *andCodeExpr) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (p *parser) parseAndExpr(and *andExpr) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (p *parser) parseAnyMatcher(any *anyMatcher) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

// EOF - see utf8.DecodeRune

// nolint: gocyclo
func (p *parser) parseCharClassMatcher(chr *charClassMatcher) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

// can't match EOF
// see utf8.DecodeRune

// try to match in the list of available chars

// try to match in the list of ranges

// try to match in the list of Unicode classes

func (p *parser) incChoiceAltCnt(ch *choiceExpr, altI int) { _ = "STUB: not implemented"; return }

// We increment altI by 1, so the keys do not start at 0

func (p *parser) parseChoiceExpr(ch *choiceExpr) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

// dummy assignment to prevent compile error if optimized

func (p *parser) parseLabeledExpr(lab *labeledExpr) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (p *parser) parseLitMatcher(lit *litMatcher) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (p *parser) parseNotCodeExpr(not *notCodeExpr) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (p *parser) parseNotExpr(not *notExpr) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (p *parser) parseOneOrMoreExpr(expr *oneOrMoreExpr) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

// did not match once, no match

func (p *parser) parseRecoveryExpr(recover *recoveryExpr) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (p *parser) parseRuleRefExpr(ref *ruleRefExpr) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (p *parser) parseSeqExpr(seq *seqExpr) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (p *parser) parseStateCodeExpr(state *stateCodeExpr) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (p *parser) parseThrowExpr(expr *throwExpr) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (p *parser) parseZeroOrMoreExpr(expr *zeroOrMoreExpr) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (p *parser) parseZeroOrOneExpr(expr *zeroOrOneExpr) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

// whether it matched or not, consider it a match

func rangeTable(class string) *unicode.RangeTable { _ = "STUB: not implemented"; return nil }

// cannot happen
