// Code generated by pigeon; DO NOT EDIT.

// Package json parses JSON as defined by [1].
//
// BUGS: the escaped forward solidus (`\/`) is not currently handled.
//
// [1]: http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf
package json

import (
	"errors"
	"io"
	"unicode"
)

func toAnySlice(v any) []any { _ = "STUB: not implemented"; return nil }

var g = &grammar{
	rules: []*rule{
		{
			name: "JSON",
			pos:  position{line: 17, col: 1, offset: 321},
			expr: &actionExpr{
				pos: position{line: 17, col: 8, offset: 330},
				run: (*parser).callonJSON1,
				expr: &seqExpr{
					pos: position{line: 17, col: 8, offset: 330},
					exprs: []any{
						&ruleRefExpr{
							pos:  position{line: 17, col: 8, offset: 330},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 17, col: 10, offset: 332},
							label: "val",
							expr: &ruleRefExpr{
								pos:  position{line: 17, col: 14, offset: 336},
								name: "Value",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 17, col: 20, offset: 342},
							name: "EOF",
						},
					},
				},
			},
		},
		{
			name: "Value",
			pos:  position{line: 21, col: 1, offset: 371},
			expr: &actionExpr{
				pos: position{line: 21, col: 9, offset: 381},
				run: (*parser).callonValue1,
				expr: &seqExpr{
					pos: position{line: 21, col: 9, offset: 381},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 21, col: 9, offset: 381},
							label: "val",
							expr: &choiceExpr{
								pos: position{line: 21, col: 15, offset: 387},
								alternatives: []any{
									&ruleRefExpr{
										pos:  position{line: 21, col: 15, offset: 387},
										name: "Object",
									},
									&ruleRefExpr{
										pos:  position{line: 21, col: 24, offset: 396},
										name: "Array",
									},
									&ruleRefExpr{
										pos:  position{line: 21, col: 32, offset: 404},
										name: "Number",
									},
									&ruleRefExpr{
										pos:  position{line: 21, col: 41, offset: 413},
										name: "String",
									},
									&ruleRefExpr{
										pos:  position{line: 21, col: 50, offset: 422},
										name: "Bool",
									},
									&ruleRefExpr{
										pos:  position{line: 21, col: 57, offset: 429},
										name: "Null",
									},
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 21, col: 64, offset: 436},
							name: "_",
						},
					},
				},
			},
		},
		{
			name: "Object",
			pos:  position{line: 25, col: 1, offset: 463},
			expr: &actionExpr{
				pos: position{line: 25, col: 10, offset: 474},
				run: (*parser).callonObject1,
				expr: &seqExpr{
					pos: position{line: 25, col: 10, offset: 474},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 25, col: 10, offset: 474},
							val:        "{",
							ignoreCase: false,
							want:       "\"{\"",
						},
						&ruleRefExpr{
							pos:  position{line: 25, col: 14, offset: 478},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 25, col: 16, offset: 480},
							label: "vals",
							expr: &zeroOrOneExpr{
								pos: position{line: 25, col: 21, offset: 485},
								expr: &seqExpr{
									pos: position{line: 25, col: 23, offset: 487},
									exprs: []any{
										&ruleRefExpr{
											pos:  position{line: 25, col: 23, offset: 487},
											name: "String",
										},
										&ruleRefExpr{
											pos:  position{line: 25, col: 30, offset: 494},
											name: "_",
										},
										&litMatcher{
											pos:        position{line: 25, col: 32, offset: 496},
											val:        ":",
											ignoreCase: false,
											want:       "\":\"",
										},
										&ruleRefExpr{
											pos:  position{line: 25, col: 36, offset: 500},
											name: "_",
										},
										&ruleRefExpr{
											pos:  position{line: 25, col: 38, offset: 502},
											name: "Value",
										},
										&zeroOrMoreExpr{
											pos: position{line: 25, col: 44, offset: 508},
											expr: &seqExpr{
												pos: position{line: 25, col: 46, offset: 510},
												exprs: []any{
													&litMatcher{
														pos:        position{line: 25, col: 46, offset: 510},
														val:        ",",
														ignoreCase: false,
														want:       "\",\"",
													},
													&ruleRefExpr{
														pos:  position{line: 25, col: 50, offset: 514},
														name: "_",
													},
													&ruleRefExpr{
														pos:  position{line: 25, col: 52, offset: 516},
														name: "String",
													},
													&ruleRefExpr{
														pos:  position{line: 25, col: 59, offset: 523},
														name: "_",
													},
													&litMatcher{
														pos:        position{line: 25, col: 61, offset: 525},
														val:        ":",
														ignoreCase: false,
														want:       "\":\"",
													},
													&ruleRefExpr{
														pos:  position{line: 25, col: 65, offset: 529},
														name: "_",
													},
													&ruleRefExpr{
														pos:  position{line: 25, col: 67, offset: 531},
														name: "Value",
													},
												},
											},
										},
									},
								},
							},
						},
						&litMatcher{
							pos:        position{line: 25, col: 79, offset: 543},
							val:        "}",
							ignoreCase: false,
							want:       "\"}\"",
						},
					},
				},
			},
		},
		{
			name: "Array",
			pos:  position{line: 40, col: 1, offset: 871},
			expr: &actionExpr{
				pos: position{line: 40, col: 9, offset: 881},
				run: (*parser).callonArray1,
				expr: &seqExpr{
					pos: position{line: 40, col: 9, offset: 881},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 40, col: 9, offset: 881},
							val:        "[",
							ignoreCase: false,
							want:       "\"[\"",
						},
						&ruleRefExpr{
							pos:  position{line: 40, col: 13, offset: 885},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 40, col: 15, offset: 887},
							label: "vals",
							expr: &zeroOrOneExpr{
								pos: position{line: 40, col: 20, offset: 892},
								expr: &seqExpr{
									pos: position{line: 40, col: 22, offset: 894},
									exprs: []any{
										&ruleRefExpr{
											pos:  position{line: 40, col: 22, offset: 894},
											name: "Value",
										},
										&zeroOrMoreExpr{
											pos: position{line: 40, col: 28, offset: 900},
											expr: &seqExpr{
												pos: position{line: 40, col: 30, offset: 902},
												exprs: []any{
													&litMatcher{
														pos:        position{line: 40, col: 30, offset: 902},
														val:        ",",
														ignoreCase: false,
														want:       "\",\"",
													},
													&ruleRefExpr{
														pos:  position{line: 40, col: 34, offset: 906},
														name: "_",
													},
													&ruleRefExpr{
														pos:  position{line: 40, col: 36, offset: 908},
														name: "Value",
													},
												},
											},
										},
									},
								},
							},
						},
						&litMatcher{
							pos:        position{line: 40, col: 48, offset: 920},
							val:        "]",
							ignoreCase: false,
							want:       "\"]\"",
						},
					},
				},
			},
		},
		{
			name: "Number",
			pos:  position{line: 54, col: 1, offset: 1204},
			expr: &actionExpr{
				pos: position{line: 54, col: 10, offset: 1215},
				run: (*parser).callonNumber1,
				expr: &seqExpr{
					pos: position{line: 54, col: 10, offset: 1215},
					exprs: []any{
						&zeroOrOneExpr{
							pos: position{line: 54, col: 10, offset: 1215},
							expr: &litMatcher{
								pos:        position{line: 54, col: 10, offset: 1215},
								val:        "-",
								ignoreCase: false,
								want:       "\"-\"",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 54, col: 15, offset: 1220},
							name: "Integer",
						},
						&zeroOrOneExpr{
							pos: position{line: 54, col: 23, offset: 1228},
							expr: &seqExpr{
								pos: position{line: 54, col: 25, offset: 1230},
								exprs: []any{
									&litMatcher{
										pos:        position{line: 54, col: 25, offset: 1230},
										val:        ".",
										ignoreCase: false,
										want:       "\".\"",
									},
									&oneOrMoreExpr{
										pos: position{line: 54, col: 29, offset: 1234},
										expr: &ruleRefExpr{
											pos:  position{line: 54, col: 29, offset: 1234},
											name: "DecimalDigit",
										},
									},
								},
							},
						},
						&zeroOrOneExpr{
							pos: position{line: 54, col: 46, offset: 1251},
							expr: &ruleRefExpr{
								pos:  position{line: 54, col: 46, offset: 1251},
								name: "Exponent",
							},
						},
					},
				},
			},
		},
		{
			name: "Integer",
			pos:  position{line: 60, col: 1, offset: 1406},
			expr: &choiceExpr{
				pos: position{line: 60, col: 11, offset: 1418},
				alternatives: []any{
					&litMatcher{
						pos:        position{line: 60, col: 11, offset: 1418},
						val:        "0",
						ignoreCase: false,
						want:       "\"0\"",
					},
					&seqExpr{
						pos: position{line: 60, col: 17, offset: 1424},
						exprs: []any{
							&ruleRefExpr{
								pos:  position{line: 60, col: 17, offset: 1424},
								name: "NonZeroDecimalDigit",
							},
							&zeroOrMoreExpr{
								pos: position{line: 60, col: 37, offset: 1444},
								expr: &ruleRefExpr{
									pos:  position{line: 60, col: 37, offset: 1444},
									name: "DecimalDigit",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Exponent",
			pos:  position{line: 62, col: 1, offset: 1459},
			expr: &seqExpr{
				pos: position{line: 62, col: 12, offset: 1472},
				exprs: []any{
					&litMatcher{
						pos:        position{line: 62, col: 12, offset: 1472},
						val:        "e",
						ignoreCase: true,
						want:       "\"e\"i",
					},
					&zeroOrOneExpr{
						pos: position{line: 62, col: 17, offset: 1477},
						expr: &charClassMatcher{
							pos:             position{line: 62, col: 17, offset: 1477},
							val:             "[+-]",
							chars:           []rune{'+', '-'},
							basicLatinChars: [128]bool{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, false, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
							ignoreCase:      false,
							inverted:        false,
						},
					},
					&oneOrMoreExpr{
						pos: position{line: 62, col: 23, offset: 1483},
						expr: &ruleRefExpr{
							pos:  position{line: 62, col: 23, offset: 1483},
							name: "DecimalDigit",
						},
					},
				},
			},
		},
		{
			name: "String",
			pos:  position{line: 64, col: 1, offset: 1498},
			expr: &actionExpr{
				pos: position{line: 64, col: 10, offset: 1509},
				run: (*parser).callonString1,
				expr: &seqExpr{
					pos: position{line: 64, col: 10, offset: 1509},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 64, col: 10, offset: 1509},
							val:        "\"",
							ignoreCase: false,
							want:       "\"\\\"\"",
						},
						&zeroOrMoreExpr{
							pos: position{line: 64, col: 14, offset: 1513},
							expr: &choiceExpr{
								pos: position{line: 64, col: 16, offset: 1515},
								alternatives: []any{
									&seqExpr{
										pos: position{line: 64, col: 16, offset: 1515},
										exprs: []any{
											&notExpr{
												pos: position{line: 64, col: 16, offset: 1515},
												expr: &ruleRefExpr{
													pos:  position{line: 64, col: 17, offset: 1516},
													name: "EscapedChar",
												},
											},
											&anyMatcher{
												line: 64, col: 29, offset: 1528,
											},
										},
									},
									&seqExpr{
										pos: position{line: 64, col: 33, offset: 1532},
										exprs: []any{
											&litMatcher{
												pos:        position{line: 64, col: 33, offset: 1532},
												val:        "\\",
												ignoreCase: false,
												want:       "\"\\\\\"",
											},
											&ruleRefExpr{
												pos:  position{line: 64, col: 38, offset: 1537},
												name: "EscapeSequence",
											},
										},
									},
								},
							},
						},
						&litMatcher{
							pos:        position{line: 64, col: 56, offset: 1555},
							val:        "\"",
							ignoreCase: false,
							want:       "\"\\\"\"",
						},
					},
				},
			},
		},
		{
			name: "EscapedChar",
			pos:  position{line: 69, col: 1, offset: 1673},
			expr: &charClassMatcher{
				pos:             position{line: 69, col: 15, offset: 1689},
				val:             "[\\x00-\\x1f\"\\\\]",
				chars:           []rune{'"', '\\'},
				ranges:          []rune{'\x00', '\x1f'},
				basicLatinChars: [128]bool{true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false, false, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
				ignoreCase:      false,
				inverted:        false,
			},
		},
		{
			name: "EscapeSequence",
			pos:  position{line: 71, col: 1, offset: 1705},
			expr: &choiceExpr{
				pos: position{line: 71, col: 18, offset: 1724},
				alternatives: []any{
					&ruleRefExpr{
						pos:  position{line: 71, col: 18, offset: 1724},
						name: "SingleCharEscape",
					},
					&ruleRefExpr{
						pos:  position{line: 71, col: 37, offset: 1743},
						name: "UnicodeEscape",
					},
				},
			},
		},
		{
			name: "SingleCharEscape",
			pos:  position{line: 73, col: 1, offset: 1758},
			expr: &charClassMatcher{
				pos:             position{line: 73, col: 20, offset: 1779},
				val:             "[\"\\\\/bfnrt]",
				chars:           []rune{'"', '\\', '/', 'b', 'f', 'n', 'r', 't'},
				basicLatinChars: [128]bool{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, false, false, false, false, false, false, false, false, false, false, false, false, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, false, false, false, false, false, true, false, false, false, true, false, false, false, false, false, false, false, true, false, false, false, true, false, true, false, false, false, false, false, false, false, false, false, false, false},
				ignoreCase:      false,
				inverted:        false,
			},
		},
		{
			name: "UnicodeEscape",
			pos:  position{line: 75, col: 1, offset: 1792},
			expr: &seqExpr{
				pos: position{line: 75, col: 17, offset: 1810},
				exprs: []any{
					&litMatcher{
						pos:        position{line: 75, col: 17, offset: 1810},
						val:        "u",
						ignoreCase: false,
						want:       "\"u\"",
					},
					&ruleRefExpr{
						pos:  position{line: 75, col: 21, offset: 1814},
						name: "HexDigit",
					},
					&ruleRefExpr{
						pos:  position{line: 75, col: 30, offset: 1823},
						name: "HexDigit",
					},
					&ruleRefExpr{
						pos:  position{line: 75, col: 39, offset: 1832},
						name: "HexDigit",
					},
					&ruleRefExpr{
						pos:  position{line: 75, col: 48, offset: 1841},
						name: "HexDigit",
					},
				},
			},
		},
		{
			name: "DecimalDigit",
			pos:  position{line: 77, col: 1, offset: 1851},
			expr: &charClassMatcher{
				pos:             position{line: 77, col: 16, offset: 1868},
				val:             "[0-9]",
				ranges:          []rune{'0', '9'},
				basicLatinChars: [128]bool{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, true, true, true, true, true, true, true, true, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
				ignoreCase:      false,
				inverted:        false,
			},
		},
		{
			name: "NonZeroDecimalDigit",
			pos:  position{line: 79, col: 1, offset: 1875},
			expr: &charClassMatcher{
				pos:             position{line: 79, col: 23, offset: 1899},
				val:             "[1-9]",
				ranges:          []rune{'1', '9'},
				basicLatinChars: [128]bool{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, true, true, true, true, true, true, true, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
				ignoreCase:      false,
				inverted:        false,
			},
		},
		{
			name: "HexDigit",
			pos:  position{line: 81, col: 1, offset: 1906},
			expr: &charClassMatcher{
				pos:             position{line: 81, col: 12, offset: 1919},
				val:             "[0-9a-f]i",
				ranges:          []rune{'0', '9', 'a', 'f'},
				basicLatinChars: [128]bool{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, true, true, true, true, true, true, true, true, true, false, false, false, false, false, false, false, true, true, true, true, true, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, true, true, true, true, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
				ignoreCase:      true,
				inverted:        false,
			},
		},
		{
			name: "Bool",
			pos:  position{line: 83, col: 1, offset: 1930},
			expr: &choiceExpr{
				pos: position{line: 83, col: 8, offset: 1939},
				alternatives: []any{
					&actionExpr{
						pos: position{line: 83, col: 8, offset: 1939},
						run: (*parser).callonBool2,
						expr: &litMatcher{
							pos:        position{line: 83, col: 8, offset: 1939},
							val:        "true",
							ignoreCase: false,
							want:       "\"true\"",
						},
					},
					&actionExpr{
						pos: position{line: 83, col: 38, offset: 1969},
						run: (*parser).callonBool4,
						expr: &litMatcher{
							pos:        position{line: 83, col: 38, offset: 1969},
							val:        "false",
							ignoreCase: false,
							want:       "\"false\"",
						},
					},
				},
			},
		},
		{
			name: "Null",
			pos:  position{line: 85, col: 1, offset: 2000},
			expr: &actionExpr{
				pos: position{line: 85, col: 8, offset: 2009},
				run: (*parser).callonNull1,
				expr: &litMatcher{
					pos:        position{line: 85, col: 8, offset: 2009},
					val:        "null",
					ignoreCase: false,
					want:       "\"null\"",
				},
			},
		},
		{
			name:        "_",
			displayName: "\"whitespace\"",
			pos:         position{line: 87, col: 1, offset: 2037},
			expr: &zeroOrMoreExpr{
				pos: position{line: 87, col: 18, offset: 2056},
				expr: &charClassMatcher{
					pos:             position{line: 87, col: 18, offset: 2056},
					val:             "[ \\t\\r\\n]",
					chars:           []rune{' ', '\t', '\r', '\n'},
					basicLatinChars: [128]bool{false, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
					ignoreCase:      false,
					inverted:        false,
				},
			},
		},
		{
			name: "EOF",
			pos:  position{line: 89, col: 1, offset: 2068},
			expr: &notExpr{
				pos: position{line: 89, col: 7, offset: 2076},
				expr: &anyMatcher{
					line: 89, col: 8, offset: 2077,
				},
			},
		},
	},
}

func (c *current) onJSON1(val any) (any, error) { _ = "STUB: not implemented"; return *new(any), nil }

func (p *parser) callonJSON1() (any, error) { _ = "STUB: not implemented"; return *new(any), nil }

func (c *current) onValue1(val any) (any, error) { _ = "STUB: not implemented"; return *new(any), nil }

func (p *parser) callonValue1() (any, error) { _ = "STUB: not implemented"; return *new(any), nil }

func (c *current) onObject1(vals any) (any, error) {
	_ = "STUB: not implemented"
	return *new(any), nil
}

func (p *parser) callonObject1() (any, error) { _ = "STUB: not implemented"; return *new(any), nil }

func (c *current) onArray1(vals any) (any, error) { _ = "STUB: not implemented"; return *new(any), nil }

func (p *parser) callonArray1() (any, error) { _ = "STUB: not implemented"; return *new(any), nil }

func (c *current) onNumber1() (any, error) {
	_ = "STUB: not implemented"
	// JSON numbers have the same syntax as Go's, and are parseable using
	// strconv.
	return *new(any), nil
}

func (p *parser) callonNumber1() (any, error) { _ = "STUB: not implemented"; return *new(any), nil }

func (c *current) onString1() (any, error) { _ = "STUB: not implemented"; return *new(any), nil }

func (p *parser) callonString1() (any, error) { _ = "STUB: not implemented"; return *new(any), nil }

func (c *current) onBool2() (any, error) { _ = "STUB: not implemented"; return *new(any), nil }

func (p *parser) callonBool2() (any, error) { _ = "STUB: not implemented"; return *new(any), nil }

func (c *current) onBool4() (any, error) { _ = "STUB: not implemented"; return *new(any), nil }

func (p *parser) callonBool4() (any, error) { _ = "STUB: not implemented"; return *new(any), nil }

func (c *current) onNull1() (any, error) { _ = "STUB: not implemented"; return *new(any), nil }

func (p *parser) callonNull1() (any, error) { _ = "STUB: not implemented"; return *new(any), nil }

var (
	// errNoRule is returned when the grammar to parse has no rule.
	errNoRule = errors.New("grammar has no rule")

	// errInvalidEntrypoint is returned when the specified entrypoint rule
	// does not exit.
	errInvalidEntrypoint = errors.New("invalid entrypoint")

	// errInvalidEncoding is returned when the source is not properly
	// utf8-encoded.
	errInvalidEncoding = errors.New("invalid encoding")

	// errMaxExprCnt is used to signal that the maximum number of
	// expressions have been parsed.
	errMaxExprCnt = errors.New("max number of expressions parsed")
)

// Option is a function that can set an option on the parser. It returns
// the previous setting as an Option.
type Option func(*parser) Option

// MaxExpressions creates an Option to stop parsing after the provided
// number of expressions have been parsed, if the value is 0 then the parser will
// parse for as many steps as needed (possibly an infinite number).
//
// The default for maxExprCnt is 0.
func MaxExpressions(maxExprCnt uint64) Option { _ = "STUB: not implemented"; return *new(Option) }

// Entrypoint creates an Option to set the rule name to use as entrypoint.
// The rule name must have been specified in the -alternate-entrypoints
// if generating the parser with the -optimize-grammar flag, otherwise
// it may have been optimized out. Passing an empty string sets the
// entrypoint to the first rule in the grammar.
//
// The default is to start parsing at the first rule in the grammar.
func Entrypoint(ruleName string) Option { _ = "STUB: not implemented"; return *new(Option) }

// AllowInvalidUTF8 creates an Option to allow invalid UTF-8 bytes.
// Every invalid UTF-8 byte is treated as a utf8.RuneError (U+FFFD)
// by character class matchers and is matched by the any matcher.
// The returned matched value, c.text and c.offset are NOT affected.
//
// The default is false.
func AllowInvalidUTF8(b bool) Option { _ = "STUB: not implemented"; return *new(Option) }

// Recover creates an Option to set the recover flag to b. When set to
// true, this causes the parser to recover from panics and convert it
// to an error. Setting it to false can be useful while debugging to
// access the full stack trace.
//
// The default is true.
func Recover(b bool) Option { _ = "STUB: not implemented"; return *new(Option) }

// GlobalStore creates an Option to set a key to a certain value in
// the globalStore.
func GlobalStore(key string, value any) Option { _ = "STUB: not implemented"; return *new(Option) }

// ParseFile parses the file identified by filename.
func ParseFile(filename string, opts ...Option) (i any, err error) {
	_ = "STUB: not implemented" // nolint: deadcode
	return *new(any), nil
}

// ParseReader parses the data from r using filename as information in the
// error messages.
func ParseReader(filename string, r io.Reader, opts ...Option) (any, error) {
	_ = "STUB: not implemented" // nolint: deadcode
	return *new(any), nil
}

// Parse parses the data from b using filename as information in the
// error messages.
func Parse(filename string, b []byte, opts ...Option) (any, error) {
	_ = "STUB: not implemented"
	return *new(any), nil
}

// position records a position in the text.
type position struct {
	line, col, offset int
}

func (p position) String() string { _ = "STUB: not implemented"; return "" }

// savepoint stores all state required to go back to this point in the
// parser.
type savepoint struct {
	position
	rn rune
	w  int
}

type current struct {
	pos  position // start position of the match
	text []byte   // raw text of the match

	// globalStore is a general store for the user to store arbitrary key-value
	// pairs that they need to manage and that they do not want tied to the
	// backtracking of the parser. This is only modified by the user and never
	// rolled back by the parser. It is always up to the user to keep this in a
	// consistent state.
	globalStore storeDict
}

type storeDict map[string]any

// the AST types...

// nolint: structcheck
type grammar struct {
	pos   position
	rules []*rule
}

// nolint: structcheck
type rule struct {
	pos         position
	name        string
	displayName string
	expr        any
}

// nolint: structcheck
type choiceExpr struct {
	pos          position
	alternatives []any
}

// nolint: structcheck
type actionExpr struct {
	pos  position
	expr any
	run  func(*parser) (any, error)
}

// nolint: structcheck
type recoveryExpr struct {
	pos          position
	expr         any
	recoverExpr  any
	failureLabel []string
}

// nolint: structcheck
type seqExpr struct {
	pos   position
	exprs []any
}

// nolint: structcheck
type throwExpr struct {
	pos   position
	label string
}

// nolint: structcheck
type labeledExpr struct {
	pos   position
	label string
	expr  any
}

// nolint: structcheck
type expr struct {
	pos  position
	expr any
}

type (
	andExpr        expr // nolint: structcheck
	notExpr        expr // nolint: structcheck
	zeroOrOneExpr  expr // nolint: structcheck
	zeroOrMoreExpr expr // nolint: structcheck
	oneOrMoreExpr  expr // nolint: structcheck
)

// nolint: structcheck
type ruleRefExpr struct {
	pos  position
	name string
}

// nolint: structcheck
type andCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

// nolint: structcheck
type notCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

// nolint: structcheck
type litMatcher struct {
	pos        position
	val        string
	ignoreCase bool
	want       string
}

// nolint: structcheck
type charClassMatcher struct {
	pos             position
	val             string
	basicLatinChars [128]bool
	chars           []rune
	ranges          []rune
	classes         []*unicode.RangeTable
	ignoreCase      bool
	inverted        bool
}

type anyMatcher position // nolint: structcheck

// errList cumulates the errors found by the parser.
type errList []error

func (e *errList) add(err error) { _ = "STUB: not implemented"; return }

func (e errList) err() error { _ = "STUB: not implemented"; return nil }

func (e *errList) dedupe() { _ = "STUB: not implemented"; return }

func (e errList) Error() string { _ = "STUB: not implemented"; return "" }

// parserError wraps an error with a prefix indicating the rule in which
// the error occurred. The original error is stored in the Inner field.
type parserError struct {
	Inner    error
	pos      position
	prefix   string
	expected []string
}

// Error returns the error message.
func (p *parserError) Error() string { _ = "STUB: not implemented"; return "" }

// newParser creates a parser with the specified input source and options.
func newParser(filename string, b []byte, opts ...Option) *parser {
	_ = "STUB: not implemented"
	return nil
}

// start rule is rule [0] unless an alternate entrypoint is specified

// setOptions applies the options to the parser.
func (p *parser) setOptions(opts []Option) { _ = "STUB: not implemented"; return }

// nolint: structcheck,deadcode
type resultTuple struct {
	v   any
	b   bool
	end savepoint
}

// nolint: varcheck
const choiceNoMatch = -1

// Stats stores some statistics, gathered during parsing
type Stats struct {
	// ExprCnt counts the number of expressions processed during parsing
	// This value is compared to the maximum number of expressions allowed
	// (set by the MaxExpressions option).
	ExprCnt uint64

	// ChoiceAltCnt is used to count for each ordered choice expression,
	// which alternative is used how may times.
	// These numbers allow to optimize the order of the ordered choice expression
	// to increase the performance of the parser
	//
	// The outer key of ChoiceAltCnt is composed of the name of the rule as well
	// as the line and the column of the ordered choice.
	// The inner key of ChoiceAltCnt is the number (one-based) of the matching alternative.
	// For each alternative the number of matches are counted. If an ordered choice does not
	// match, a special counter is incremented. The name of this counter is set with
	// the parser option Statistics.
	// For an alternative to be included in ChoiceAltCnt, it has to match at least once.
	ChoiceAltCnt map[string]map[string]int
}

// nolint: structcheck,maligned
type parser struct {
	filename string
	pt       savepoint
	cur      current

	data []byte
	errs *errList

	depth   int
	recover bool

	// rules table, maps the rule identifier to the rule node
	rules map[string]*rule
	// variables stack, map of label to value
	vstack []map[string]any
	// rule stack, allows identification of the current rule in errors
	rstack []*rule

	// parse fail
	maxFailPos            position
	maxFailExpected       []string
	maxFailInvertExpected bool

	// max number of expressions to be parsed
	maxExprCnt uint64
	// entrypoint for the parser
	entrypoint string

	allowInvalidUTF8 bool

	*Stats

	choiceNoMatch string
	// recovery expression stack, keeps track of the currently available recovery expression, these are traversed in reverse
	recoveryStack []map[string]any
}

// push a variable set on the vstack.
func (p *parser) pushV() { _ = "STUB: not implemented"; return }

// create new empty slot in the stack

// slice to 1 more

// get the last args set

// empty map, all good

// pop a variable set from the vstack.
func (p *parser) popV() {
	_ = "STUB: not implemented"
	// if the map is not empty, clear it
	return
}

// GC that map

// push a recovery expression with its labels to the recoveryStack
func (p *parser) pushRecovery(labels []string, expr any) { _ = "STUB: not implemented"; return }

// create new empty slot in the stack

// slice to 1 more

// pop a recovery expression from the recoveryStack
func (p *parser) popRecovery() {
	_ = "STUB: not implemented"
	// GC that map
	return
}

func (p *parser) addErr(err error) { _ = "STUB: not implemented"; return }

func (p *parser) addErrAt(err error, pos position, expected []string) {
	_ = "STUB: not implemented"
	return
}

func (p *parser) failAt(fail bool, pos position, want string) {
	_ = "STUB: not implemented"
	// process fail if parsing fails and not inverted or parsing succeeds and invert is set
	return
}

// read advances the parser to the next rune.
func (p *parser) read() { _ = "STUB: not implemented"; return }

// see utf8.DecodeRune

// restore parser position to the savepoint pt.
func (p *parser) restore(pt savepoint) { _ = "STUB: not implemented"; return }

// get the slice of bytes from the savepoint start to the current position.
func (p *parser) sliceFrom(start savepoint) []byte { _ = "STUB: not implemented"; return nil }

func (p *parser) buildRulesTable(g *grammar) { _ = "STUB: not implemented"; return }

// nolint: gocyclo
func (p *parser) parse(g *grammar) (val any, err error) {
	_ = "STUB: not implemented"
	return *new(any), nil
}

// TODO : not super critical but this could be generated

// panic can be used in action code to stop parsing immediately
// and return the panic as an error.

// advance to first rune

// If parsing fails, but no errors have been recorded, the expected values
// for the farthest parser position are returned as error.

func listJoin(list []string, sep string, lastSep string) string {
	_ = "STUB: not implemented"
	return ""
}

func (p *parser) parseRuleWrap(rule *rule) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (p *parser) parseRule(rule *rule) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (p *parser) parseExprWrap(expr any) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

// nolint: gocyclo
func (p *parser) parseExpr(expr any) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (p *parser) parseActionExpr(act *actionExpr) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (p *parser) parseAndCodeExpr(and *andCodeExpr) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (p *parser) parseAndExpr(and *andExpr) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (p *parser) parseAnyMatcher(any *anyMatcher) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

// EOF - see utf8.DecodeRune

// nolint: gocyclo
func (p *parser) parseCharClassMatcher(chr *charClassMatcher) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

// can't match EOF
// see utf8.DecodeRune

// try to match in the list of available chars

// try to match in the list of ranges

// try to match in the list of Unicode classes

func (p *parser) parseChoiceExpr(ch *choiceExpr) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

// dummy assignment to prevent compile error if optimized

func (p *parser) parseLabeledExpr(lab *labeledExpr) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (p *parser) parseLitMatcher(lit *litMatcher) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (p *parser) parseNotCodeExpr(not *notCodeExpr) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (p *parser) parseNotExpr(not *notExpr) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (p *parser) parseOneOrMoreExpr(expr *oneOrMoreExpr) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

// did not match once, no match

func (p *parser) parseRecoveryExpr(recover *recoveryExpr) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (p *parser) parseRuleRefExpr(ref *ruleRefExpr) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (p *parser) parseSeqExpr(seq *seqExpr) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (p *parser) parseThrowExpr(expr *throwExpr) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (p *parser) parseZeroOrMoreExpr(expr *zeroOrMoreExpr) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (p *parser) parseZeroOrOneExpr(expr *zeroOrOneExpr) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

// whether it matched or not, consider it a match
