// Package builder generates the parser code for a given grammar. It makes
// no attempt to verify the correctness of the grammar.
package builder

import (
	"io"

	"github.com/mna/pigeon/ast"
)

const codeGeneratedComment = "// Code generated by pigeon; DO NOT EDIT.\n\n"

// generated function templates
var (
	onFuncTemplate = `func (%s *current) %s(%s) (any, error) {
%s
}
`
	onPredFuncTemplate = `func (%s *current) %s(%s) (bool, error) {
%s
}
`
	onStateFuncTemplate = `func (%s *current) %s(%s) (error) {
%s
}
`
	callFuncTemplate = `func (p *parser) call%s() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.%[1]s(%s)
}
`
	callPredFuncTemplate = `func (p *parser) call%s() (bool, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.%[1]s(%s)
}
`
	callStateFuncTemplate = `func (p *parser) call%s() error {
    stack := p.vstack[len(p.vstack)-1]
    _ = stack
    return p.cur.%[1]s(%s)
}
`
)

// Option is a function that can set an option on the builder. It returns
// the previous setting as an Option.
type Option func(*builder) Option

// ReceiverName returns an option that specifies the receiver name to
// use for the current struct (which is the struct on which all code blocks
// except the initializer are generated).
func ReceiverName(nm string) Option { _ = "STUB: not implemented"; return *new(Option) }

// Optimize returns an option that specifies the optimize option
// If optimize is true, the Debug and Memoize code is completely
// removed from the resulting parser
func Optimize(optimize bool) Option { _ = "STUB: not implemented"; return *new(Option) }

// SupportLeftRecursion returns an option that specifies the supportLeftRecursion option.
// If supportLeftRecursion is true, LeftRecursion code is added to the resulting parser.
func SupportLeftRecursion(support bool) Option { _ = "STUB: not implemented"; return *new(Option) }

// Nolint returns an option that specifies the nolint option
// If nolint is true, special '// nolint: ...' comments are added
// to the generated parser to suppress warnings by gometalinter or golangci-lint.
func Nolint(nolint bool) Option { _ = "STUB: not implemented"; return *new(Option) }

// BasicLatinLookupTable returns an option that specifies the basicLatinLookup option
// If basicLatinLookup is true, a lookup slice for the first 128 chars of
// the Unicode table (Basic Latin) is generated for each CharClassMatcher
// to increase the character matching.
func BasicLatinLookupTable(basicLatinLookupTable bool) Option {
	_ = "STUB: not implemented"
	return *new(Option)
}

// BuildParser builds the PEG parser using the provider grammar. The code is
// written to the specified w.
func BuildParser(w io.Writer, g *ast.Grammar, opts ...Option) error {
	_ = "STUB: not implemented"
	return nil
}

type builder struct {
	w   io.Writer
	err error

	// options
	recvName              string
	optimize              bool
	basicLatinLookupTable bool
	globalState           bool
	nolint                bool
	supportLeftRecursion  bool
	haveLeftRecursion     bool

	ruleName  string
	exprIndex int
	argsStack [][]string

	rangeTable bool
}

func (b *builder) setOptions(opts []Option) { _ = "STUB: not implemented"; return }

func (b *builder) buildParser(grammar *ast.Grammar) error { _ = "STUB: not implemented"; return nil }

func (b *builder) writeInit(init *ast.CodeBlock) { _ = "STUB: not implemented"; return }

// remove opening and closing braces

func (b *builder) writeGrammar(g *ast.Grammar) {
	_ = "STUB: not implemented"
	// transform the ast grammar to the self-contained, no dependency version
	// of the parser-generator grammar.
	return
}

func (b *builder) writeRule(r *ast.Rule) { _ = "STUB: not implemented"; return }

func (b *builder) writeExpr(expr ast.Expression) { _ = "STUB: not implemented"; return }

func (b *builder) writeActionExpr(act *ast.ActionExpr) { _ = "STUB: not implemented"; return }

func (b *builder) writeAndCodeExpr(and *ast.AndCodeExpr) { _ = "STUB: not implemented"; return }

func (b *builder) writeAndExpr(and *ast.AndExpr) { _ = "STUB: not implemented"; return }

func (b *builder) writeAnyMatcher(any *ast.AnyMatcher) { _ = "STUB: not implemented"; return }

func (b *builder) writeCharClassMatcher(ch *ast.CharClassMatcher) {
	_ = "STUB: not implemented"
	return
}

// BasicLatinLookup calculates the decision results for the first 256 characters of the UTF-8 character
// set for a given set of chars, ranges and unicodeClasses to speedup the CharClassMatcher.
func BasicLatinLookup(chars, ranges []rune, unicodeClasses []string, ignoreCase bool) (basicLatinChars [128]bool) {
	_ = "STUB: not implemented"
	return nil
}

func (b *builder) writeChoiceExpr(ch *ast.ChoiceExpr) { _ = "STUB: not implemented"; return }

func (b *builder) writeLabeledExpr(lab *ast.LabeledExpr) { _ = "STUB: not implemented"; return }

func (b *builder) writeLitMatcher(lit *ast.LitMatcher) { _ = "STUB: not implemented"; return }

func (b *builder) writeNotCodeExpr(not *ast.NotCodeExpr) { _ = "STUB: not implemented"; return }

func (b *builder) writeNotExpr(not *ast.NotExpr) { _ = "STUB: not implemented"; return }

func (b *builder) writeOneOrMoreExpr(one *ast.OneOrMoreExpr) { _ = "STUB: not implemented"; return }

func (b *builder) writeRecoveryExpr(recover *ast.RecoveryExpr) { _ = "STUB: not implemented"; return }

func (b *builder) writeRuleRefExpr(ref *ast.RuleRefExpr) { _ = "STUB: not implemented"; return }

func (b *builder) writeSeqExpr(seq *ast.SeqExpr) { _ = "STUB: not implemented"; return }

func (b *builder) writeStateCodeExpr(state *ast.StateCodeExpr) { _ = "STUB: not implemented"; return }

func (b *builder) writeThrowExpr(throw *ast.ThrowExpr) { _ = "STUB: not implemented"; return }

func (b *builder) writeZeroOrMoreExpr(zero *ast.ZeroOrMoreExpr) { _ = "STUB: not implemented"; return }

func (b *builder) writeZeroOrOneExpr(zero *ast.ZeroOrOneExpr) { _ = "STUB: not implemented"; return }

func (b *builder) writeRuleCode(rule *ast.Rule) { _ = "STUB: not implemented"; return }

// keep trace of the current rule, as the code blocks are created
// in functions named "on<RuleName><#ExprIndex>".

func (b *builder) pushArgsSet() { _ = "STUB: not implemented"; return }

func (b *builder) popArgsSet() { _ = "STUB: not implemented"; return }

func (b *builder) addArg(arg *ast.Identifier) { _ = "STUB: not implemented"; return }

func (b *builder) writeExprCode(expr ast.Expression) { _ = "STUB: not implemented"; return }

func (b *builder) writeActionExprCode(act *ast.ActionExpr) { _ = "STUB: not implemented"; return }

// already rendered, prevent duplicates

func (b *builder) writeAndCodeExprCode(and *ast.AndCodeExpr) { _ = "STUB: not implemented"; return }

// already rendered, prevent duplicates

func (b *builder) writeNotCodeExprCode(not *ast.NotCodeExpr) { _ = "STUB: not implemented"; return }

// already rendered, prevent duplicates

func (b *builder) writeStateCodeExprCode(state *ast.StateCodeExpr) {
	_ = "STUB: not implemented"
	return
}

// already rendered, prevent duplicates

func (b *builder) writeFunc(funcIx int, code *ast.CodeBlock, callTpl, funcTpl string) {
	_ = "STUB: not implemented"
	return
}

func (b *builder) writeStaticCode() { _ = "STUB: not implemented"; return }

// This is very unlikely to ever happen

// Clean the ==template== comments from the generated parser

// This is very unlikely to ever happen

func (b *builder) funcName(ix int) string { _ = "STUB: not implemented"; return "" }

func (b *builder) writef(f string, args ...any) { _ = "STUB: not implemented"; return }

func (b *builder) writelnf(f string, args ...any) { _ = "STUB: not implemented"; return }

func (b *builder) writeln(f string) { _ = "STUB: not implemented"; return }
