// Code generated by pigeon; DO NOT EDIT.

package issue70

import (
	"errors"
	"io"
	"unicode"
)

var g = &grammar{
	rules: []*rule{
		{
			name: "X",
			pos:  position{line: 5, col: 1, offset: 21},
			expr: &actionExpr{
				pos: position{line: 5, col: 5, offset: 27},
				run: (*parser).callonX1,
				expr: &seqExpr{
					pos: position{line: 5, col: 5, offset: 27},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 5, col: 5, offset: 27},
							label: "a",
							expr: &ruleRefExpr{
								pos:  position{line: 5, col: 7, offset: 29},
								name: "Z",
							},
						},
						&notExpr{
							pos: position{line: 5, col: 9, offset: 31},
							expr: &anyMatcher{
								line: 5, col: 10, offset: 32,
							},
						},
					},
				},
			},
		},
		{
			name: "Y",
			pos:  position{line: 6, col: 1, offset: 52},
			expr: &ruleRefExpr{
				pos:  position{line: 6, col: 5, offset: 58},
				name: "Z",
			},
		},
		{
			name: "Z",
			pos:  position{line: 7, col: 1, offset: 60},
			expr: &zeroOrOneExpr{
				pos: position{line: 7, col: 5, offset: 66},
				expr: &actionExpr{
					pos: position{line: 7, col: 6, offset: 67},
					run: (*parser).callonZ2,
					expr: &litMatcher{
						pos:        position{line: 7, col: 6, offset: 67},
						val:        "Z",
						ignoreCase: false,
						want:       "\"Z\"",
					},
				},
			},
		},
	},
}

func (c *current) onX1(a any) (any, error) { _ = "STUB: not implemented"; return *new(any), nil }

func (p *parser) callonX1() (any, error) { _ = "STUB: not implemented"; return *new(any), nil }

func (c *current) onZ2() (any, error) { _ = "STUB: not implemented"; return *new(any), nil }

func (p *parser) callonZ2() (any, error) { _ = "STUB: not implemented"; return *new(any), nil }

var (
	// errNoRule is returned when the grammar to parse has no rule.
	errNoRule = errors.New("grammar has no rule")

	// errInvalidEntrypoint is returned when the specified entrypoint rule
	// does not exit.
	errInvalidEntrypoint = errors.New("invalid entrypoint")

	// errInvalidEncoding is returned when the source is not properly
	// utf8-encoded.
	errInvalidEncoding = errors.New("invalid encoding")

	// errMaxExprCnt is used to signal that the maximum number of
	// expressions have been parsed.
	errMaxExprCnt = errors.New("max number of expressions parsed")
)

// Option is a function that can set an option on the parser. It returns
// the previous setting as an Option.
type Option func(*parser) Option

// MaxExpressions creates an Option to stop parsing after the provided
// number of expressions have been parsed, if the value is 0 then the parser will
// parse for as many steps as needed (possibly an infinite number).
//
// The default for maxExprCnt is 0.
func MaxExpressions(maxExprCnt uint64) Option { _ = "STUB: not implemented"; return *new(Option) }

// Entrypoint creates an Option to set the rule name to use as entrypoint.
// The rule name must have been specified in the -alternate-entrypoints
// if generating the parser with the -optimize-grammar flag, otherwise
// it may have been optimized out. Passing an empty string sets the
// entrypoint to the first rule in the grammar.
//
// The default is to start parsing at the first rule in the grammar.
func Entrypoint(ruleName string) Option { _ = "STUB: not implemented"; return *new(Option) }

// AllowInvalidUTF8 creates an Option to allow invalid UTF-8 bytes.
// Every invalid UTF-8 byte is treated as a utf8.RuneError (U+FFFD)
// by character class matchers and is matched by the any matcher.
// The returned matched value, c.text and c.offset are NOT affected.
//
// The default is false.
func AllowInvalidUTF8(b bool) Option { _ = "STUB: not implemented"; return *new(Option) }

// Recover creates an Option to set the recover flag to b. When set to
// true, this causes the parser to recover from panics and convert it
// to an error. Setting it to false can be useful while debugging to
// access the full stack trace.
//
// The default is true.
func Recover(b bool) Option { _ = "STUB: not implemented"; return *new(Option) }

// GlobalStore creates an Option to set a key to a certain value in
// the globalStore.
func GlobalStore(key string, value any) Option { _ = "STUB: not implemented"; return *new(Option) }

// ParseFile parses the file identified by filename.
func ParseFile(filename string, opts ...Option) (i any, err error) {
	_ = "STUB: not implemented" // nolint: deadcode
	return *new(any), nil
}

// ParseReader parses the data from r using filename as information in the
// error messages.
func ParseReader(filename string, r io.Reader, opts ...Option) (any, error) {
	_ = "STUB: not implemented" // nolint: deadcode
	return *new(any), nil
}

// Parse parses the data from b using filename as information in the
// error messages.
func Parse(filename string, b []byte, opts ...Option) (any, error) {
	_ = "STUB: not implemented"
	return *new(any), nil
}

// position records a position in the text.
type position struct {
	line, col, offset int
}

func (p position) String() string { _ = "STUB: not implemented"; return "" }

// savepoint stores all state required to go back to this point in the
// parser.
type savepoint struct {
	position
	rn rune
	w  int
}

type current struct {
	pos  position // start position of the match
	text []byte   // raw text of the match

	// globalStore is a general store for the user to store arbitrary key-value
	// pairs that they need to manage and that they do not want tied to the
	// backtracking of the parser. This is only modified by the user and never
	// rolled back by the parser. It is always up to the user to keep this in a
	// consistent state.
	globalStore storeDict
}

type storeDict map[string]any

// the AST types...

// nolint: structcheck
type grammar struct {
	pos   position
	rules []*rule
}

// nolint: structcheck
type rule struct {
	pos         position
	name        string
	displayName string
	expr        any
}

// nolint: structcheck
type choiceExpr struct {
	pos          position
	alternatives []any
}

// nolint: structcheck
type actionExpr struct {
	pos  position
	expr any
	run  func(*parser) (any, error)
}

// nolint: structcheck
type recoveryExpr struct {
	pos          position
	expr         any
	recoverExpr  any
	failureLabel []string
}

// nolint: structcheck
type seqExpr struct {
	pos   position
	exprs []any
}

// nolint: structcheck
type throwExpr struct {
	pos   position
	label string
}

// nolint: structcheck
type labeledExpr struct {
	pos   position
	label string
	expr  any
}

// nolint: structcheck
type expr struct {
	pos  position
	expr any
}

type (
	andExpr        expr // nolint: structcheck
	notExpr        expr // nolint: structcheck
	zeroOrOneExpr  expr // nolint: structcheck
	zeroOrMoreExpr expr // nolint: structcheck
	oneOrMoreExpr  expr // nolint: structcheck
)

// nolint: structcheck
type ruleRefExpr struct {
	pos  position
	name string
}

// nolint: structcheck
type andCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

// nolint: structcheck
type notCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

// nolint: structcheck
type litMatcher struct {
	pos        position
	val        string
	ignoreCase bool
	want       string
}

// nolint: structcheck
type charClassMatcher struct {
	pos             position
	val             string
	basicLatinChars [128]bool
	chars           []rune
	ranges          []rune
	classes         []*unicode.RangeTable
	ignoreCase      bool
	inverted        bool
}

type anyMatcher position // nolint: structcheck

// errList cumulates the errors found by the parser.
type errList []error

func (e *errList) add(err error) { _ = "STUB: not implemented"; return }

func (e errList) err() error { _ = "STUB: not implemented"; return nil }

func (e *errList) dedupe() { _ = "STUB: not implemented"; return }

func (e errList) Error() string { _ = "STUB: not implemented"; return "" }

// parserError wraps an error with a prefix indicating the rule in which
// the error occurred. The original error is stored in the Inner field.
type parserError struct {
	Inner    error
	pos      position
	prefix   string
	expected []string
}

// Error returns the error message.
func (p *parserError) Error() string { _ = "STUB: not implemented"; return "" }

// newParser creates a parser with the specified input source and options.
func newParser(filename string, b []byte, opts ...Option) *parser {
	_ = "STUB: not implemented"
	return nil
}

// start rule is rule [0] unless an alternate entrypoint is specified

// setOptions applies the options to the parser.
func (p *parser) setOptions(opts []Option) { _ = "STUB: not implemented"; return }

// nolint: structcheck,deadcode
type resultTuple struct {
	v   any
	b   bool
	end savepoint
}

// nolint: varcheck
const choiceNoMatch = -1

// Stats stores some statistics, gathered during parsing
type Stats struct {
	// ExprCnt counts the number of expressions processed during parsing
	// This value is compared to the maximum number of expressions allowed
	// (set by the MaxExpressions option).
	ExprCnt uint64

	// ChoiceAltCnt is used to count for each ordered choice expression,
	// which alternative is used how may times.
	// These numbers allow to optimize the order of the ordered choice expression
	// to increase the performance of the parser
	//
	// The outer key of ChoiceAltCnt is composed of the name of the rule as well
	// as the line and the column of the ordered choice.
	// The inner key of ChoiceAltCnt is the number (one-based) of the matching alternative.
	// For each alternative the number of matches are counted. If an ordered choice does not
	// match, a special counter is incremented. The name of this counter is set with
	// the parser option Statistics.
	// For an alternative to be included in ChoiceAltCnt, it has to match at least once.
	ChoiceAltCnt map[string]map[string]int
}

// nolint: structcheck,maligned
type parser struct {
	filename string
	pt       savepoint
	cur      current

	data []byte
	errs *errList

	depth   int
	recover bool

	// rules table, maps the rule identifier to the rule node
	rules map[string]*rule
	// variables stack, map of label to value
	vstack []map[string]any
	// rule stack, allows identification of the current rule in errors
	rstack []*rule

	// parse fail
	maxFailPos            position
	maxFailExpected       []string
	maxFailInvertExpected bool

	// max number of expressions to be parsed
	maxExprCnt uint64
	// entrypoint for the parser
	entrypoint string

	allowInvalidUTF8 bool

	*Stats

	choiceNoMatch string
	// recovery expression stack, keeps track of the currently available recovery expression, these are traversed in reverse
	recoveryStack []map[string]any
}

// push a variable set on the vstack.
func (p *parser) pushV() { _ = "STUB: not implemented"; return }

// create new empty slot in the stack

// slice to 1 more

// get the last args set

// empty map, all good

// pop a variable set from the vstack.
func (p *parser) popV() {
	_ = "STUB: not implemented"
	// if the map is not empty, clear it
	return
}

// GC that map

// push a recovery expression with its labels to the recoveryStack
func (p *parser) pushRecovery(labels []string, expr any) { _ = "STUB: not implemented"; return }

// create new empty slot in the stack

// slice to 1 more

// pop a recovery expression from the recoveryStack
func (p *parser) popRecovery() {
	_ = "STUB: not implemented"
	// GC that map
	return
}

func (p *parser) addErr(err error) { _ = "STUB: not implemented"; return }

func (p *parser) addErrAt(err error, pos position, expected []string) {
	_ = "STUB: not implemented"
	return
}

func (p *parser) failAt(fail bool, pos position, want string) {
	_ = "STUB: not implemented"
	// process fail if parsing fails and not inverted or parsing succeeds and invert is set
	return
}

// read advances the parser to the next rune.
func (p *parser) read() { _ = "STUB: not implemented"; return }

// see utf8.DecodeRune

// restore parser position to the savepoint pt.
func (p *parser) restore(pt savepoint) { _ = "STUB: not implemented"; return }

// get the slice of bytes from the savepoint start to the current position.
func (p *parser) sliceFrom(start savepoint) []byte { _ = "STUB: not implemented"; return nil }

func (p *parser) buildRulesTable(g *grammar) { _ = "STUB: not implemented"; return }

// nolint: gocyclo
func (p *parser) parse(g *grammar) (val any, err error) {
	_ = "STUB: not implemented"
	return *new(any), nil
}

// TODO : not super critical but this could be generated

// panic can be used in action code to stop parsing immediately
// and return the panic as an error.

// advance to first rune

// If parsing fails, but no errors have been recorded, the expected values
// for the farthest parser position are returned as error.

func listJoin(list []string, sep string, lastSep string) string {
	_ = "STUB: not implemented"
	return ""
}

func (p *parser) parseRuleWrap(rule *rule) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (p *parser) parseRule(rule *rule) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (p *parser) parseExprWrap(expr any) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

// nolint: gocyclo
func (p *parser) parseExpr(expr any) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (p *parser) parseActionExpr(act *actionExpr) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (p *parser) parseAndCodeExpr(and *andCodeExpr) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (p *parser) parseAndExpr(and *andExpr) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (p *parser) parseAnyMatcher(any *anyMatcher) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

// EOF - see utf8.DecodeRune

// nolint: gocyclo
func (p *parser) parseCharClassMatcher(chr *charClassMatcher) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

// can't match EOF
// see utf8.DecodeRune

// try to match in the list of available chars

// try to match in the list of ranges

// try to match in the list of Unicode classes

func (p *parser) parseChoiceExpr(ch *choiceExpr) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

// dummy assignment to prevent compile error if optimized

func (p *parser) parseLabeledExpr(lab *labeledExpr) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (p *parser) parseLitMatcher(lit *litMatcher) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (p *parser) parseNotCodeExpr(not *notCodeExpr) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (p *parser) parseNotExpr(not *notExpr) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (p *parser) parseOneOrMoreExpr(expr *oneOrMoreExpr) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

// did not match once, no match

func (p *parser) parseRecoveryExpr(recover *recoveryExpr) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (p *parser) parseRuleRefExpr(ref *ruleRefExpr) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (p *parser) parseSeqExpr(seq *seqExpr) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (p *parser) parseThrowExpr(expr *throwExpr) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (p *parser) parseZeroOrMoreExpr(expr *zeroOrMoreExpr) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

func (p *parser) parseZeroOrOneExpr(expr *zeroOrOneExpr) (any, bool) {
	_ = "STUB: not implemented"
	return *new(any), false
}

// whether it matched or not, consider it a match
